### ISSUE TITLE
I cannot create bug reports on bugs.erlang.org

### ISSUE THREAD

**Issue by garazdawi** [erlang/otp#3052]
**Describe the bug**
It is no longer possible to create bugs at http://bugs.erlang.org

**To Reproduce**
Go to http://bugs.erlang.org and click on "Create", nothing happens.

**Expected behavior**
It should be possible to create a bug.

**Affected versions**
Started happening 10 minutes ago.

**Additional context**
Are we migrating from JIRA to github issues, or what is this all about?

**Comment by ranjanified** [comment]
The migration from JIRA (bugs.erlang.org) to Github-issues will happen tomorrow starting at 10 am CET.

Because of this there might be disturbances or impossible to access and create issues during some hours from 10 am.

The new place to create and browse issues towards the OTP project will be announced during the day.

/Kenneth , Erlang/OTP Ericsson

**Comment by garazdawi** [comment]
Migration is done! See https://github.com/erlang/otp/wiki/Bug-reports for details about how to open bug reports here.

**Comment by essen** [comment]
How will ticket numbers appear in release notes from now on?

Before: ERL-1234
After: ???

**Comment by jhogberg** [comment]
`GH-1234`
