### ISSUE TITLE
ERL-282: escript fails when redirecting stdout to less and less terminates

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3150]
Original reporter: `jj1bdx`
Affected version: `OTP-19.1`
Component: `erts`
Migrated from: https://bugs.erlang.org/browse/ERL-282

---

```
When executing the attached script {{lessbug.escript}} as
{{escript lessbug.escript | less}} and terminates less before displaying all the results,
BEAM crashes with a dump.
The system is macOS 10.12.0, Xcode 8.0, with OTP 19.1.3, compiled with the following options:
{{--enable-m64-build --enable-darwin-64bit --disable-hipe --enable-vm-probes --with-dynamic-trace=dtrace --disable-native-libs --enable-kernel-poll --without-odbc --enable-threads --enable-smp-support --with-wx --with-ssl=/usr/local/opt/openssl}}

This crash dump is not always reproducible: the output may not respond at all sometimes.

```

**Comment by garazdawi** [comment]
A bit more info here: #4553

**Comment by garazdawi** [comment]
I want to put down some of the reasons why I think that the issues linked above are duplicates of this.

In OTP-18 I introduced [this](2e84a2ab5e0f0c82c2d79f69cd2f4bff762762a4) commit that sets the stdin and stdout fds to NONBLOCKING on unix. The reason why this change was done is described in the commit message:

> Without this change an stdout write could block an entire scheduler if for some reason the pseudo tty on the other side does not consume the output of the Erlang shell.

As it turns out, this change comes with a host of issues for programs using the stdin/stdout fds of Erlang.

1) Firstly, programs that read the stdout from Erlang may get an FD as its stdin that already is in NONBLOCKING mode. Some versions of programs such as `less` and `cat` are not prepared for this and behave badly. This is what happens when you do `erl | cat`.

2) Secondly, when Erlang exits without setting its stdout/stdin fds to BLOCKING, some versions of bash/sh will not reset it and all of the sudden bash starts working with a NONBLOCKING fd, which it is not prepared for. This is when you get a garbled terminal.

A partial solution to this problem could be to call `sys_tty_reset` (as @jktomer points out in #4553) when SIGINT is encounter. However, this is not a foolproof method as a process can be killed by SIGKILL and then the same problem would remain.

So the solution for this in my mind is to remove the NONBLOCKING behaviour from the `ttsl_driver` and the `fd_driver`. This brings us back to the original problem of what to do when we try to write to stdout and it blocks.

The best solution that I can come up with is to put all writes on dirty I/O schedulers, however, that would mean that we need to rewrite the ttsl driver to use nifs and that is a lot of work. Also the `fd_driver` cannot be rewritten to a nif, so we would have to create another way to handle "oldshell".

So right now I'm leaning towards creating two driver threads inside each ttysl/fd port that deals with the problems of reading/writing to blocking fds. This seems to be the solution with the least amount of work that we know will work. Unless anyone else has any better ideas?

**Comment by jktomer** [comment]
I don't think making the file descriptor nonblocking is the issue for "tty output after interrupting with +Bd/killing any shell is hosed," rather it's the tty modes set in ttsl_sdrv.c's `tty_init`. (I was wrong that `sys_tty_reset` is the fix; I hadn't read it carefully enough).

I don't actually think setting a TTY FD to nonblocking mode changes behavior for other processes that have the same TTY open. (It will, of course, affect processes we fork off, but that doesn't seem to be a major concern for anyone.)

**Comment by max-au** [comment]
Do I understand correctly that the discussion is about this line: https://github.com/erlang/otp/blob/master/erts/emulator/drivers/unix/ttsl_drv.c#L334

I tried removing it, and it seems to make no difference, `erl +B` still garbles the console after Ctrl + C (at least for Mac OS).

**Comment by jktomer** [comment]
Setting the tty file descriptor to nonblocking is not the cause of garbled terminal output. The issue is the tcsetattr call in [tty_set](https://github.com/erlang/otp/blob/master/erts/emulator/drivers/unix/ttsl_drv.c#L1528), specifically the fact that it is normally called with the OPOST bit cleared as set up in [tty_init](https://github.com/erlang/otp/blob/master/erts/emulator/drivers/unix/ttsl_drv.c#L1477-L1487). The comment [above](https://github.com/erlang/otp/blob/master/erts/emulator/drivers/unix/ttsl_drv.c#L1446-L1451) helpfully notes that setting raw mode on the terminal is OK "assuming the caller will call the tty_reset() function (also in this file) when it's done with raw mode."

Setting the fd to nonblocking *may* cause other issues with pipelines.

**Comment by garazdawi** [comment]
What shell and OS versions are you using to trigger the error with a garbled terminal? Also what exactly are you doing to trigger it?

**Comment by garazdawi** [comment]
> zsh (interestingly, bash seems unaffected)

So that is why I haven't seen it. I'm still using bash on OS X and I very rarely run using `+B`.

**Comment by max-au** [comment]
All escripts (e.g. rebar3) are running with `+B`, so `rebar3 shell` leaves garbled TTY almost every time. I realised that it might be an easy fix though (unlike piping issue with nonblocking fd).

**Comment by jktomer** [comment]
On Tue, Mar 9, 2021 at 3:16 PM Maxim Fedorov ***@***.***>
wrote:

> I think this issue is actually two issues merged. Might be useful to split
> it.
>
> Garbled terminal can be consistently reproduced with Mac OS X 11.2.2 and
> zsh (interestingly, bash seems unaffected).
>
That's because bash explicitly resets the tty attributes whenever a child
program exits and the OS notes that it was terminated with a signal. Which
is actually a pretty clever feature and maybe I should upstream it to
zsh...
