### ISSUE TITLE
ERL-743: Please document gen_tcp:unrecv or provide a peek mechanism

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#3776]
Original reporter: `essen`
Affected version: `Not Specified`
Component: `kernel`
Migrated from: https://bugs.erlang.org/browse/ERL-743

---

```
There is currently no documented way to do a peek[1] on a TCP connection. There is however an undocumented function gen_tcp:unrecv/2[2] that can be used as an equivalent in at least some cases.

I need a peek/unrecv mechanism in order to efficiently handle the PROXY protocol header[3] on incoming connections. With peek/unrecv, I can do a single recv and get the full PROXY protocol header in the data returned. Without, I would need 1 to 3 recv depending on the scenario (unfortunately the most interesting scenario would require 3 recv).

The reason the data needs to stay in the socket is because the connection may be upgraded to TLS after the PROXY protocol header was read, so I either do not want to read any bytes from the TLS hello messages, or I want to put those bytes back via unrecv on the socket before calling ssl:handshake/3.

The example at the bottom of the PROXY protocol specification[3] uses peek followed by a recv with the size of what was processed. An alternative I can already do today is recv followed by an unrecv of the remainder of the data.

Please consider either documenting unrecv (or at least keeping it around undocumented after the NIF rewrite) or adding a peek mechanism (not necessarily using MSG_PEEK as long as the data remains buffered and can be read with a subsequent recv).

[1] https://github.com/erlang/otp/pull/335
[2] https://github.com/erlang/otp/blob/master/lib/kernel/src/gen_tcp.erl#L326
[3] https://www.haproxy.org/download/1.9/doc/proxy-protocol.txt
```

**Comment by nickva** [comment]
In Apache CouchDB, using Mochiweb, we had a need for a similar feature. That's how I found this issue. It turns out it wasn't possible to get the state of a client socket in passive mode without receiving or sending data on it, and it seemed racy to use `gen_tcp:unrecv/2` from a different process.

We tried `inet:monitor/1`, `inet:info/1`, `inet:getstat/1` and nothing worked. Using the new `socket` backend module with `MSG_PEEK` option would work, but then there is no `gen_tcp:recv/3,4` which takes extra options to allow passing in `MSG_PEEK` and we though switching to the new socket backend is too early for our project.

After a few experiments we found one thing that works and that's effectively calling `getsockopts(sock, getsockopts(sock, IPPROTO_TCP, TCP_INFO, ...)` via `inet:getopts/2`. All the modern unix-like os-es seem to support that in one way or another. They just use different constants for `IPPROTO_TCP` and `TCP_INFO` but the returned structure and the states are fairly uniform. The solution is not very pretty but it works for us for us for our set of supported platforms. The solution ended up looking like this: https://github.com/apache/couchdb/blob/d5701f437183c3742aab5812e298d5bb80cb0c15/src/chttpd/src/chttpd_util.erl#L153-L235. Thought I'd leave a note here in case anyone had the same issue and wanted an alternative solution.
