### ISSUE TITLE
ERL-1360: Parallelise cold starting Mnesia

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4367]
Original reporter: `vans163`
Affected version: `OTP-23.1`
Component: `mnesia`
Migrated from: https://bugs.erlang.org/browse/ERL-1360

---

```
Coldbooting a large database on a 32/64 core ryzen.  Only 1 core is used and the speed is about 100MBs of data loaded into mem every 2 seconds, the disk storage is NVME drive.

!image-2020-09-24-10-05-49-385.png!

I think it should be possible to parallelise this somehow? 
```

**Comment by dszoboszlay** [comment]
@vans163 I tried once to make Mnesia loader parallel, but the speed up didn't seem significant enough. Nevertheless, you can try it with your DB, I rebased the code on `master` and pushed to [parallel-mnesia_log](/dszoboszlay/otp/tree/parallel-mnesia_log).

The DCD is easy to process with parallel workers, the big issue is with the DCL, because it contains operations that need to be applied sequentially.

**Comment by dgud** [comment]
Will not do anything about this for now.

**Comment by vans163** [comment]
> @vans163 I tried once to make Mnesia loader parallel, but the speed up didn't seem significant enough. Nevertheless, you can try it with your DB, I rebased the code on `master` and pushed to [parallel-mnesia_log](/dszoboszlay/otp/tree/parallel-mnesia_log).
> 
> The DCD is easy to process with parallel workers, the big issue is with the DCL, because it contains operations that need to be applied sequentially.
> 
> By the way, my branch is not PR-ready, it misses tests etc. Actually I only checked that it sill compiles after forward porting it from OTP-18, so there are no guarantees that it would work at all. Sorry!

We just dropped mnesia a while back and rolled our own rocksdb+ets hybrid implementation. Fixed the problem lol.
