### ISSUE TITLE
ERL-1466: erl_prettypr:format/2 with utf8 encoding provides invalid binary literal strings

### ISSUE THREAD

**Issue by OTP-Maintainer** [erlang/otp#4460]
Original reporter: `okeuday`
Affected version: `Not Specified`
Component: `syntax_tools`
Migrated from: https://bugs.erlang.org/browse/ERL-1466

---

```
Was using Erlang/OTP 23.2.3 and Elixir 1.11.3 with https://github.com/okeuday/reltool_util/blob/master/ex2erl to discover this problem.  I had expected that erl_prettypr:format/2 would provide valid utf8 output when it is given the encoding option utf8.  However, with binary literal strings in the syntax tree that are invalid utf8, the output will fail compilation due to the output being invalid utf8.

So, a syntax tree that contains a binary like:
{noformat}
<<"½EÇ+\2031\\\006\027\031Ò¯K©AÓ">>
{noformat}
 will not be formatted as:
{noformat}
<<189,69,199,43,131,49,92,6,23,25,210,175,75,169,65,211>>
{noformat}
 for valid utf8 compilation.
```

**Comment by uabboli** [comment]
Hi,

I'm not sure I understand. I cannot see what erl_prettypr is doing wrong.

However, I'll point out something that looks like a bug.

If you call erl_prettypr:format/2 with {encoding,utf8}, you'll get a
result with character codes possibly greater than 255. Note that
file:write_file/2 expects bytes; it's your responsibility to make sure
the characters are encoded before writing them to file.

What happens if you change the source code to something like:

    -define(FILE_ENCODING, utf8).

    ErlangSourceCode0 = erl_prettypr:format(SyntaxTreeN,
                                            [{encoding, ?FILE_ENCODING}]),
    ErlangSourceCode0 = unicode:characters_to_binary(ErlangSourceCode0),
    ok = file:write_file(FilePathErlang, ErlangSourceCode),

If you still experience problems, I need an example I can run.

Best regards,

Hans Bolinder, Erlang/OTP team, Ericsson

**Comment by okeuday** [comment]
@uabboli Thank you for noticing this!  The problem was the absence of `unicode:characters_to_binary/1`.  With that change, the output is correct (otherwise the md5 for the [elixir module](https://github.com/CloudI/CloudI/commit/516420977aa3bb7b050e706f489d973d21864e0f#diff-e3304d72cd82dc091f9963f49d6ac17b11e082ab14a0f865c8f55a81f66a5112) wasn't written properly)
