### ISSUE TITLE
local fails at gen_tcp:listen/2 with kernel inet_backend = socket

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#4548]
**Describe the bug**
With the `OTP-24.0-rc1` release tag and the kernel application configured with `inet_backend = socket` for `gen_tcp` to use `gen_tcp_socket`, attempts to use `local` functionality fail.  Specifically, I observed this with `gen_tcp:listen(0, [... {ifaddr, {local, SocketPath}} ...])` returning `{error, enotsup}`

**To Reproduce**
I have been using a https://github.com/CloudI/CloudI compilation that uses the configure flag `--with-integration-tests-ran` and modifying the `etc/vm.config` file though it is likely easier to observe this in a `gen_tcp_socket` related test in Erlang/OTP.

**Expected behavior**
Normally gen_tcp would function for `local` use (in the same way when `inet_backend /= socket`).

**Affected versions**
`OTP-24.0-rc1`

**Additional context**
`local` works fine with `inet_backend /= socket` and `inet`/`tcp` appears to be fine with `inet_backend = socket`.

**Comment by RaimoNiskanen** [comment]
Can not reproduce:
``` erlang
$ erl -kernel inet_backend socket
Erlang/OTP 24 [RELEASE CANDIDATE 1] [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.0  (abort with ^G)
1> gen_tcp:listen(0, [{ifaddr,{local,"/tmp/kasta"}}]).
{ok,{'$inet',gen_tcp_socket,
             {<0.86.0>,{'$socket',#Ref<0.3034025962.4057333763.32207>}}}}
```
So something is different...

**Comment by okeuday** [comment]
@RaimoNiskanen I narrowed the problem down to `{nodelay,true}` with local use.  The other options that are used don't cause the `{error,enotsup}`.

Just to make the situation clearer, the full list of options used is:
```
gen_tcp:listen(0,[{ifaddr,{local,"/tmp/test"}},{nodelay,true},
                  binary,{packet,4},{backlog,1},{active,false},
                  {recbuf,65536},{sndbuf,65536},{delay_send,false},
                  {keepalive,false},{send_timeout,5000},{send_timeout_close,true}]).
```
However, `nodelay` set to `true` was the only option that caused the `enotsup`:
```
1> gen_tcp:listen(0,[{ifaddr,{local,"/tmp/test"}},{nodelay,true}]).
{error,enotsup}
```

**Comment by bmk** [comment]
I tested this with debug enabled and as far as I can see its the setsockopt function that returns enotsup (Operation not supported).
However the man page for tcp does not indicate any restrictions.
But, my experiments seems to indicate that this option does not work with domain = local!

**Comment by bmk** [comment]
I also found the following comment on stackoverflow:
"Unix domain sockets don't use Nagle (and obviously don't use TCP either)."
So I think we can assume that 'nodelay' cannot be used for Unix Domain Sockets (domain = local).

**Comment by RaimoNiskanen** [comment]
Well, then. `gen_tcp` and `inet_drv.c` causes some confusion here, and there is a backwards compatibility bug.

`nodelay` is a protocol level `tcp` option, and for the `local` address family there is no `tcp` protocol.  So the `nodelay` option is not supported, hence `enotsup`.  There is a `stream` protocol that acts as `tcp` and it is therefore we have piggy backed this protocol onto `gen_tcp`, when in fact for the `local` address family a more appropriate name would have been `gen_stream`. From the `socket` API this becomes clearer:
``` erlang
$ erl -kernel inet_backend socket
Erlang/OTP 24 [DEVELOPMENT] [erts-11.1.3] [source-f81a48e770] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V11.1.3  (abort with ^G)
1> f(S), {ok,S} = socket:open(local, stream).              
{ok,{'$socket',#Ref<0.2913727644.3694264327.26982>}}
2> socket:bind(S, #{family => local, path => "/tmp/test"}).
ok
3> socket:listen(S, 5).                                    
ok
4> socket:setopt(S, {tcp,nodelay}, true).                  
{error,enotsup}
5> socket:open(local, stream, tcp).               
{error,eprotonosupport}
```
Note that in `5>` it shows that trying to use choose `tcp` for address/protocol family `local` and protocol type `stream` is not supported.  The only valid protocol for `local,stream` is the default protocol, which is what `gen_tcp` chooses for you, covertly.

Then, `inet_drv.c` has got some options that it ignores errors for, when set from a list (for backwards compatibility reasons *it* claims in a comment), and `tcp,nodelay` is among them.  Just watch this:
``` erlang
$ erl -kernel inet_backend socket
Erlang/OTP 24 [DEVELOPMENT] [erts-11.1.3] [source-f81a48e770] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V11.1.3  (abort with ^G)
1> {ok,S} = gen_tcp:listen(0,[{ifaddr,{local,"/tmp/test"}}]).
{ok,{'$inet',gen_tcp_socket,
             {<0.86.0>,{'$socket',#Ref<0.1231052080.475136003.165120>}}}}
2> inet:setopts(S, [{nodelay,true}]).                        
{error,enotsup}
```
We have missed to implement this error ignoring for some options when setting them in a list, and to be completely backwards compatible (bug compatible) we need to implement that.  But maybe we shoul not; perhaps we should instead document this discrepancy because it is a major release and ignoring some errors that `inet_drv.c` does is probably a rather stupid idea; backwards compatibility taken too far..., or?

In this case the current behaviour of `inet_drv.c` hides the fact that you are setting an option that is not valid for this protocol, while `inet_backend = socket` does not hide that.

**Comment by RaimoNiskanen** [comment]
So, I would like to declare this "not a bug" and document the difference.  Would that be satisfactory?

**Comment by okeuday** [comment]
@RaimoNiskanen Yes, that is the best approach.  It is a new interface and detecting options that are not supported for the address family is a positive thing.  Thanks for checking this.

**Comment by RaimoNiskanen** [comment]
To be documented, then.
