### ISSUE TITLE
Reserved words cond and let

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4590]
Are the reserved words `cond` and `let` so, for historical reasons, or are they effectively used (even if not exposed)?

I don't see them mentioned in the doc.s, apart for the "Reserved words" sections, (and also at least `cond` in an EEP, I believe).

If not used, I could PR to get them removed from the doc. Otherwise, I'm OK if this Issue is closed (at least a future search will potentially make it clearer - I didn't find anything on these, before).

---

(this is neither a bug request nor a feature request, but it might evolve into a pull request)

**Comment by bjorng** [comment]
They are not used.

A long time ago time there was some idea that it could be a good idea to add a `let`...`in` construct to the language. Even though the let construct  was never actually implemented, `let` was made a reserved word. (`in` would have been made reserved, too, had it not been that it was too frequently used as an atom in existing code.)

There have been several attempts to add a `cond` construct to the language, but they all failed.

Since it is cumbersome to add new reserved keywords to the language, we will usually not "unreserve" a keyword in case that we would want to use it in the future.

So I think that `cond` and `let` should remain reserved, and they should remain documented as reserved to make it clear that they cannot be used as atoms. If you think it would be helpful, you can submit a pull request to add a note saying something about `let` and `cond` being reserved for potential future use but not currently used in the language.

**Comment by paulo-ferraz-oliveira** [comment]
@bjorng, thanks for the detailed explanation. As I remembered that `query` was once a reserved word and it's no longer there (at the time we used `q` and now can freely use a semantically proper `query`) I though these might go the same route.

I'll pull request to add that note.
