### ISSUE TITLE
ct: failing end_per_testcase not failing test

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4617]
Using Common Test, a test gets an OK result even if its corresponding `end_per_testcase` fails. Is this by design? It may be, since the report shows the error as "WARNING: end_per_testcase thrown! WARNING: end_per_testcase failed!", but... the result is still OK (with time "Died"), which is not useful if, say, you're running tests in CI.

Should https://erlang.org/doc/man/ct_suite.html#Module:end_per_testcase-2 make this more explicit? This is what it states (among other things), at the moment: "By returning {fail, Reason}, TestCase is marked as faulty (even though it was successful in the sense that it returned a value instead of terminating).".

**Comment by IngelaAndin** [comment]
Yes, it is by design. A test case fails if the erlang process running the test case crashes and succeeds if it terminates normally. end_per_testcase is actually not run if the test case fails. Which I think is a design flaw, but controversial to change due to backward compatibility.  That is why I often find myself calling end_per_testcase in init_per_testcase to make sure I have a clean start.  

Feel free to suggest documentation improvements.
