### ISSUE TITLE
New type nonempty_binary

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4636]
Just throwing this in here to see if fruitful discussion revolves around it. Feel free to close if deemed too silly.

We get a few warnings (via `dialyzer`) stating that a given `binary()` could be `-spec(_).`ed as `<<_:8, _:_*8>>` (for example). This represents a "nonempty_binary" (not the only type, ofc). Since that name (`nonempty_binary`) is a much more representative then whatever notation `dialyzer` was able to infer, would it be good to have a type representing this in Erlang, directly?

(rationale: - close but not the same thing, ofc - we already have `nonempty_list`, `nonempty_string`)

---

We have done stuff like declaring a type named `nonempty_binary` with that definition and then using that, but it's in a shared lib. and I'd like to avoid depending on that for something as simple as a type declaration, while also not wanting to force all our lib.s to declare their own type.

Also note that even in OTP's base there's a couple of occurrences for this or even `<<_:32,_:_*8>>`, `<<_:64,_:_*8>>`.

**Comment by kostis** [comment]
I was asked to throw my .02 here.

First of all, note that according to the [Types and Function Specifications](https://erlang.org/doc/reference_manual/typespec.html) only `nonempty_list(Type)` (and its improper sibling) are built-in types, while `nonempty_list()` and `nonempty_string()` are _type aliases_, i.e. thought as being defined with type definitions of the form:
```erlang
-type nonempty_list()   :: nonempty_list(any()).
-type nonempty_string() :: nonempty_list(char()).
```

I guess the list of type aliases could be extended with these two:
```erlang
-type nonempty_binary()    :: <<_:8,_:*8>>.
-type nonempty_bitstring() :: <<_:1._:*1>>.
```
so that, as mentioned above, applications and libraries do not need to define such aliases of their own.  Another advantage is that this makes the set of built-in type aliases more uniform, which is a **big plus** in my opinion.  The amount of changes that this will require to OTP is probably not big, so it's something to consider, even for 24.0.

The only two downsides that I see are:
1. Libraries that already define such types will need to adapt to the addition of a new _reserved_ type name.
2. Tools, such as e.g. [PropEr](https://github.com/proper-testing/proper), that understand built-in types and aliases will also need to adapt.

If it is of any interest, my vote is **positive** for the addition of these two type aliases in the type language.

Having written that though, note that this addition will not solve the (perceived) "problem" mentioned in the post above, for cases of the form `<<_:32,_:8>>`, `<<_:64,_:*>>`, etc.  On the other hand, by default, Dialyzer does **not** spit out warnings like the post above claims.  (It only does so, when options which are off by default are used).

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for your analysis, @kostis. Let me add a few comments.

> aliases could be extended

This is basically what I had in mind 😄 

> The amount of changes that this will require to OTP

I'm not sure I understand this. Being just a _type alias_, not a built-in type, what changes do you foresee, except adding these?
I've never added anything to `erlang.erl` specifically (IIRC), so am not sure what this implies. Willing to give it a go, though.

> downsides that I see

1. you mean in the cases they already define their own types with the same name? OTP 24, for example, introduced `error/3` and this started clashing with existing code also (namely in `parse_trans`) - I'm not trying to justify it 😄, I'm just stating there's prior examples of similar changes that force stuff to be adapted
2. here I'm not sure what you mean; if possible, could you point me to a piece of code where this would be an issue? I'd like to dig deeper

> Dialyzer does not **spit** out warnings

I'm not sure I implied that `dialyzer` had this behavior "by default", but I guess one might read it like so from the general content of the initial message. I nonetheless sadly omitted (for no particular reason - simple oversight) the options which I used:

* `error_handling`
* `underspecs` % this is the one producing the warning
* `unknown`
* `unmatched_returns`

FWIW, `dialyzer` is a great tool that we use all the time and pay detailed attention to its output. This issue is not a `dialyzer` issue, it's a usability issue, IMO.
