### ISSUE TITLE
Check why disk_log is not able to repair files with zero bytes

### ISSUE THREAD

**Issue by tothlac** [erlang/otp#4755]
If I a disklog file is create with the following code:

```
create() ->
  disk_log:open([{name, mylog},
                 {mode,read_write},
                 {size, {2000000, 1000}},
                 {type, wrap},
                 {repair, true},
                 {file, "mylog"}]).
```

and I fill with zero bytes all the belonging disk_log files, using this command:
```
tothlac:otp printf "a" > mylog.1; printf "a" > mylog.idx; printf "a" > mylog.siz
tothlac:otp ls -alt | head
total 143040
-rw-r--r--    1 tothlac  staff         0 Apr 21 11:05 mylog.siz
-rw-r--r--    1 tothlac  staff         0 Apr 21 11:05 mylog.idx
-rw-r--r--    1 tothlac  staff         0 Apr 21 11:05 mylog.1
```

I got the following error:
```
2> create_disk_log:create().
{error,{not_a_log_file,"mylog.1"}}
```

In case there is a single 'a' character in the files, it is different:
```
tothlac:otp printf "a" > mylog.1; printf "a" > mylog.idx; printf "a" > mylog.siz
tothlac:otp ls -alt | head
total 143064
-rw-r--r--    1 tothlac  staff         1 Apr 21 11:07 mylog.siz
-rw-r--r--    1 tothlac  staff         1 Apr 21 11:07 mylog.idx
-rw-r--r--    1 tothlac  staff         1 Apr 21 11:07 mylog.1
```

Now it is able to open the files:
```
3> create_disk_log:create().
{ok,mylog}
```

The problem is that the node where disk_log was started for some reason probably crashed in the previous run, so these files were created with zero bytes. That's another strange thing. How could disk_log create those files with 0 bytes being written into them?

In my opinion, if disk_log is able to start with files containing a simple character it should be able to start with empty files as well.

**Comment by uabboli** [comment]
Hi,

> and I fill with zero bytes all the belonging disk_log files
>
> 2> create_disk_log:create().
> {error,{not_a_log_file,"mylog.1"}}

The empty index file (mylog.idx) is not considered well-formed by
disk_log. disk_log then assumes that the current file is mylog.1 and
all files are empty.

Although the current file mylog.1 is found, the file has no header
(the format is 'internal' by default), and an error is returned.

> In case there is a single 'a' character in the files, it is different:
>
> 3> create_disk_log:create().
> {ok,mylog}

In this case the index file is considered well-formed, and after
reading mylog.idx, disk_log thinks the current file is mylog.97. The
reason is that "a" written onto mylog.idx is interpreted as the
integer 97. The file mylog.97 does not exist and is created.

One could argue that the index file should have some kind of header or
magic bytes so that disk_log would not consider the index file
well-formed. If so, 'not_a_log_file' would have been returned also in
this case.

> The problem is that the node where disk_log was started for some
> reason probably crashed in the previous run, so these files were
> created with zero bytes. That's another strange thing. How could
> disk_log create those files with 0 bytes being written into them?

Most probably disk_log did not create those files with zero bytes.
When the node crashed, the files were open and their contents reset by
the system, immediately or when restarting (repairing).

Best regards,

Hans Bolinder, Erlang/OTP team, Ericsson
