### ISSUE TITLE
Scheduler poll causes performance degradation

### ISSUE THREAD

**Issue by luos** [erlang/otp#4759]
**Describe the bug**
Hi,

Recently at a request of one of our customers we began benchmarking different Erlang versions to be used with RabbitMQ. 

We tracked down an issue which was introduced in Erlang 21.2 with the implementation of Kernel Poll. 

When this feature is used, in certain scenarios RabbitMQ's throughput drops to roughly half. 

The setup used was the following:

Four RabbitMQ 3.7.9s, AWS c5d.9xlarge machines with 36 cores and 72 GB of memory, data directory mounted on NVME SSD. 

The RabbitMQs are clustered through Erlang distribution, which roughly means that the incoming messages will go through from the first node to all other nodes through the distribution links,  twice. 

In the test scenario we load RabbitMQ by connecting (TCP) 10 producers, 10 consumers, 10 queues and we publish as many 5 kb messages as possible. The number of incoming and outgoing messages will be roughly equal, as is the behaviour of RabbitMQ, it will try to balance this.

We performed the tests using Erlang 21.0.5 as a baseline, then ran the different fixes against 21.3.8.22 using RabbitMQ 3.7.9. The configurations were the following:
* Erlang 21.0.5 as a baseline 
* Erlang 21.3.8.22 with no changes, compiled on the machines
* Erlang 21.3.8.22 compiled with editing the source to not use scheduler poll (https://github.com/erlang/otp/compare/master...luos:disable-kernel-poll)
* Erlang 21.3.8.22 compiled with the --disable-kernel-poll feature flag
* Erlang 21.3.8.22 compiled with the preliminary "eagerness" fix (https://github.com/erlang/otp/compare/master...garazdawi:lukas/erts/rabbitmq-polling-eagerness) 

![kép](https://user-images.githubusercontent.com/923194/115712393-011b4e80-a375-11eb-9009-9190731fa6a9.png)

The latency of the messages was also higher, even though the CPU usage of the nodes was way lower, in which case we would expect lower latency: 

![kép](https://user-images.githubusercontent.com/923194/115712526-2b6d0c00-a375-11eb-8a77-96f7b55056ca.png)

We discussed this with @garazdawi  and he already provided us with some fixes which you can see on the graph as "eagerness fix". 

We also know that not all workloads are affected equally, I will try to post some more details later.
I will attach some additional information later. 

**To Reproduce**

I will attach this later if I can reproduce in a smaller environment. 

**Expected behavior**
* Performance is on the same level as on 21.0.5 or can be achieved by tuning some knobs, while keeping the same performance in other scenarios :)

**Affected versions**
21.2+

CC @garazdawi @olikasg

**Comment by garazdawi** [comment]
My understanding of this issue is that polling for new events on FDs is not done quickly enough and thus the system is starved for work. The reason for this is because FDs that exhibit a `{active, true}` behaviour are moved into a pollset that is polled by a scheduler instead of the pollthread. If the polling has been done by a pollthread, any new event would be discovered immediately, but since it is done by a scheduler it has to wait for the scheduler to decide that it is time to poll.

This was introduced in OTP-21.2 as a means of reducing the CPU overhead of having to manipulate the kernel-space pollset.

The `eagerness` test that we tested changed the scheduling priorities so that all ports run at `max` priority and also increased the frequency in which the scheduler pollset is polled.

The options as I see them:
1. Introduce a configure switch that disables the scheduler pollset.
2. Introduce a run-time switch that disables the scheduler pollset.
3. Try to improve the scheduler polling heuristic

In the short term, option 1 is the most reasonable. I don't know what a better heuristic would look like as this is basically a tradeoff in between CPU and latency, and that tradeoff is difficult for us to do.

I'm a bit skeptical about adding a run-time switch for this as it involves quite a bit of code and changes the layout of quite a few structs.

**Comment by luos** [comment]
Hi,

I think we'd prefer as well if this could be resolved without a flag. 

I ran some additional tests with newer Erlang and picked the changes onto 23.3.1, please see the results below: 

![kép](https://user-images.githubusercontent.com/923194/115733307-0edacf00-a389-11eb-9e28-bd2643111084.png)

According to this this gets pretty close to the "no scheduler poll" version.

**Comment by garazdawi** [comment]
I've come up with two other ideas that we may want to try.

1. Reintroduce the eager check IO functionality. This was default enabled in OTP-20.3, and should in theory help with this issue, but from what we have measured OTP-20.3 has the same degradation as OTP-21.2 so this might not be the path to go.
2. Add a runtime switch that increases the priority of running ports. The largest gain in the eagerness patch came from running ports at `max` priority. So if we add a switch that allows the user to control how high priority ports should have this might help with this issue. However, we will be back to the beginning once the `socket` implementation is used for the distribution as they do not use ports.

**Comment by okeuday** [comment]
Would usage of `+spp true` improve throughput in your testing?

**Comment by garazdawi** [comment]
> Would usage of +spp true improve throughput in your testing?

I doubt it as the `+spp` option only affects how processes interact with ports. In this case it is the events triggered by the poll implementation that is the problem.

**Comment by lhoguin** [comment]
Interesting ticket. It is worth pointing out that the scenario in question is using classic mirrored queues, which will be deprecated in the near future and removed in RabbitMQ 4.0 (specifically the mirror part, non-mirrored classic queues will remain).

I wonder if the same issue occurs when using Quorum Queues instead.

I also wonder if simply setting the distribution port to `max` is enough or if the problem involves the ports for the connections as well. And if it is the distribution, whether the problem still exists with a distribution driver that uses `socket` instead of ports (I got one, but I suppose with 24 you could just set the `inet_backend` to try).

**Comment by garazdawi** [comment]
> I also wonder if simply setting the distribution port to `max` is enough or if the problem involves the ports for the connections as well.

Yes, that might very well be the case. However, for ports it is not a simple thing to do as today ports have no priority. Implementing priorities for ports would be a huge undertaking, but adding a switch that increases the priority of ports in relation to process is relatively simple.

> And if it is the distribution, whether the problem still exists with a distribution driver that uses socket instead of ports (I got one, but I suppose with 24 you could just set the inet_backend to try).

That would indeed be interesting to know!

**Comment by michaelklishin** [comment]
If this helps with comparing on Erlang 24, RabbitMQ 3.8 will gain Erlang 24 support starting with `3.8.16` in early May. The PR is ready and waiting for `3.8.15` to ship.

**Comment by luos** [comment]
Hi, 

We performed roughly the same test using Erlang 24.2.1 and got roughly the same result. Do you think there will is a solution to this or maybe some flag was introduced which can help with this? 

Thank you

**Comment by garazdawi** [comment]
Hello!

We have not done anything to address this issue yet.

A quick fix would be to add the configure option to disable scheduler polling, but I'm not really happy with that solution as I would like to come up with a way to do this that would make the best choice without the user having to configure anything.

I'll try to make us take some time soon and think about this issue and see what we can come up with.
