### ISSUE TITLE
socket: online doc. seems "off"

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [erlang/otp#4781]
**Describe the bug**
It's more of a documentation "issue".

**To Reproduce**
Go to http://erlang.org/documentation/doc-12.0-rc3/lib/kernel-8.0/doc/html/socket.html.

**Expected behavior**
1. I'd expect the function listing to be sorted (e.g. `getopt/3` is the first function, even before `accept/1`) - this appears to only affect the function "tree" though...
2. `accept/2` is shown twice in the "body" (http://erlang.org/documentation/doc-12.0-rc3/lib/kernel-8.0/doc/html/socket.html#accept-2, for example, and just below it)
3. `send` is kind of confusing (seems all functions are mixed)
4. ... (there might be more issues)

**Affected versions**
24.0, at least.

Sorry for not being more explicit. I just wanted to bring attention to the subject. I relied on the doc. to develop `socket`-related stuff before, and it wasn't always easy.

**Comment by RaimoNiskanen** [comment]
I have been fighting with basing the documentation on the type specifications, and the tools are sometimes rather blunt.

1) `getopt/3` and `setopt/4` are backwards compatibility functions for which I deemed it too awkward to write type specifications for; they are just wrappers on the other `getopt/*` and `setopts/*` functions.  Therefore their documentation is written "old style" and for some reason they get sorted before all other functions by our documentation builder.  I would call it a bug in the documentation builder and get someone to look at it.

2) ... and ...
3) These functions are grouped together according to their timeout argument, since that is what chiefly is different about their description. So the first occurence for `accept/2` is with `Timeout = infinity` so it is grouped with `accept/1`, which has the default `infinity` timeout.  This grouping is used for all functions with a `Timeout` argument such as `send/*`.  For `accept/1,2` and `connect/2,3`, Timeout :: 'infinity' is not stated in the function head - I will try to improve that, but in all other functions you should see the difference in the documentation function head.

I hope that makes it clearer, and that the documentation is more readable realizing that pattern.

4)  Please let us know if you find more explicit issues.

**Comment by RaimoNiskanen** [comment]
1) There was a workaround, or a solution.  Sorting was corrected by removing leading and trailing whitespace within the XML tags for the old style function heads, which apparently is according to our DTD, but still uncomfortable...  So that detail, and `infinity` in the function head for `accept/*` and `connect/*`, will be fixed in 24.0.

**Comment by lhoguin** [comment]
And one accept/2 being duplicated.

**Comment by paulo-ferraz-oliveira** [comment]
I'll have to wait for the next version of the docs to be able to judge this again. Thanks for your time. I'm Okay with you closing this issue if nobody else has issues with `socket`'s doc. (or just let it linger for a while, as reference, and close it in a couple of weeks).

**Comment by garazdawi** [comment]
> I'll have to wait for the next version of the docs to be able to judge this again. Thanks for your time. I'm Okay with you closing this issue if nobody else has issues with socket's doc. (or just let it linger for a while, as reference, and close it in a couple of weeks).

You can download the latest HTML docs of matsre from the github actions. For example https://github.com/erlang/otp/actions/runs/795353394 has a couple of artifacts attached, one of which is the HTML docs.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks @garazdawi. I appreciate it, though it's kinda cumbersome. Is there no way to have them published somewhere directly?

**Comment by garazdawi** [comment]
There used to be: http://blog.erlang.org/cd/ but it stopped working a while ago when Travis stopped being as Open Source friendly as they used to be. Someday I will get that working again, but I've not taken the time to do that yet.

**Comment by paulo-ferraz-oliveira** [comment]
> ... and ...

Not sure this is a question, but I'll expand.

```
accept(ListenSocket) -> {ok, Socket} | {error, Reason}
accept(ListenSocket, Timeout) -> {ok, Socket} | {error, Reason}
accept(ListenSocket, Timeout) -> {ok, Socket} | {error, Reason}
```

This is how I find the headings.

Now:
1. I know not what `accept/1` does: I'm used to finding some text like "The same as `accept(ListenSocket, ...)`", but in this case I don't know what `...` is (I'm assuming `infinity`, but I maybe be assuming wrong) - i.e. there's no description there,
2. I see two `accept/2` with a slight variation in input: one uses `non_neg_integer()`, the other one `infinity` (I'm not sure this is the "norm" in OTP doc., but I think I've seen otherwise - so I get used to some form of doc. then this one surprises me - I use the doc.s regularly),
3. the second `accept/2` states "The same as accept/1 but returns {error, timeout} if no connection has been accepted after Timeout milliseconds." but yeah 😄 I know not what `accept/1` does...

**Comment by RaimoNiskanen** [comment]
@lhoguin: `accept/2` is not duplicated.  The clauses are different and divided into 3 descriptions.

His is how the headings will be:
```erlang
accept(ListenSocket) -> {ok, Socket} | {error, Reason}.
accept(ListenSocket, Timeout :: infinity) -> {ok, Socket} | {error, Reason}.
  %% Explanation that the function(s) wait for a connection to arrive.

accept(ListenSocket, Timeout :: integer() >= 0) -> {ok, Socket} | {error, Reason | timeout}.
  %% Explanation that it is the same as accept/1 but returns after Timeout if no connection has arrived.

accept(ListenSocket, Timeout :: nowait) -> {ok, Socket} | {select, SelectInfo} | {error, Reason}.
accept(ListenSocket, SelectHandle :: select_handle()) -> {ok, Socket} | {select, SelectInfo} | {error, Reason}.
  %% Explanation that they are the same as accept/1 but returns immediately, maybe with a SelectInfo.
```
An explanation is for the functions in its heading.  So `accept/1` and `accept(_, infinity)` share explanation because they behave identically.

**Comment by paulo-ferraz-oliveira** [comment]
OK, thanks. I got confused, but now it's better. I do understand the rationale and the (implicit) explanation of "... is for the functions in its heading", but I guess I'm used to stuff like http://erlang.org/documentation/doc-12.0-rc3/lib/stdlib-3.15/doc/html/proplists.html#get_value-2: `Equivalent to get_value(Key, List, undefined).`.

**Comment by RaimoNiskanen** [comment]
Yes, I thought there would be so many references of that kind for different arities between all send*, recv*, and so forth functions, so I thought it was clearer to group those with identical behaviour together over one description.

**Comment by paulo-ferraz-oliveira** [comment]
Sure :) Thanks for your time and patience.
