### ISSUE TITLE
Possible issue with SSL 

### ISSUE THREAD

**Issue by stuartjohnston1967** [erlang/otp#4892]
stuartjoh...@gmail.com’s profile photo
stuartjoh...@gmail.com
6 May 2021, 15:12:34
to rabbitmq-discuss

So we have rabbitMQ running sucessfully on version v3.8.9 / Erlang 23.3.2

But when we upgrade rabbitMQ to version v3.8.11/14/16 we receive errors within the erlang crash dump file 

Slogan: Kernel pid terminated (application_controller) ({application_start_failure,rabbitmq_prelaunch,{{shutdown,{failed_to_start_child,prelaunch,{config_decryption_error,{key,ssl_options},badarg}}},{rabbit_p
System version: Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
Compiled: Wed Mar 31 23:18:54 2021
Taints: crypto
Atoms: 17494
Calling Thread: scheduler:1

Has the config file or order for ssl_options changed

I've hunted the internet but couldn't fine anything

When we remove the SSL parts it starts up fine....

Best Regards

Stuart

**Comment by IngelaAndin** [comment]
There was an unintentional change of options handling order in OTP-23.2.7,  Fixed in OTP-23.3 and OTP-23.2.7.2.  This could cause problems for applications that set an option multiple times.

**Comment by michaelklishin** [comment]
@stuartjohnston1967 can you please share your config files so both OTP and RabbitMQ maintainers do not guess what may be going on?

**Comment by stuartjohnston1967** [comment]
Sorry I though I had , please find below I've "X" out the PASSWORD

[
  {kernel, [{net_ticktime,  120}]},
  {ssl, [{versions, ['tlsv1.2']}]},
  {rabbit, [
            {tcp_listeners, []},
            {ssl_listeners, [5671]},
            {ssl_options, [{cacertfile,"/opt/rabbitmq/ssl/all_cacerts.pem"},
                           {certfile,  "/opt/rabbitmq/ssl/wsprabbitmq_pre_server_certificate.pem"},
                           {keyfile,   "/opt/rabbitmq/ssl/wsprabbitmq_pre_encrypted_key.pem"},
                           {password,
                             {encrypted,
                              <<"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX">>
                             }
                           },
                           {fail_if_no_peer_cert, true},
                           {verify, verify_peer}
                          ]},
            {config_entry_decoder, [{passphrase, {file, "/opt/rabbitmq/config/.passphrase"}}]}
           ]}
].

**Comment by stuartjohnston1967** [comment]
That is from the advanced.config located within /etc/rabbitmq

**Comment by michaelklishin** [comment]
I simplified this to

``` Erlang
[
  {kernel, [
    {net_ticktime, 120}
  ]},
  {ssl, [{versions, ['tlsv1.2']}]},
  {rabbit, [
    {tcp_listeners, []},
    {ssl_listeners, [5671]},
    {ssl_options, [
      {cacertfile, "/path/to/tls-gen.git/basic/result/server_certificate.pem"},
      {certfile,     "/path/to/tls-gen.git/basic/result/server_certificate.pem"},
      {keyfile,      "/path/to/tls-gen.git/basic/result/server_key.pem"},
      {fail_if_no_peer_cert, true},
      {verify, verify_peer}
    ]}
  ]}
].
```

because my private key doesn't have a password.

With this config, a `3.8.16` node starts successfully on 23.3 and 24.0.1.

**Comment by michaelklishin** [comment]
Looks like the options exception comes from a config decoding step. I can reproduce the following exception

```
1> Configuring logger redirection
04:12:31.243 [error]

04:12:31.248 [error] BOOT FAILED
BOOT FAILED
04:12:31.248 [error] ===========
===========
04:12:31.248 [error] Exception during startup:
Exception during startup:
04:12:31.249 [error]

04:12:31.249 [error]     supervisor:'-start_children/2-fun-0-'/3 line 355
    supervisor:'-start_children/2-fun-0-'/3 line 355
04:12:31.249 [error]     supervisor:do_start_child/2 line 371
    supervisor:do_start_child/2 line 371
04:12:31.249 [error]     supervisor:do_start_child_i/3 line 385
    supervisor:do_start_child_i/3 line 385
04:12:31.249 [error]     rabbit_prelaunch:run_prelaunch_first_phase/0 line 27
    rabbit_prelaunch:run_prelaunch_first_phase/0 line 27
04:12:31.249 [error]     rabbit_prelaunch:do_run/0 line 108
    rabbit_prelaunch:do_run/0 line 108
04:12:31.249 [error]     rabbit_prelaunch_conf:setup/1 line 33
    rabbit_prelaunch_conf:setup/1 line 33
04:12:31.250 [error]     rabbit_prelaunch_conf:decrypt_config/2 line 404
    rabbit_prelaunch_conf:decrypt_config/2 line 404
04:12:31.250 [error]     rabbit_prelaunch_conf:decrypt_app/3 line 425
    rabbit_prelaunch_conf:decrypt_app/3 line 425
04:12:31.250 [error] throw:{config_decryption_error,{key,default_pass},badarg}
throw:{config_decryption_error,{key,default_pass},badarg}
04:12:31.250 [error]
```

using this config file

``` erl
[
  {rabbit, [
      {default_user, <<"guest">>},
      {default_pass,
        {encrypted,
         <<"cPAymwqmMnbPXXRVqVzpxJdrS8mHEKuo2V+3vt1u/fymexD9oztQ2G/oJ4PAaSb2c5N/hRJ2aqP/X0VAfx8xOQ==">>
        }
      },
      {config_entry_decoder, [
             {passphrase, <<"mypassphrase">>}
         ]}
    ]}
].
```

but when I regenerate the encrypted value:

``` shell
# please generate your own value!
rabbitmqctl encode '<<"guest">>' mypassphrase
# => {encrypted,<<"tZWNxKgL0Eh58KZS3oVbIaFDKktJIyXC4XYzZsPZSEM/xX4hTXwOsOZc7HUChGh9">>}
```

so the config becomes

``` erl
[
  {rabbit, [
      {default_user, <<"guest">>},
      {default_pass,
        {encrypted,<<"YY6lG63gy88uMR8uYxL2tYP+4Gtec+dJr1N+9/iBTjecBX5OEU4mVCNejMZn4n2P">>}
      },
      {config_entry_decoder, [
             {passphrase, <<"mypassphrase">>}
         ]}
    ]}
].
```

So in your case, the config value cannot be decrypted. It can be due to default TLS-related option changes (e.g. what cipher suite is used when you don't specify any). I don't remember any defaults changing in RabbitMQ but
recent Erlang releases certain had a [fair number of changes](https://github.com/erlang/otp/commits/master/lib/ssl/src), including cipher suite names and likely defaults.

I see no evidence of an issue in the OTP's `ssl` app. Perhaps you need to regenerate the encrypted config value.

**Comment by IngelaAndin** [comment]
You can sanity check your key file by using the public_key application. 

```
{ok, PemBin} = file:read_file("key.pem"). 
[KeyEntry] = public_key:pem_decode(PemBin).
public_key:pem_entry_decode(KeyEntry, Password).
```

It will not be impacted by cipher suite defaults for TLS as they have nothing to do with the possible encryption of the key file. Also, we have not changed the string names of the cipher suites we did change the erlang representation though. We provide filter functions so that you should not need to write long lists of maps (earlier tuples). For backward compatibility (even though no longer documented), it is also possible to configure using the string names if you prefer writing long explicit lists. The string names are the RFC names or the OpenSSL names although the translation of the OpenSSL names is broken in older versions of OTP.

**Comment by stuartjohnston1967** [comment]
I can confirm that after performing the above steps it has resolved the issue … thank you for your assistance 

Stuart
