### ISSUE TITLE
Map pattern matching in function call to work according to Joe's Programming Erlang

### ISSUE THREAD

**Issue by jacksonbenete** [erlang/otp#4963]
Hello there,

Has been a while (2013) since Joe's Programming Erlang Second Edition was out "documenting" a never implemented feature.
#3056 and #3467 are two old reports of this case that I could find.

One of these, #3056, is labeled "wontfix", and the other one, #3467, is labeled as "priority:low".

Some rationale from Joe himself regarding the problem can be found on [erlang-questions mailing list](http://erlang.org/pipermail/erlang-questions/2016-February/087606.html).

### Summing up:
```
-module(count_characters).
-export([count_characters/1]).

count_characters(Str) ->
   count_characters(Str, #{}).

count_characters([H|T], #{ H := N }=X) ->
   count_characters(T, X#{ H := N+1 });
count_characters([H|T], X) ->
   count_characters(T, X#{ H => 1 });
count_characters([], X) ->
   X. 
```
`> c(count_characters)
`> count_characters.erl:7: variable 'H' is unbound`
`error`

The idea is that `count_characters([H|T], #{ H := N }=X) ->` would match and Bind the Head, and then use the Head variable/address to populate the Map. 
As some user have said in some of those old issues, the problem is probably that this would be the same as saying `count_characters([H|T], #{ H1 := N }=X}) when H1 =:= H ->` which will not work since H1 is Unbound.

### My questions on this are: 
1 - It's hard to understand, did this just doesn't work as "documented" but there is any other way of doing that, or it doesn't work at all?

2 - It's the case that it will never be fixed or is the case that it's a low priority enhancement? This is also confusing.

3 - Why did this is a low priority? Is it hard to implement or it's just something not wanted by the community/maintainers?

**Comment by bjorng** [comment]
It turned out that this feature turned out to be harder to implement than was initially thought, so it was dropped from the initial implementation of maps, but our intention was to attempt to implement it later.

We did an attempt to implement it for OTP 23, after having extended matching of maps to allow guard expressions as keys and as sizes in binary in #2521. We expected it to be non-trivial, but it turned out to be even more complicated, so we dropped it again.

We have currently no plans to attempt to implement it again.

Here is some background and a few examples to show why the feature is much more complicated than it might seem.

First note that matching is is not done in any particular order. There is no implied left-to-right order. Matching can be done in any order, producing the same result. Therefore, if Joe's example above is expected to work, then the following example should also work:

```
count_characters(#{ H := N }=X, [H|T]) ->
   count_characters(X#{ H := N+1 }, T);
      .
      .
      .
```

We did get that example to work. In fact, as long as there were no repeated variables, even quite convoluted examples worked:

    convoluted(Ref,
           #{ node(Ref) := NodeId, Loop := universal_answer},
           [{NodeId, Size} | T],
           <<Int:(Size*8+length(T)),Loop>>) when is_reference(Ref) ->
        Int.

Things started to get complicated when variables were repeated:

    foo(#{K := K}, K) -> ok.

Our prototype could not handle it, but I think that it should. It should be equivalent to the following, which our prototype could handle:

    foo(#{K := V}, K) when K =:= V -> ok.

My opinion is that rules for variable binding and variable scoping in Erlang is already too complicated and they should not be made more complicated. Therefore, my opinion is that we should not try to implement this feature.

Leaving out personal opinion, it is clear that a correct implementation of this feature that would handle all edge cases (if at all possible) would require a huge amount of work.

Here are some more details about [why we dropped this feature](https://github.com/bjorng/otp/blob/24bff391300c98efaabbcd154bf25cde711d67dc/SHELVED.md).
