### ISSUE TITLE
Cannot reallocate 0 bytes of memory (of type "estack")

### ISSUE THREAD

**Issue by lhoguin** [erlang/otp#4981]
**Describe the bug**
The combination of RabbitMQ 3.8.17 and Erlang/OTP 24.0 running on Windows 2012R2 results in the node crashing. The `temp_alloc` allocator seems to have a huge size in the crash dump (17GB?) despite the node using only a few hundred megabytes of memory.

```
=erl_crash_dump:0.5
Fri Jun 11 21:11:51 2021
Slogan: temp_alloc: Cannot reallocate 0 bytes of memory (of type "estack").
System version: Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [jit]
Compiled: Tue May 11 21:51:34 2021
Taints: asn1rt_nif,crypto
Atoms: 48012
Calling Thread: scheduler:1
```

I can share the `erl_crash.dump` file privately, please provide me with an email.

**Affected versions**
OTP 24.0 downloaded from erlang.org. There are no issues with OTP 23.3.

**Additional context**
RabbitMQ sets the folllowing allocator flags at startup:

```
+MBas ageffcbf +MHas ageffcbf +MBlmbcs 512 +MHlmbcs 512 +MMmcs 30
```

**Comment by rickard-green** [comment]
You can send the crash dump to rickard at erlang.org

**Comment by lhoguin** [comment]
It was too big so I shared a link to it instead. Please confirm when you have received it.

**Comment by rickard-green** [comment]
Thanks, I've download it now, but have not yet had the time to look at it yet.

**Comment by rickard-green** [comment]
I'm quite sure you hit the bug fixed by PR #4875. The fix in the PR was released in the [OTP 24.0.2](http://erlang.org/download/OTP-24.0.2.README) patch.

If I interpret the crashdump and your code (found it on github) correct, the crash happens in `pmon:monitor/2` when performing `maps:put/2` with a large map containing external process identifiers as keys which is consistent with the bug fixed by the PR. The `temp_alloc` instance of the scheduler thread executing this has a memory block of a size that is a bit larger than 16 GB which it most likely is trying to reallocate to a block of a size a bit more than 32 GB. When the system is not able to satisfy this request it makes a crashdump. The format string used when printing the slogan "Cannot reallocate..." is faulty, but works on all systems except for 64-bit Windows which most likely is the reason why the slogan claims "0 bytes".

I'm closing this issue. If this should happen again on a OTP 24.0.2 or later system, please reopen or create a new issue.

**Comment by gagarski** [comment]
A little off-topic question: is there a reason why 24.0.2 release (and 24.0.3 release) were not published on http://erlang.org/download/?

**Comment by garazdawi** [comment]
> A little off-topic question: is there a reason why 24.0.2 release (and 24.0.3 release) were not published on http://erlang.org/download/?
> 
> (I mean source code archives)

Seems to be a bug in our patch build tools. You can still download the prebuilt archive from github, but seems like the erlang.org archive for some reason is not uploaded.

**Comment by rickard-green** [comment]
We have never published source code archives for emergency patch packages at <http://erlang.org/download/>. We've only manually published source code archives there for maintenance patch packages (typically a minor version bump) and new releases.

Source code archives can be found at <https://erlang.org/download/otp_versions_tree.html> (links to github) and on the github release pages.
