### ISSUE TITLE
Application freezes during start failure when logging to the group leader

### ISSUE THREAD

**Issue by galdor** [erlang/otp#5005]
# Issue
An OTP application whose `init/2` callback fails is supposed to cause the node to exit (the usual "Kernel pid terminated (application_controller)…"). While this error is being handled, OTP uses `logger` to emit error reports. If a log handler uses the group leader as IO device, the node will not exit; in console mode, the prompt will not be printed. Worse, no error message is being printed. It seems something is stuck.

# Context
Following a discussion on erlang-questions regarding the fact that logger messages are not captured by EUnit (so that they can be printed only when a test case fails), I start using a log handler which writes to the group leader, as suggested in [this email](https://erlang.org/pipermail/erlang-questions/2021-May/101010.html) by @garazdawi (you may find it interesting). I ended up discovering this problem because my application `start/2` callback failed and I could not get any error message, with the node staying up.

# Example
The following application reproduces the problem every time: https://github.com/galdor/erl-gl-test.
You can clone it, and run:
```
rebar3 release
./_build/default/rel/gl_test/bin/gl_test console
```

In `src/gl_test_app.erl`, using `standard_error` for `Device` fixes the problem.

# Environment
- Erlang/OTP 24.
- Rebar 3.16.1.

**Comment by josevalim** [comment]
So the reason why this happens is because the group leader of your application supervision tree is an application master process. This is used, between other things, to identify to which application a process in your supervision tree belongs to.  

However, when your application terminates, the application master terminates, which means that, when you log, the group leader and therefore the IO device is long gone.

The most immediate solution that comes to mind is to replace the default handler right before running the test suite, for example, when setting up the EUnit test suite.

**Comment by galdor** [comment]
Your explaination makes sense, but the fact there is no protection against this kind of issue in the IO system is really scary. I do not know how the application system and the logger system interact, but even `io:format` writes to the group leader by default. I would expect this situation to be correctly handled, or at least to trigger a clear error about the situation.

**Comment by josevalim** [comment]
I wouldn’t personally consider it scary because, if I set the group leader to myself, all I need to do is to not perform any IO message from said process. Which is easy to do as long as I own the code.

IMO, the issue is really the log callbacks, which allow you to run any code from any logging process. In any case, I agree a simple check that the `IODevice /= self()` doesn’t hurt.

**Comment by galdor** [comment]
But I did not set the group leader to myself, so yes the problem comes from the logger.

**Comment by josevalim** [comment]
Yeah, exactly. I sent PR #5008 with a possible solution to this problem, which is to fail early when calling yourself. I implemented it for both `io` and `gen` modules.
