### ISSUE TITLE
A lots memory consumption when writing/deleting million records in mnesia table

### ISSUE THREAD

**Issue by htdat148** [erlang/otp#5018]
**Describe the bug**
I am running an Erlang application that often writes millions of records to the mnesia table for making a scheduler. When the time is due, the records get executed and removed from the table. The table is configured with `{type, disk_copies}, {type, ordered_set}`. I use transaction operations for writing and dirty operations for deleting records.

I have an experiment that writes 2 million records and then deletes all of them: the RAM memory was not reclaimed after it finished. There is a spike that twice increases the memory when I start to delete those records. For example, the beam memory starts as 75MB, and becomes after the experiment 410MB. I've used erlang:memory() to inspect the memory before and after, found that the memory was eaten by the `process_used, binary, ets` but actually, I did not have any action with binary and ets usage should be fine. If I use erlang:garbage_collect(Pid) for all running processes, the memory gets reclaimed, leaving 180MB.

I also found some posts which have the same issue: https://elixirforum.com/t/mnesia-transaction-memory-is-increasing/36268
I tried to find the `transaction_consumption.txt` in that is mentioned in mnesia `implementation.txt` but I couldn't.

**To Reproduce**

```
-record(test, {test_1, test_2, test_3, test_4, test_5}).

mnesia:create_table(test,
                        [{attributes, record_info(fields, test)}, {type, ordered_set}]),

write_mnesia_test() ->
  Fun = fun() ->
          lists:map(fun(X) ->
                      mnesia:write({test, X, X+1, X+2, X+3, X+4})
                    end, lists:seq(1, 2000000))
        end,
  mnesia:transaction(Fun).

delete_mnesia_test() ->
      AllKeys = mnesia:dirty_all_keys(test),
      [mnesia:dirty_delete({test, Key}) || Key <- AllKeys].
```

**Expected behavior**
I think the memory should be reclaimed like when I run the `erlang:garbage_collect`.

**Affected versions**
I am using Erlang OTP 22

**Comment by rickard-green** [comment]
The above does not indicate a bug.

A process is not garbage collected unless it reach certain limits, for example it needs to allocate heap data and there is no free heap available. If a process stops executing, it does not matter how long time passes, it wont automatically garbage collect by itself unless it reaches one of these limits. A garbage collection can be forced by calling `erlang:garbage_collect()` though.

A process that has had a lot of live data (and by this have grown large) but at the time of the garbage collection has no live data wont shrink down to its original size immediately. It will instead get a relatively large heap. The heap space is free for usage by the process, but it is allocated from the systems point of view. The relatively large heap is selected in order to avoid triggering garbage collections unnecessarily frequent.

Not only your processes are effected when you execute. Also other processes might build up heap in order to serve your processes.

If you look at memory consumption via `top` or similar, it is also expected that memory usage will have increased after execution even if you are able to garbage collect every process down into its initial size. This due to memory allocators that place memory blocks into larger chunks of memory which cannot be removed until the whole memory chunk is free. More or less every memory allocation system that exist will have this characteristic.
