### ISSUE TITLE
`sets:is_set(#{})` should not return `true` on any map

### ISSUE THREAD

**Issue by kubantsev** [erlang/otp#5046]
**Describe the bug**

Code relying on `sets:is_set/1` and treating map as set's element produce unexpected result in OTP 24:
```
S = sets:add_element(#{some => "one map"}, sets:new()),
M = #{any => "another map"},

S1 = case sets:is_set(M) of
   true -> sets:union(S, M);
   _ -> sets:add_element(M, S)
end,

sets:to_list(S1).

[#{some => "one map"}, any]
```
This results to lost map-element.

**To Reproduce**
OTP 23:
```
> sets:is_set(#{}).
false
```

OTP 24
```
> sets:is_set(#{}).
true
```

**Expected behavior**
1. `sets:is_set/1` should return `false` on arbitrary map.

**Affected versions**
OTP 24

**Additional context**

This new behaviour was introduced since https://github.com/erlang/otp/commit/e66941e8d7c47b973dff94c0308ea85a6be1958e
> Initial implementation of EEP 50
```
%% is_set(Set) -> boolean().
%%  Return 'true' if Set is a set of elements, else 'false'.
-spec is_set(Set) -> boolean() when
      Set :: term().
is_set(#{}) -> true;
is_set(#set{}) -> true;
is_set(_) -> false.
```

**Comment by garazdawi** [comment]
hmm. The only way that I can see us solve this is to add `is_set/2` that takes a version of which type of set it is that we testing for. Or I suppose we could wrap the entire map into a `set` tuple.

**Comment by garazdawi** [comment]
Pinging @josevalim to see if he has any opinions as he wrote the original code.

**Comment by josevalim** [comment]
I am not sure what is the way to go either. Some thoughts:

1. One of the original proposals was to introduce a `mapsets` module: that would provide a better indication that sets are represented by maps. Downsides: this ship has probably sailed?

2. Document the behaviour that maps are sets and therefore `sets:is_set/1` will return true for any map. Downside: doesn't really solve the issue but it will warn users to handle it upstream and distinguish it (or wrap the set) themselves.

3. Wrap it in a tuple. Downsides: performance? Also complexity as we need to support three versions?

4. Check if the values of the map are all empty lists. Downsides: can still have false positives and it might be expensive.

To play a bit of devil's advocate: any API that asks if something is a set or a key will be inherently ambiguous if you want to store a set inside a set. Because of this, I would go with 2 (and perhaps 4).

**Comment by asabil** [comment]
I still think that 3 is probably the most correct solution: https://github.com/erlang/otp/pull/2864#discussion_r522261239

In the current implementation, a `set()` **is a** `map()` or a `#set{}` record: `set() :: map() | #set{}`.

I think from a typing perspective that a `set()` should have been a distinct type from a map `set() :: #set{} | #set_map{}`.

However, as @josevalim pointed out this approach would require supporting three versions now that the ship has sailed, maybe 2 is the only viable option now?

**Comment by michalmuskala** [comment]
I think 2 is the most natural approach comparing to other things in Erlang. Erlang does not have distinct, nominal types and pretending like it does breaks down sooner or later. If the question answered by the `set:is_set` function is "can this be passed safely to other functions in the `set` module?", than the current behaviour is entirely correct - those functions can handle any map.

**Comment by mikpe** [comment]
I would argue that either `sets:is_set/1` should be deprecated, or sets should be wrapped to make their representation more easily distinguishable from other data. Personally I would rather see `sets:is_set/1` go away, since it's unreasonable to have such a type predicate in a dynamically typed language where the type in question simply is composed of other simpler types. Regardless of how you represent sets in Erlang, there's always going to be another type predicate that also returns `true` for them.

**Comment by bjorng** [comment]
I think that we should document the current behavior (2), and also I agree with @mikpe that we should deprecate `sets:is_set/1`.

**Comment by okeuday** [comment]
@bjorng I am disappointed that `sets:is_set/1` would get deprecated.  It is advantageous to have an `is_*` datatype function as an assert before usage that could be something else, to have a simpler failure that explains the problem.  The previous map sets changes did break it because the map wasn't wrapped in a record that identified the data type.  I understand that you could always create Erlang data that is able to make `sets:is_set/1` return true.  However, the goal is to avoid any unexpected errors while acknowledging that sets is a composite data type instead of a primitive data type.

**Comment by bjorng** [comment]
We have not decided yet that `sets:is_set/1` will be deprecated. My comment above expressed my personal opinion. We will have to discuss it within the OTP team, and probably in the OTP Technical Board.

**Comment by jhogberg** [comment]
Going with @mikpe's reasoning we've decided to soft-deprecate `sets:is_set/1` and similar functions in other modules. There's no way to reliably tell types apart without sufficient context, and we don't think it's right to pretend otherwise.

The documentation will be updated to say that the functions are deprecated to discourage their future use, but you will not get deprecation warnings for them to avoid breaking old code compiled with `-Werror`, nor do we plan to remove them in the future.
