### ISSUE TITLE
Incomplete specification for timer conversion functions 

### ISSUE THREAD

**Issue by VitorTrin** [erlang/otp#5052]
the `timer` has function for conversion other time units into milliseconds. An undocumented feature is that they can receive floating point parameters. For example

```erlang
1> timer:hours(1).
36000
2> timer:hours(0.5).
1.8e6
```
Yet the documentation says that these functions should only use integers and only returns integers 

Should this possibility be in the documentation or it should not be used?

**Comment by garazdawi** [comment]
Hello!

The `timer:hours/1` function is meant to be used as input into `timer:sleep/1` and other `timer` functions. So I think that the current documented inputs are correct.

We could add positive floats as valid inputs, but then the code would have to round the return value before returning it.

**Comment by VitorTrin** [comment]
Why couldn't we document that positive floats return other positive floats? Becaust `timer:sleep/1` doesn't accept floats?

**Comment by garazdawi** [comment]
> Because timer:sleep/1 doesn't accept floats?

And all the other timer functions. In the end, it is `receive after Time -> timeout end` that does not support floats which is why the API is as it is.

**Comment by RaimoNiskanen** [comment]
This is simply a case of the implementation being more lenient than the documentation and the type specification.

So if application code should rely on the current behaviour for `float()` as an argument to `timer:hours/1` (or `timer:minutes/1`, `timer:seconds/1`, `timer:now_diff/2`, `timer:hms/3`, ...), it would be using an undocumented feature, which we might remove anytime without warning.

It is important that the code (e.g in `timer`) behaves correctly for documented arguments (types and values)). To define the behaviour for all arguments (types and values) (for all functions in all libraries) is less important, and sometimes much work for very little gain.  In this case it is simply the guard `when is_integer(Hours), 0 =< Hours` that is missing, but in the general case it might be very hard to promise to crash for any argument(s /combinations) that is not according to the type specification.

When the the type specification is violated, the function may do anything, *including* returning some value.

**Comment by RaimoNiskanen** [comment]
That said; when reasoning about changing a behaviour like this:

Since this is a very old function, and there might exist code that (accidentally) depends on a float being passed - we do not dare changing a(n even incorrect) behaviour unless in a major release.

On the other hand; since the purpose of this function is to return a time-out value that must be an integer, then returning a float might be considered a bug, and accepting a float might be hiding a bug.

Thus; I think accepting a float is not correct and should be changed, preferably in a major release.  But I am sure there are many other functions in our libraries that are in more dire need of attention.

**Comment by VitorTrin** [comment]
Wow, that is a really through response, thanks for your time!
