### ISSUE TITLE
Opacity check misses violations in unions

### ISSUE THREAD

**Issue by mheiber** [erlang/otp#5118]
**Describe the bug**

In some cases when an opaque type is part of a union opacity violations are not caught.

**To Reproduce**

Given this module:

```erl
-module(sample).
-compile([export_all, nowarn_export_all]).

% No opacity violation error
-spec test1() -> {term(), term()} | a.
test1() ->
    case rand:uniform(2) of
        1 -> gb_sets:new();
        2 -> a
    end.


% (correct) opacity violation error
-spec test2() -> {term(), term()} | a.
test2() ->
    case rand:uniform(2) of
        1 -> gb_sets:new()
    end.
```

Run `dialyzer sample.erl`

**Expected behavior**

Opacity violation for `test1/0`. The error should be the same as for `test2/0`.

My reasoning is baed on [the definition of opacity from the OTP docs on type specs](https://erlang.org/doc/reference_manual/typespec.html):

> Types declared as opaque represent sets of terms whose structure is not supposed to be visible from outside of their defining module. That is, only the module defining them is allowed to depend on their term structure.

`test1/0` depends on the structure of `gb_sets:set/1` being a two-tuple, which is why this looks like an opacity violation to me.

**Affected versions**

OTP 25 and (probably) earlier versions

**Comment by jhogberg** [comment]
This is a fun one, but it's neither a bug nor does it have anything to do with opaque types. Let's tweak your example a little bit:
```erlang
%% No error here either!
-spec test1() -> a | b.
test1() ->
    case rand:uniform(2) of
        1 -> neither_a_nor_b;
        2 -> a
    end.

%% Invalid type specification
-spec test2() -> a | b.
test2() ->
    case rand:uniform(2) of
        1 -> neither_a_nor_b
    end.

%% No union, but still no warning!?
-spec test3() -> a.
test3() ->
    case rand:uniform(2) of
        1 -> definitely_not_a;
        2 -> a
    end.

%% Error here, despite the spec for test1/0 saying `a | b`!
test4() ->
      b = test1().
```

What's going on?

The spec for `test1/0` says it returns a subtype of `a | b`, and the implementation can return `a | neither_a_nor_b`. Since `neither_a_nor_b` is not a subtype of `a | b`, `dialyzer` concludes that case is impossible and thus the function returns `a`. Your example had an opaque type in place of `neither_a_nor_b`, but the principle is the same.

By default, `dialyzer` will stay quiet as long as there's some way for things to succeed and only warns when things _always_ go off the rails. You can see this in how it warns for `test2/0` since it either crashes or returns an illegal value, and how it stays quiet for `test1/0` since things are fine when `rand:uniform(2)` happens to return `2`.

You can tell `dialyzer` to warn you when the specs and implementation don't line up by passing the `underspecs` and `overspecs` options, they're pretty noisy though:

```
t.erl:5:2: The success typing for t:test1/0 implies that the function might also return 
          'neither_a_nor_b' but the specification return is 
          'a' | 'b'
t.erl:5:2: The specification for t:test1/0 states that the function might also return 
          'b' but the inferred return is 
          'a' | 'neither_a_nor_b'
t.erl:13:2: Invalid type specification for function t:test2/0. The success typing is 
          () -> 'neither_a_nor_b'
t.erl:20:2: The success typing for t:test3/0 implies that the function might also return 
          'definitely_not_a' but the specification return is 
          'a'
t.erl:28:1: Function test4/0 has no local return
t.erl:29:7: The pattern 
          'b' can never match the type 
          'a'
```

Using the same options on your example I expected to see the warning you wanted, but funny enough I ran into an actual opacity bug in under-/overspecs, making the warning text misleading:

```
t.erl:5:2: Type specification t:test1
          () -> {term(), term()} | 'a' is a supertype of the success typing: t:test1
          () -> 'a' | gb_sets:set(_)
```

The actual warning text should be as below, I'll make a PR fixing that shortly.

```
t.erl:5:2: The specification for t:test1/0 states that the function might also return 
          {term(), term()} but the inferred return is 
          'a' | gb_sets:set(_)
```

**Comment by mheiber** [comment]
@jhogberg thanks for taking the time to write this up and dig into the examples, it's really helpful for getting me closer to forming a mental model for what Dialyzer is doing.

Re

> [Previous comment](https://github.com/erlang/otp/issues/5118#issuecomment-913806861): "By default, dialyzer will stay quiet as long as there's some way for things to succeed ..."

it sounds like you're referring to success typing. But I didn't think success typing was related to opacity. "some way for things to succeed" means (to me) "there may be at least one code path that will not error at runtime." But the definition of opacity is not related to runtime errors (if I understand correctly):

> [Erlang docs](https://erlang.org/doc/reference_manual/typespec.html#type-declarations-of-user-defined-types): "Types declared as opaque represent sets of terms whose structure is not supposed to be visible from outside of their defining module."

**Comment by jhogberg** [comment]
> it sounds like you're referring to success typing. But I didn't think success typing was related to opacity.

I used atoms on purpose to show that returning a value not allowed by the spec will not raise a warning by default as long as there's some other way for the function to return a valid value.

If a function's implementation can return `a | c` and the spec says it will return `a | b`, `dialyzer` will happily conclude that the function will never return `c` and move on with life. The same holds if the implementation were to return `a | gb_sets:set(_)` -- opacity has nothing to do with it.

> "some way for things to succeed" means (to me) "there may be at least one code path that will not error at runtime.

Breaking a constraint is considered an error even if the function might not necessarily crash at runtime.

**Comment by mheiber** [comment]
thanks for explaining!

**Comment by jhogberg** [comment]
No problem, and thanks for your report! We wouldn't have found the overspecs/underspecs bug without it. :)
