### ISSUE TITLE
Delayed file I/O: explicit flush + close without flushing

### ISSUE THREAD

**Issue by lhoguin** [erlang/otp#5220]
**Is your feature request related to a problem? Please describe.**
I am using `delayed_write` to boost the write performance of an append-only file. A couple problems came up when using this:

* It is not possible to flush without performing another operation. I need to sometimes read from this file from a different fd and as a result I want the writer fd to flush before the reader tries to read, for the data to be there. I solved this by calling `gen_statem:call(Pid, '$synchronous_flush')` directly, but that's not optimal from a maintenance point of view.
* On close the buffer will ALWAYS be flushed. When the file gets deleted immediately after close, I do not need the buffer to be flushed. I suspect I can just kill the pid to "solve" the issue but that's not optimal either.

**Describe the solution you'd like**
I'm not sure what form the solution should take exactly but there should be a function call to force a flush without accessing the fd data directly. Similarly there should be a way to drop the buffer and close the file if it is no longer needed.

**Comment by jhogberg** [comment]
This feels quite specialized, and it might be better for you to handle the buffering yourself. Is there anything preventing you from doing so?

**Comment by lhoguin** [comment]
I mean, the code is there, I guess I could copy paste the file and do my two tiny changes.

Perhaps the "optionally don't sync on close" part is specialised, but I do not think wanting to flush to disk on demand is that unusual.

**Comment by jhogberg** [comment]
We didn't think anyone would use a `delayed_write` file for IPC, and it's unusual enough that no one else has suggested it yet.

The `file` module is very cluttery and I'd rather not add a one-off thing for `delayed_write` alone if I can avoid it. There's nothing wrong with using `position(Fd, cur)` or `truncate(Fd)` to indirectly flush the buffers, it's documented and shouldn't cost too much. Have you compared the performance of the two approaches?

**Comment by essen** [comment]
It's not for IPC it's just to keep the code simpler with separate fds for reading and writing using the same process. Typically it'll read/write from a different file, or read/write from the same file but gets a cache hit when reading. Perhaps one of those functions is OK performance wise, it just doesn't feel right. Happy to drop this if you think there's nothing to be done.

For more context: It's a "first" implementation so it's possible that down the line the delayed write approach gets dropped in favor of something else. I think what I really want is a file used very much like a sort of memory block (append unless there's some space that has been freed earlier in the file). Data location must be known on write (even if the data doesn't get flushed to disk because it was freed). Data is FIFO. Fragmentation not a big concern in that scenario. But I don't know how to do this efficiently in only Erlang.

**Comment by jhogberg** [comment]
> It's not for IPC it's just to keep the code simpler with separate fds for reading and writing using the same process. Typically it'll read/write from a different file, or read/write from the same file but gets a cache hit when reading. Perhaps one of those functions is OK performance wise, it just doesn't feel right. Happy to drop this if you think there's nothing to be done.

Adding another way to flush just `delayed_write` doesn't feel right either, and it was never meant to be used this way.

I don't think we'll do anything in the current API, but I've been toying with the idea of a new file API every now and then. I'll take this usage into account in the new design.

**Comment by lhoguin** [comment]
Agree. Closing this for the time being. Thanks!
