### ISSUE TITLE
Wrong Efficiency Guide Maps URL

### ISSUE THREAD

**Issue by robsonpeixoto** [erlang/otp#5228]
The https://erlang.org/doc/efficiency_guide/users_guide.html Maps documentation is pointing to https://erlang.org/doc/man/maps.html but should be to https://erlang.org/doc/efficiency_guide/maps.html

**Comment by KennethL** [comment]
I also suspect that the flattening of the latest documentation goes wrong because there is a file for the new chapter in the efficiency guide that is named maps.xml and which result in a maps.html file. This maps.html is the same file name as is also used for the reference manual for the maps module and it seems like the link point to the wrong maps.html

**Comment by hissssst** [comment]
I experience this issue too

**Comment by garazdawi** [comment]
Fixed on https://erlang.org/doc as well. Lets hope I did not break anything else...
