### ISSUE TITLE
crypto api silently truncates data if AES blocksize is wrong

### ISSUE THREAD

**Issue by vans163** [erlang/otp#5388]
**Describe the bug**
A incorrect blocksize for AES will truncate the data.

**To Reproduce**
```erlang
Key = <<0:256>>,
Chunk = <<0>>,
<<>> = crypto:crypto_one_time(aes_256_ecb, Key, Chunk, false).
```
```elixir
key = <<0::256>>
chunk = <<0>>
<<>> = :crypto.crypto_one_time(:aes_256_ecb, key, chunk, false)
```

**Expected behavior**
An error should be thrown saying the blocksize is incorrect.

**Affected versions**
The OTP 23+

**Additional context**
I really think data should not be truncated/lost as its hard to spot and other parts of the `crypto` API indeed ensure correct block and key sizes.

**Comment by HansN** [comment]
We have discussed this in the team and changing the default behavior in the 24.x releases should be avoided.

If, and in that case when it would change is not decided.

Meanwhile, the expected behavior you request is already available as the option `{padding,none}`:
```
crypto:crypto_one_time(aes_256_ecb, Key, Chunk, [{encrypt,false}, {padding,none}]).
```
An unfilled last block will then return an error when `crypto:crypto_final/1` is called.
