### ISSUE TITLE
Running tests instructions fail

### ISSUE THREAD

**Issue by marcandre** [erlang/otp#5392]
**Describe the bug**
I tried to run the tests from a fresh copy of the repository.

Note: I am entirely new to Erlang, but an otherwise experienced developper.

**To Reproduce**
clone the erlang/otp repository && cd into it
follow the [running tests wiki instructions](https://github.com/erlang/otp/wiki/Running-tests)

**Expected behavior**
I expected the tests to run

Instead, after [some extensive output](https://gist.github.com/marcandre/4ecdb73c59effc9997dccb6e72df1d6a) and 82 warnings, I get an error (because there is no `$ERL_TOP/tests_install`)

I then tried the last line of the [howto on testing](https://github.com/erlang/otp/blob/master/HOWTO/TESTING.md):
```
erl -s ts install -s ts run all_tests -s init stop
```

I was rewarded with more [extensive output](https://gist.github.com/marcandre/de748dcc00a509faacbc3d18efdcedcd), 326 additional warnings, 73 inscrutable error reports.
After a long while of inactivity, I couldn't really tell if it was a success or not as there is no progress indicator, I got extra output (with more errors and warnings), indicating that some tests were still running.

I was not sure what to expect, but I am sure I was not expecting that.

**Comment by marcandre** [comment]
After a half hour, I'm at over 293k lines of output, I tried creating a gist but github is choking on it...
![image](https://user-images.githubusercontent.com/33770/141929540-34e5a6a1-7a60-4501-b704-4d7f339361b6.png)

Is this... normal?

**Comment by garazdawi** [comment]
> **Describe the bug** I tried to run the tests from a fresh copy of the repository.
> 
> Note: I am entirely new to Erlang, but an otherwise experienced developer.

Hello! Welcome to Erlang!

> 
> **To Reproduce**
> clone the erlang/otp repository && cd into it
> follow the [running tests wiki instructions](https://github.com/erlang/otp/wiki/Running-tests)
> 
> **Expected behavior** I expected the tests to run
> 
> Instead, after [some extensive output](https://gist.github.com/marcandre/4ecdb73c59effc9997dccb6e72df1d6a) and 82 warnings, I get an error (because there is no `$ERL_TOP/tests_install`)

In the test instructions you linked it says that you should call `make install`, yet I do not see that in the log you attached?

> 
> I then tried the last line of the [howto on testing](https://github.com/erlang/otp/blob/master/HOWTO/TESTING.md):
> 
> ```
> erl -s ts install -s ts run all_tests -s init stop
> ```
> 
> I was not sure what to expect, but I am sure I was not expecting that.

Running the tests of Erlang/OTP might not be the best way to start to get to know Erlang (how often have you run the JVM or GCC test suites?). The output from it may be a little bit daunting at first, mostly (I think) because the way to interact with the test results is not in the console as you may be used to, but instead in the HTML log pages created. If you look in the current working directory of where you started the tests (that is `/Users/work/otp/release/tests/test_server/`) there will be a file called index.html. If you open that file in a browser you will be able to follow the results of your test run.

> After a half hour, I'm at over 293k lines of output, I tried creating a gist but github is choking on it...
> Is this... normal?

Running all tests take roughly 7-8 hours, so yes this is normal. When developing we usually only run a subset of all tests. Personally, I use the method of running tests mentioned [here](https://github.com/erlang/otp/blob/master/HOWTO/TESTING.md#convenience-for-running-tests-without-the-release-and-configuration-steps). That is, after building Erlang/OTP, I just do `make test`, or `cd lib/stdlib && make test` if I just want to run the stdlib tests.

Hope this has not scared you away from learning Erlang!

**Comment by marcandre** [comment]
Thanks for your reply

> In the test instructions you linked it says that you should call `make install`, yet I do not see that in the log you attached?

Oh, you're right, I forgot it in the log I pasted.

I had previously tried on another machine (with same result) and I hadn't forgotten it [that time though](https://gist.github.com/marcandre/1c69de43e3f38ea96e77ae0bcb170209), but I had used `./otp_build setup -a` without the `--prefix` (as in the HOW TO, but not the other page).

> Running the tests of Erlang/OTP might not be the best way to start to get to know Erlang (how often have you run the JVM or GCC test suites?).

Never (I never contributed to the JVM or `gcc`), only those of Ruby and Elixir.

> The output from it may be a little bit daunting at first, mostly (I think) because the way to interact with the test results is not in the console as you may be used to, but instead in the HTML log pages created. If you look in the current working directory of where you started the tests (that is `/Users/work/otp/release/tests/test_server/`) there will be a file called index.html. If you open that file in a browser you will be able to follow the results of your test run.

Got it. Results in the console should be ignored entirely then?

> > After a half hour, I'm at over 293k lines of output, I tried creating a gist but github is choking on it...
> > Is this... normal?
> 
> Running all tests take roughly 7-8 hours, so yes this is normal. When developing we usually only run a subset of all tests. Personally, I use the method of running tests mentioned [here](https://github.com/erlang/otp/blob/master/HOWTO/TESTING.md#convenience-for-running-tests-without-the-release-and-configuration-steps). That is, after building Erlang/OTP, I just do `make test`, or `cd lib/stdlib && make test` if I just want to run the stdlib tests.

Thanks, that helps. Maybe the "how to" and test instructions should start with a pointer to that...

I'll close this, but my summary is:
1) having two different pages on how to run tests, with almost but not quite identical setup instructions is not ideal
2) having a setup for test that spans multiple commands is not ideal
3) a page where the "summary" instructions are not useful in practice is also not ideal 😅

Thanks for the help
