### ISSUE TITLE
user_drv adds unecessary additional new line to output

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#5403]
**Describe the bug**

Take the following code snippet that prints a line full of `-------` based on the terminal columns:

```
$ erl -noinput -eval '{_,C} = io:columns(), Line = lists:duplicate(C, "-"), io:format("~s~n~s~n~s~n", lists:duplicate(3, Line))' -s erlang halt
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------------------
```

The output is correct with the `-noinput` flag. If you take it out, then you get:

```
$ erl -eval '{_,C} = io:columns(), Line = lists:duplicate(C, "-"), io:format("~s~n~s~n~s~n", lists:duplicate(3, Line))' -s erlang halt
Erlang/OTP 24 [erts-12.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------

----------------------------------------------------------------------------------------------------

```

I believe somewhere in the tty driver we are computing the size incorrectly but my C-fu is not strong enough to find out where.

**Expected behavior**

I would expect the outputs above to match. The output is also correct if `TERM=dumb` is set.

**Affected versions**

I can reproduce the behaviour from OTP 21.3 to OTP 24.1. This bug has been reproduced on Linux and Mac.

**Comment by garazdawi** [comment]
The problem seems to be the `xn` effect as described here: https://www.gnu.org/software/termutils/manual/termcap-1.3/html_node/termcap_27.html

When the ttysl driver notices that the terminal has the `xn` quirk, it emits `" \b"` in order to trigger the wrap. This way to trigger the wrap is not recommended by the manual, but seems to work for most scenarios except when the next characters to be output are `"\r\n"`.

Maybe it would be possible to make the driver not emit `" \b"` when the characters triggering the wrap is `"\r"`...

I will poke about an experiment a bit.
