### ISSUE TITLE
otp24 asmjit time-consuming recursion is greater than otp22

### ISSUE THREAD

**Issue by leonlee2007** [erlang/otp#5437]
**Describe the bug**
This is not a bug but otp24 asmjit time-consuming recursion is greater than otp22. it's very incredible！

**To Reproduce**
Call `test_calc/0, test_calc_tail/0` with otp22 and otp24 asmjit to get the following results: 

**`test_calc/0` test data: (output maximum, minimum and average time consumption)**

| function_name | otp_version | compile_version | argument  | min(us) | max(us) | avg(us) |
| ------------- | ----------- | --------------- | --------- | ------- | ------- | ------- |
| calc          | 22          | 7.4.5           | 1,000     | 17      | 122     | 20      |
| calc          | 22          | 7.4.5           | 10,000    | 184     | 887     | 291     |
| calc          | 22          | 7.4.5           | 50,000    | 2,311   | 5,281   | 3,649   |
| calc          | 22          | 7.4.5           | 500,000   | 18,893  | 105,137 | 23,008  |
| calc          | 22          | 7.4.5           | 1,000,000 | 42,922  | 64,701  | 47,986  |
| calc          | 22          | 7.4.5           | 2,000,000 | 86,144  | 134,785 | 95,996  |

| function_name | otp_version | compile_version | argument  | min(us) | max(us) | avg(us) |
| ------------- | ----------- | --------------- | --------- | ------- | ------- | ------- |
| calc          | 24          | 8.0.3           | 1,000     | 17      | 205     | 23      |
| calc          | 24          | 8.0.3           | 10,000    | 196     | 741     | 305     |
| calc          | 24          | 8.0.3           | 50,000    | 2,982   | 4,996   | 3,795   |
| calc          | 24          | 8.0.3           | 500,000   | 118,755 | 170,838 | 132,329 |
| calc          | 24          | 8.0.3           | 1,000,000 | 224,605 | 315,486 | 243,924 |
| calc          | 24          | 8.0.3           | 2,000,000 | 488,299 | 660,719 | 548,853 |

**`test_calc_tail/0` test data: (output maximum, minimum and average time consumption)** 

| function_name | otp_version | compile_version | argument   | min(us) | max(us) | avg(us) |
| ------------- | ----------- | --------------- | ---------- | ------- | ------- | ------- |
| calc_tail     | 22          | 7.4.5           | 1,000      | 10      | 2,114   | 17      |
| calc_tail     | 22          | 7.4.5           | 10,000     | 103     | 674     | 132     |
| calc_tail     | 22          | 7.4.5           | 100,000    | 1,060   | 1,830   | 1,291   |
| calc_tail     | 22          | 7.4.5           | 1,000,000  | 11,624  | 14,579  | 12,954  |
| calc_tail     | 22          | 7.4.5           | 5,000,000  | 59,380  | 71,062  | 65,031  |
| calc_tail     | 22          | 7.4.5           | 10,000,000 | 120,332 | 222,766 | 131,017 |

| function_name | otp_version | compile_version | argument   | min(us) | max(us) | avg(us) |
| ------------- | ----------- | --------------- | ---------- | ------- | ------- | ------- |
| calc_tail     | 24          | 8.0.3           | 1,000      | 7       | 194     | 9       |
| calc_tail     | 24          | 8.0.3           | 10,000     | 72      | 337     | 90      |
| calc_tail     | 24          | 8.0.3           | 100,000    | 767     | 1,313   | 909     |
| calc_tail     | 24          | 8.0.3           | 1,000,000  | 8,498   | 10,400  | 9,273   |
| calc_tail     | 24          | 8.0.3           | 5,000,000  | 44,645  | 62,807  | 49,239  |
| calc_tail     | 24          | 8.0.3           | 10,000,000 | 89,449  | 111,167 | 98,347  |

**Expected behavior**
According to the above test data, `test_calc_tail/0` otp24 is better than otp22, which is in line with expectations， **but when the recursion scale of `test_calc/0` is large, the performance of opt24 is far worse than otp22.** I don't know what caused it?

**Affected versions**
otp22.1 vs otp24.1.4 asmjit

**Additional context**
* test environment:
```
 VMware virtual machine
 Centos7.5
 4 core 16G memory
```
* Test code:
```erlang
calc(N) -> calc(N, 0).
calc(0, Ret) -> Ret;
calc(N, Acc) when N > 0 -> N + calc(N-1, Acc * 0.5).

calc_tail(N) -> calc_tail(N, 0).
calc_tail(0, Ret) -> Ret;
calc_tail(N, Acc) when N > 0 -> calc_tail(N-1, N + Acc * 0.5).

test_num(TestNum, M, F, N) ->
  List = lists:seq(1, TestNum),
  TimeL = [begin {Time, _} = timer:tc(M, F, [N]), Time end || _ <- List],
  TimeL1 = lists:sort(TimeL),
  Min = hd(TimeL1),
  Max = lists:last(TimeL1),
  Avg = trunc(lists:sum(TimeL) / TestNum),
  {Min, Max, Avg}.
 
test(Func, List) ->
  TestNum = 1000,
  OTPVer = erlang:system_info(otp_release),
  [{version, CompileVer} | _] = otp:module_info(compile),
  CsvFile = lists:flatten(io_lib:format("~p_~s_~s.csv", [Func, OTPVer, CompileVer])),
  {ok, FD} = file:open(CsvFile, [write]),
   io:format(FD, "~p,~p,~p,~p,~p(us),~p(us),~p(us)~n", [function_name, otp_version, compile_version, argument, min, max, avg]),
  RetList =
  [begin
     {Min, Max, Avg} = test_num(TestNum, otp, Func, N),
     io:format(FD, "~p,~s,~s,~p,~p,~p,~p~n", [Func, OTPVer, CompileVer, N, Min, Max, Avg]),
     Avg
   end || N <-List],
  file:close(FD),
  RetList.
  
test_calc() -> test(calc, [1000, 10000, 50000, 500000, 1000000, 2000000]).
test_calc_tail() -> test(calc_tail, [1000, 10000, 100000, 1000000, 5000000, 10000000]).
```

**Comment by bjorng** [comment]
When benchmarking, one should always run each measurement in a freshly spawned process to avoid the distortions of garbage collections happening at random times with random size of the heap with random amount of live data on the heap.
I rewrote your benchmark like this:

```
spawn_test(M, F, As) ->
    {Pid,Ref} = spawn_monitor(fun() ->
                                      exit(timer:tc(M, F, As))
                              end),
    receive
        {'DOWN',Ref,process,Pid,Res} ->
            Res
    end.

test_num(TestNum, M, F, N) ->
    List = lists:seq(1, TestNum),
    TimeL = [begin {Time, _} = spawn_test(M, F, [N]), Time end || _ <- List],
    TimeL1 = lists:sort(TimeL),
    Min = hd(TimeL1),
    Max = lists:last(TimeL1),
    Avg = trunc(lists:sum(TimeL) / TestNum),
    {Min, Max, Avg}.
```

I also lowered the number of iterations for each from 1000 to 10.

**Comment by bjorng** [comment]
That said, I can confirm that the JIT in OTP 24 is indeed slower than the threaded interpreter in OTP 22 or OTP 24.

**Comment by bjorng** [comment]
It is not the recursion, but the floating point operations. If I eliminate the floating point operations like this:

```
calc(0, Ret) -> Ret;
calc(N, Acc) when N > 0 -> N + calc(N-1, Acc * 2).
```

the JIT in OTP 24 will make it faster than OTP 22.

I have relabeled this issue as enhancement instead of bug. I cannot promise anything, but we might be able to teach the JIT in OTP 25 to generate somewhat better code for `calc/2`.

**Comment by leonlee2007** [comment]
Thank you very much for your reply!
Can I understand it this way? When the number of floating point **iteration operations** is greater than 50,000, the JIT in OTP 24 is slower than the thread interpreter in OTP 22 or OTP 24, and this problem may be improved in OTP 25.

**Comment by leonlee2007** [comment]
```erlang
calc(N) -> calc(N, 0).
calc(0, Ret) -> Ret;
calc(N, Acc) when N > 0 -> N + calc(N-1, Acc * 0.5).

calc_tail(N) -> calc_tail(N, 0).
calc_tail(0, Ret) -> Ret;
calc_tail(N, Acc) when N > 0 -> calc_tail(N-1, N + Acc * 0.5).
```
Another question is very confusing. `calc_tail/1` also has floating point operations. Why does calc_tail/1 run faster on the JIT in otp24 than  on the thread interpreter in OTP 22?

I am very eager to get your reply, and sincerely wish Erlang/OTP get better and better and stronger!

**Comment by bjorng** [comment]
Yes, we **hope** to improve the performance in OTP 25. It depends on us having enough time to work on it, and us finding a good solution.

> Why does calc_tail/1 run faster on the JIT in otp24 than on the thread interpreter in OTP 22?

The JIT can generate nice optimized code for the calculation of the expression `N + Acc * 0.5` in `calc_tail/2`. The JIT can't do much to optimize the `calc/2` function.

**Comment by leonlee2007** [comment]
Thank you very much, this completely solved my confusion.
Looking forward to finding a good solution in OTP 25.

**Comment by zuiderkwast** [comment]
Are we interested in immediate floats? If we can use 60 bits, we can represent an exponent of 7 bits instead of 11. It requires some bit-fiddling but we can avoid an allocation. This allows us to represent floats in the range -2^62..2^63. If we have 59 bits, we have a 6-bit exponent or the range -2^30..2^31. It's would still cover most values in many applications.

We could split the split the 60-bit integer space in two: 59 bits for integers and 59 for floats.

Another way to get some bits would be in pointers. In x86-64 and Aarch64, only 48 bits in a 64 bit pointer are used, so we could tag stuff in the upper 16 bits. This doesn't work on mainframes Z architecture though (but IIRC there are at least a few unused bits here too.)

**Comment by jhogberg** [comment]
> Are we interested in immediate floats?

@sverker made a proof of concept a few years back, but it turned out to be more difficult than it sounds. If I recall correctly there's more issues than just accuracy.

> Another way to get some bits would be in pointers. In x86-64 and Aarch64, only 48 bits in a 64 bit pointer are used, so we could tag stuff in the upper 16 bits

Only 48 bits are available but all are significant: you'll get an exception when the "dead" bits aren't equal to bit 47. This is to stop people from using this trick since it'll break as soon as the 48-bit limit is relaxed.

AArch64 has its "top byte ignore" feature that could in theory be used for something like this (especially since AArch64 lets you test the upper 12 bits with ease), but the OS is in control of that and it clashes with the memory tagging extensions.

**Comment by zuiderkwast** [comment]
> If I recall correctly there's more issues than just accuracy.

If we don't touch the mantissa, the accuracy isn't impacted. Only the range.

> you'll get an exception when the "dead" bits aren't equal to bit 47

We could leave them untouched (all zero) for pointers, but start with e.g. "10" for floats. That gives us the remaining 62 bits to use for floats.

If we don't want use the upper bits, we can use the same trick as for other types (e.g. integers) as mentioned.

**Comment by jhogberg** [comment]
> If we don't touch the mantissa, the accuracy isn't impacted. Only the range.

Yes, there were more issues than accuracy and range if I recall. I can't remember the details though.

> We could leave them untouched (all zero) for pointers, but start with e.g. "10" for floats. That gives us the remaining 62 bits to use for floats.

Checking upper bits is very expensive on x64, and we'd no longer be able to tell a type from checking the lower bits alone (as they can now overlap with a float), making all other tests more expensive.

I'm not against the idea, mind you, it just seems rather tricky to make it work well. :)

**Comment by josevalim** [comment]
I remember reading about this for the OpenSmalltalkVM some time ago and I was able to dig the article back: https://clementbera.wordpress.com/2018/11/09/64-bits-immediate-floats/

Not sure if useful, but sharing anyway. :)

**Comment by jhogberg** [comment]
> I remember reading about this for the OpenSmalltalkVM some time ago and I was able to dig the article back: https://clementbera.wordpress.com/2018/11/09/64-bits-immediate-floats/

A staged approach like that might work nicely, the only downsides I can think of is complexity and making mixed arithmetic slightly more expensive, but we can probably live with that if the benefits are good enough.

**Comment by zuiderkwast** [comment]
Thanks @josevalim, it explains the idea very well. I've seen a very similar version somewhere else.

**Comment by garazdawi** [comment]
One problem with using floats as immediates is that we in many many places just do a normal bit wise comparison of the values, while for floats (at least the way they work today) positive and negative zero should compare as equal. So all immediate comparisons would have to be first checked if they are floats, or we would have to change how negative and positive zero compares.

**Comment by sverker** [comment]
> One problem with using floats as immediates is that we in many many places just do a normal bit wise comparison of the values, while for floats (at least the way they work today) positive and negative zero should compare as equal. So all immediate comparisons would have to be first checked if they are floats, or we would have to change how negative and positive zero compares.

Yes, this is where @psyeugenic and I gave up the prototyping of immediate floats. When we realized that we had to make every term comparison of immediates more expensive to maintain `0 =:= -0`.

**Comment by josevalim** [comment]
I may be out of depth here, but could you make it so the immediate mask for equality is one bit deeper? For example, let's say all immediates start with the bit zero. For equality, you look for the first _two_ bits being zero. In this case, you would need to do an additional check only for negative floats and very large integers? Although I guess the definition of very large integers is not so high for 32-bit systems?

**Comment by zuiderkwast** [comment]
@sverker Isn't it possibly a bug that `0 =:= -0`? Could we drop that (while maintaining `0 == -0`) without the world falling apart? I have noticed that a -0.0 literal doesn't actually result in a negative float bit pattern, but I doubt anyone relies on that either.

@josevalim The immediates are encoded like this: https://github.com/erlang/otp/blob/master/erts/emulator/beam/erl_term.h#L70 (I was thinking about of fitting 58-bit floats as IMMED2 between CATCH and NIL.) Pids and ports use the same number of bits as small integers (IMMED1). Atoms use even less bits (IMMED2). I think your idea might require some changes but it would be nice to find some bit pattern that works.

**Comment by josevalim** [comment]
I have been thinking a bit more about this. The current upper tag design is:

    00 HEADER
    01 LIST
    10 BOXED
    11 IMMED

Here is a potential proposal:

    000 HEADER
    001 BOXED
    01 LIST
    10 IMMED_FLOAT
    11 IMMED

In this approach:

1. Immediate tags only need to check the first bit

2. However, when doing comparisons, we check the first 2 bits to be `0b11` to rule out floats (same perf as today)

3. Comparison between immediate floats can be still be fast considering `0.0 == -0.0` according to [the outlines defined here](https://clementbera.wordpress.com/2018/11/09/64-bits-immediate-floats/)

My main questions is: would using three bits for BOXED/HEADER make things slower or limit the current capabilities? I know this approach reduces the header arity but I think that it should be fine? Currently it has 26 bits but the max arity is enforced to be 24 bits. So we can waste 1 bit.

Possible complexities going down this road:

1. We would need to revisit all places where comparison with immediate may be possibly done. There are approximately 200 calls to `is_immed`/`is_not_immed`/`IS_CONST` that would need to be checked (doable but annoying).

2. We still need both immediate and boxed floats and we will need to implement mixed arithmetic for them (and also between immediate floats and integers+bignums)

**Comment by zuiderkwast** [comment]
@josevalim I'll review if you implement it. :-)

**Comment by garazdawi** [comment]
> My main questions is: would using three bits for BOXED/HEADER make things slower or limit the current capabilities?

You cannot use three bits for boxed in 32-bit systems for one, also Windows already uses the third bit so it would not work there, and also I plan to make use of the third bit for the GC so you may not have it! :)

**Comment by josevalim** [comment]
Thanks @garazdawi!

> You cannot use three bits for boxed in 32-bit systems

Sorry, I should have clarified. The schema would be specific to 64-bits systems, since I don't think we can have f64 as immediate on 32-bits systems? Given we are talking about 64-bits, I am hoping we have a lot more bits to use. It does add one additional concern though: we will have a different tagging system for 32-bits vs 64-bits.

Does it change your reply? For example, could you use the third bit for GC on 32-bit systems and the fourth bit on 64-bit ones? Or my proposal is not suitable even for 64-bits systems?

**Comment by garazdawi** [comment]
> Given we are talking about 64-bits, I am hoping we have a lot more bits to use.

Unfortunately, that is not true as we tag pointers that point to word-aligned terms, so we only have 3 bits to work with on 64-bit systems (and 2 bits on 32-bit systems). If we want to use more bits than 3, we need to do something creative like

* shift all boxed and list pointers
* use the most significant bits for the tag instead of the least significant as we do today
* make all terms double word-aligned
* collapse BOXED and LIST pointer tags

Or something I haven't thought of yet.

> Does it change your reply?

Not really. We still have 64-bit Windows to deal with and if we are to use the 3rd bit for something there are (IMO) better candidates such as compressed lists or the GC. IMO changing the primary tag system in order to optimize double storage is not worth the extra complexity.

**Comment by michalmuskala** [comment]
Another creative option is what ZGC in Java uses is to mmap the same memory multiple times in address space, allowing you to tag the pointer (and still refer to the same value in memory) - some more details https://www.baeldung.com/jvm-zgc-garbage-collector#multi-mapping

**Comment by josevalim** [comment]
@garazdawi if we can't change the primary tag, then the second option is to change the immediate tag from this:

    00 PID
    01 PORT
    1000 ATOM
    1001 CATCH
    1011 NIL
    11 SMALLINT

To this:

    0 FLOATS
    1000 ATOM
    1010 PID
    1011 PORT
    10010 CATCH
    10011 NIL
    11 SMALLINT

Small ints have the same precision. PIDs and PORTs lose two bits but that should be fine. Atoms stay the same and we add one bit to CATCH/NIL (not relevant). The immediate tag is still `11` and we look at `111` for comparisons. Is this path worth exploring or are there also pitfalls?

**Comment by rickard-green** [comment]
@josevalim 
> PIDs and PORTs lose two bits but that should be fine on 64 bits systems.

I'm really not fond of this. At least not for PIDs. We are currently preparing to utilize as many bits as possible for PIDs to make them as "unique as possible", so it would not be fun to lose 2 bits for PIDs to floats.

**Comment by rickard-green** [comment]
Perhaps 58 bits for PIDs would be enough, though...

**Comment by zuiderkwast** [comment]
While sketching on the same stuff, I see the same idea being posted. :-) My idea is very similar and involves steeling one bit from pids and ports and using a 3 bits bitmask of 111 for direct comparing immediates.

    xxx0 11 immed float
    0001 11 pid (was xx0011)
    0101 11 port (was xx0111)
    1001 11 atom (was 001011)    |
    1101 11 catch (was 011011)   | was immed2
            nil (was 111011)     |
    xx11 11 small

(Nil is a singleton value, so we can use an invalid value of some other tag, for
example a catch tag with a zero payload (assuming this is an invalid catch and
that we can accept making `is_catch` one instruction heavier).)

**Comment by garazdawi** [comment]
> Is this path worth exploring or are there also pitfalls?

None that I can think of right now besides these that have already been mentioned:
* we will have a different tagging system for 32-bits vs 64-bits. (because we don't want to steal a bit from pids there)
* We would need to revisit all places where comparison with immediate may be possibly done. (JIT, places using macros, places not using macro)

**Comment by josevalim** [comment]
@zuiderkwast we should probably give up on the idea of calling them "immediate floats". Immediate strongly relies on term equality `X == Y` and we can't achieve that cheaply with floats since `0.0` and `-0.0` have different representations but are still equal.

The next question then is if it is worth exploring "unboxed floats". Unboxed floats could take a bit off immediate. But perhaps we could have an unboxed tag at the top level for both floats and lists. Before:

    00 HEADER
    01 LIST
    10 BOXED
    11 IMMED

After:

    00 HEADER
    01 UNBOXED
    10 BOXED
    11 IMMED

Where unboxed would hold unboxed lists (010) and floats (011) on 64 bits. I think taking one bit off lists is not problematic on 64 bits (citation needed), so this should be less impactful than the other designs but then I am not sure if it is worth it, as this is getting quite above my pay-grade. :)

**Comment by zuiderkwast** [comment]
@josevalim

> we should probably give up on the idea of calling them "immediate floats"

Sure, unboxed floats. I already agree we don't want to include them in the bitwise direct comparison.

> I think taking one bit off lists is not problematic on 64 bits (citation needed)

A list is a pointer, so I don't think we're allowed to take that bit, IIUC @garazdawi's GC plans.

@garazdawi 

> we will have a different tagging system for 32-bits vs 64-bits.

Agreed, this complexity penalty we'd have to accept.

> We would need to revisit all places where comparison with immediate may be possibly done. (JIT, places using macros, places not using macro)

Right. Do you think there's any code that's not using `is_immed` or `IS_CONST`? Because these unboxed floats will not be immediates (as José noted).

**Comment by garazdawi** [comment]
> Do you think there's any code that's not using is_immed or IS_CONST?

Definitely.
