### ISSUE TITLE
performance anomaly with process_info(self(), message_queue_len) in OTP-24

### ISSUE THREAD

**Issue by mikpe** [erlang/otp#5481]
**Describe the bug**
A consumer process receives a long stream of messages at a high rate. If the consumer calls `process_info(self(), message_queue_len)` for each incoming message (as part of alerting logic), and the stream is long enough, processing time suddenly increases exponentially. This is a regression in OTP-24 as compared to OTP-22.

**To Reproduce**
Compile the attached Erlang module `pimql.erl` with OTP-24.1.7, then run it:
```
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.1.5  (abort with ^G)
1> pimql:test(6).
10^3: with pimql 563 ms, without pimql 280 ms
10^4: with pimql 4566 ms, without pimql 2777 ms
10^5: with pimql 92530 ms, without pimql 26796 ms
10^6: with pimql 146704841 ms, without pimql 225307 ms
ok
2> pimql:test(6).
10^3: with pimql 654 ms, without pimql 308 ms
10^4: with pimql 4732 ms, without pimql 2742 ms
10^5: with pimql 46424 ms, without pimql 21439 ms
10^6: with pimql 135084954 ms, without pimql 234991 ms
ok
```

**Expected behavior**
With OTP-22.3.4.23 I see processing times consistently linear on the length of the message sequences:
```
6> pimql:test(7).
10^3: with pimql 531 ms, without pimql 279 ms
10^4: with pimql 4646 ms, without pimql 2688 ms
10^5: with pimql 45505 ms, without pimql 26100 ms
10^6: with pimql 232168 ms, without pimql 244311 ms
10^7: with pimql 1945813 ms, without pimql 1449139 ms
ok
```

**Affected versions**
At least OTP-24.1.7.

**Additional context**
Abstracted from part of a distributed transaction replication layer. The above measurements were done on a 4C/8T Ivy Bridge i7.

**Comment by mikpe** [comment]
[pimql.erl.txt](https://github.com/erlang/otp/files/7652171/pimql.erl.txt)
The test case. github complained it doesn't support `.erl` files, so I appended a `.txt` suffix -- just rename it back to `pimql.erl`.

**Comment by rickard-green** [comment]
I cannot come to think of any changes regarding this on the top of my head. Most often when it comes to issues like this it is due to garbage collection. We have not done anything major regarding garbage collection either, but not much is needed to trigger garbage collection at a different point than before.

I haven't looked more closely at this than checking if you have set the [`message_queue_data`](https://www.erlang.org/doc/man/erlang.html#process_flag_message_queue_data) flag to `off_heap` or not. I could not find any such setting. In `on_heap` mode (which is the default), the whole message queue is part of the rootset which can make a huge difference with a large message queue. Please try `off_heap` and see what results that gives. My guess is that this goes away with the `off_heap` setting since messages in the message queue won't be part of the garbage collection at all.

If a process have the potential to build up a large message queue, you typically always want to use the `off_heap` message queue data setting for this reason. You also typically want to set this when spawning the process and not when it got a huge message queue. If it got messages in the message queue, all message in the message queue have to be converted to off heap messages.

**Comment by mikpe** [comment]
I modified the test case to run the consumer process in three different configurations: with the `process_info(self(), message_queue_len)` call and either `on_heap` or `off_heap` for `message_queue_data`, and without that call and `on_heap` (default).
With OTP-24:
```
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Eshell V12.1.5  (abort with ^G)
1> pimql:test(6).
10^3: with pimql on-heap 561 ms, with pimql off-heap 393, without pimql 271 ms
10^4: with pimql on-heap 4727 ms, with pimql off-heap 3823, without pimql 2752 ms
10^5: with pimql on-heap 91321 ms, with pimql off-heap 19132, without pimql 12555 ms
10^6: with pimql on-heap 165443884 ms, with pimql off-heap 257161, without pimql 210955 ms
ok
```
With OTP-22:
```
Erlang/OTP 22 [erts-10.7.2.15] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V10.7.2.15  (abort with ^G)
1> pimql:test(7).
10^3: with pimql on-heap 570 ms, with pimql off-heap 402, without pimql 267 ms
10^4: with pimql on-heap 4731 ms, with pimql off-heap 3870, without pimql 2645 ms
10^5: with pimql on-heap 43505 ms, with pimql off-heap 24965, without pimql 24060 ms
10^6: with pimql on-heap 45275136 ms, with pimql off-heap 200025, without pimql 240264 ms
10^7: with pimql on-heap 2041630 ms, with pimql off-heap 1623803, without pimql 1264102 ms
ok
```
The observations are that:
1. `off_heap` solves the performance issue, and
2. even OTP-22 can see a massive performance issue with `on_heap`, something my initial tests didn't observe

So there is apparently no regression compared to OTP-22, and the solution with an expected long message queue is to select `off_heap`.

Thanks for your input @rickard-green, closing the issue.
