### ISSUE TITLE
[wx] wxWebViewBackendEdge missing

### ISSUE THREAD

**Issue by leoliu** [erlang/otp#5482]
**Describe the bug**
wxWebViewBackendEdge that is available since wxWidgets 3.1.4 on windows is not available to Erlang's wx.

**To Reproduce**
```
> wxWebView:isBackendAvailable("wxWebViewEdge").
false
```
**Expected behavior**
```
> wxWebView:isBackendAvailable("wxWebViewEdge").
true
```

**Affected versions**
all versions.

**Additional context**
The legacy backend on windows `wxWebViewBackendIE` while being the default is a pain to work with for modern web apps, and is ten thousand miles behind all other backends.

**Comment by dgud** [comment]
You will need to download and install the webView2 runtime package from microsoft:
See https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#details-about-the-webview2-runtime

Since this must also be installed on the target machine I though it was no idea to include it in the erlang installer.

**Comment by leoliu** [comment]
There is no need to include the webview2 runtime with Erlang.

I misunderstood. I was aware of needing to install the runtime. But I thought the operating system would alert just-in-time when it was needed.
