### ISSUE TITLE
Dialyzer behaves incorrectly with new erlang builtin types.

### ISSUE THREAD

**Issue by ilya-klyuchnikov** [erlang/otp#5635]
**Describe the bug**
Dialyzer doesn't seem to understand types from https://github.com/erlang/otp/commit/f3c239b73d2527f06c821293e068ae114dcd1a1a#diff-eaa01573391f162623a013292376aea0f7d1f6435cac34a7346e11b1b9d325ab

using `erlang:float()` and `erlang:number()` has a different effect than just using `float()` and `number()`. 

**To Reproduce**

```erlang
-module(t).

-export([foo1/1, foo2/1, foo3/1]).

-type f() :: float().
-type n() :: integer() | float().

-spec foo1(float()) -> number().
foo1(S) when is_float(S) -> S + S.

-spec foo2(erlang:float()) -> erlang:number().
foo2(S) when is_float(S) -> S + S.

-spec foo3(f()) -> n().
foo3(S) when is_float(S) -> S + S.
```

```
dialyzer -Wspecdiffs t.erl
  Proceeding with analysis...
t.erl:8:2: The specification for t:foo1/1 states that the function might also return 
          integer() but the inferred return is 
          float()
t.erl:14:2: The specification for t:foo3/1 states that the function might also return 
          integer() but the inferred return is 
          float()

```

Dialyzer reports a "spec diff" only for `foo1` and for `foo3`, but not for `foo2`.

**Expected behavior**
A spec diff for `foo2` should also be reported.

**Affected versions**
24.2

**Comment by TD5** [comment]
I wonder if this this because `erlang:number` isn't canonicalised into the built-in number type, but rather as a "normal" qualified type that happens to be from the `erlang` module?

The logic here doesn't seem to consider the `erlang`-qualified case:
https://github.com/erlang/otp/blob/master/lib/dialyzer/src/erl_types.erl#L1258 / https://github.com/erlang/otp/blob/master/lib/dialyzer/src/erl_types.erl#L389

but then perhaps it's resolved during earlier stages, e.g. when generating abstract forms?

**Comment by jhogberg** [comment]
The warning is generated correctly, but it gets filtered out on purpose because the types are remote.

I can think of a few reasons to do this, but I'd just be speculating as there's no comment explaining [this decision](https://github.com/erlang/otp/commit/804df7a55aa2ec49c2001f03aa5f0af1e5f7e18f). @aronisstav ?

**Comment by aronisstav** [comment]
I think the intention was so that "richer" remote types can still be used in places where more precise info would be tedious to write instead, such as e.g. a callback that is actually returning fewer values than what a full remote type provided from its behaviour allows.

E.g. any appropriate gen_statem function can be spec'd as returning a `gen_statem:state_function_result()` without Dialyzer being "well technically this only ever returns `{'next_state', 'state1', _}`.

I understand however that this is inconsistent with one explicitly asking for underspec (or specdiff) warnings...
