### ISSUE TITLE
different between inet:gethostname and inet_db:gethostname 

### ISSUE THREAD

**Issue by ddhq** [erlang/otp#5661]
# /etc/hosts

127.0.0.1 localhost myhostname
::1 localhost

in this way:
inet:gethostname(). = myhostname
inet_db:gethostname(). = localhost

after reading inet_db:set_hostname ，inet_db  hostname was set by inet_config (inet:get_hostname );
when i call it myself, it's myhostname ， not localhost

----------------

but if i change /etc/hosts into:

127.0.0.1 localhost
::1 localhost

it works fine：
inet:gethostname(). = myhostname
inet_db:gethostname(). = myhostname

it really confuse me , any help will be applicated, thanks.

**Comment by RaimoNiskanen** [comment]
A simple answer is: `inet_db` is not a documented API module; it is an internal helper module,
so it should not be called from user code and user code should not rely on its' return values.

That said; `inet:gethostname()` is (almost 100%) a wrapper of the OS command "hostname -s";
get me the short hostname.

The OS command `hostname` returns what was set during system startup, so it is not firmly
related to the content of `/etc/hosts`.  Some Linux distros insert the short hostname on
the 127.0.0.1 line in `/etc/hosts`, but that often gets confusing since you do not want
the loopback address when looking up the short hostname.  Some Linux distros create
a line 127.0.0.2 for the short hostname, some 127.0.1.1, just to differ from the loopback address.
Some do not insert it at all and relies on the resolver to find the short hostname.
Some insert the known external address, ..., it is ~~a mess~~ system dependent.


`inet_db:gethostname()` fetches a cached value from an internal ETS table, and that value is firstly
the same, but a refinement step is made; after picking up what can be picked up from the
OS configuration (files), the name known from `inet:gethostname()` is looked up (chiefly to see
if a fully qualified name can be obtained), and the lookup result (assumed to be the canonical name)
is what is stored in the ETS table.

In your case 1; it seems that the line in /etc/hosts is found when looking up the short hostname,
and there the canonical name is 'localhost', so that is what is stored by `inet_db`.

In your case 2; I guess that lookup of the short hostname fails, and therefore the name is not refined,
so the return value from "hostname -s" / `inet:gethostname()` is stored.

**Comment by ddhq** [comment]
@RaimoNiskanen thanks for answer，but where is the step you metion above?

but a refinement step is made; after picking up what can be picked up from the
OS configuration (files),

where does this happen?

**Comment by ddhq** [comment]
![820DA6C9-6D92-46ab-A1E4-968C4B1BB428](https://user-images.githubusercontent.com/20969300/153144058-bd827079-63ae-483e-b04e-0e71d7fdffda.png)

i get into this because inet:gethostbyname,  in my case 1 above,  gethostbyname will return  nxdomain, 
then i trace into inet:gethostbyname_self, and i notice inet_db:gethostname,

i was wondering whether this is ok?

**Comment by RaimoNiskanen** [comment]
> > but a refinement step is made; after picking up what can be picked up from the
> > OS configuration (files),
> 
> where does this happen?

It happens during system start in `inet_config:init/0`, the call to `set_hostname/1`,
which is done after calling `do_load_resolv/2` that configures host name resolving.

This may update the known hostname in `inet_db`:s ETS table.

**Comment by RaimoNiskanen** [comment]
`inet_db:gethostname()` is assumed to be the best hostname of ours we have found.
We want this name to be known to others so it will be useful as a short node name.
Therefore we look up our short host name via host name resolving to get a more canonical name, if there is one.

But incorrect network configurations may screw that up, and I know of no perfect method.

**Comment by ddhq** [comment]
> # /etc/hosts
> 127.0.0.1 localhost myhostname ::1 localhost
> 
> in this way: inet:gethostname(). = myhostname inet_db:gethostname(). = localhost
> 
> after reading inet_db:set_hostname ，inet_db hostname was set by inet_config (inet:get_hostname ); when i call it myself, it's myhostname ， not localhost
> 
> but if i change /etc/hosts into:
> 
> 127.0.0.1 localhost ::1 localhost
> 
> it works fine： inet:gethostname(). = myhostname inet_db:gethostname(). = myhostname
> 
> it really confuse me , any help will be applicated, thanks.

os
![image](https://user-images.githubusercontent.com/20969300/153322736-cbf41ddb-f0fd-4516-bd60-b1cb58a073c8.png)

**Comment by ddhq** [comment]
**erl version**

![image](https://user-images.githubusercontent.com/20969300/153324723-0002968c-808e-411a-84c7-b4b865958886.png)

**Comment by RaimoNiskanen** [comment]
I have already explained and cannot really understand where the explanation did not get through.
Here goes again...

`inet:gethostname()` returns the host's name as set by hostname(1).  In this case it seems to be 'myhostname'.

If the name is not qualified (a short name); in an attempt to find a more canonical name
`inet_config:init()` first configures host name resolving and then calls `inet:gethostbyname("myhostname")`.
If that function returns a name (and aliases), that name becomes the new value in `inet_db`.

When you have
```
127.0.0.1 localhost myhostname
```
in /etc/hosts, `inet:gethostbyname("myhostname")` will return "localhost" as the canonical host name
and "myhostname" as an alias.  Then "localhost" is assumed to be the better name and that is
what is set in `inet_db` to henceforth be returned from `inet_db:gethostname()`.

It is considered bad practice to have "myhostname", i.e what is set by hostname(1),
resolve to the loopback address 127.0.0.1.

When you do not have 'myhostname' in the entry for 127.0.0.1 in /etc/hosts; the call
`inet:gethostbyname("myhostname")` fails, so a better name than what `inet:gethostname()`
returned can not be found and that name is what is stored for `inet_db:gethostname()`.
