### ISSUE TITLE
Why is Dialyzer's `-Wunknown` off by default?

### ISSUE THREAD

**Issue by TD5** [erlang/otp#5695]
I've found myself explicitly switching on `-Wunknown` in various places, and being confused when I've forgotten to set it and therefore not had Dialyzer warn when I expected it to. I started to wonder why it's not on by default, because I find it quite useful. My best guess is that it's off by default to allow people to run Dialyzer over a subset of their codebase for performance reasons, and doing this would potentially then result in `unknown` warnings purely due to "missing" functions/modules being outside the set of things under analysis.

From the docs:
> **-Wunknown**
> Let warnings about unknown functions and types affect the exit status of the command-line version. The default is to ignore warnings about unknown functions and types when setting the exit status. When using Dialyzer from Erlang, warnings about unknown functions and types are returned; the default is not to return these warnings.

What's the official view on why `unknown` warnings aren't always returned, and does it still make sense for this to be the case?

**Comment by max-au** [comment]
Could it be done in order to support hot code upgrades (where a module/function may appear)?

**Comment by paulo-ferraz-oliveira** [comment]
@max-au, I believe so. I don't have an "official view" but that's what makes sense to me, too.

**Comment by bjorng** [comment]
> What's the official view on why `unknown` warnings aren't always returned, and does it still make sense for this to be the case?

I don't know reasoning behind the decision, but I think it's partly because you might want to run Dialyzer on part of a codebase for speed and also it fits with Dialyzer's philosophy to only warn for things that Dialyzer is sure is wrong.

We will not change the default in OTP 25. We will postpone to OTP 26 the decision on whether the current default makes sense or whether it should be changed.

**Comment by jesperes** [comment]
I think it would be a good idea to make `unknown` on by default. If does make it difficult to run dialyzer on a subset of your code, but disabling it hides a whole category of problems, such as misspelled types.

**Comment by TD5** [comment]
I perhaps should have been clearer in the original post: I really did intend this as a question of history and original intent to aid my own understanding, rather than a proposal to change things. That said, I am happy if the question sparks a debate and results in some sort of improvement for users of OTP.

The point made above about hot code reloading is an interesting one, and makes sense to me. My question very much came from my personal experience, where I have all my code and dependencies available at build and analysis time, and I run Dialyzer over everything on every change to stay on top of the warnings. I appreciate this isn't necessarily reflective of how some (or even most?) people use Erlang and OTP, so it makes sense that the option default to something that supports the majority of users.

**Comment by paulo-ferraz-oliveira** [comment]
> it makes sense that the option default to something that supports the majority of users.

Agreed. It would take a poll to get those results, though.

I've run into the same issue, but always keep the same `rebar3` config.s (via code reuse) so I don't think about it that much, these days. But "on by default" would be nice, for me 😄

**Comment by erszcz** [comment]
> My question very much came from my personal experience, where I have all my code and dependencies available at build and analysis time, and I run Dialyzer over everything on every change to stay on top of the warnings. I appreciate this isn't necessarily reflective of how some (or even most?) people use Erlang and OTP.

I'm wondering if it really is or isn't the case. I'm aware that loadable Linux modules are often built out of the source tree using just header files due to the sheer size of the kernel tree, but are modules of Erlang systems really built without access to an entire project codebase?

The argument that static type checking cannot work for Erlang because of hot code reloading resonates in the community, but I'm not really convinced by it. Even in the light of type discrepancies between versions of code (let's say a currently running version and a version to be loaded), we would still like the version in development (so the one to be loaded at some point in the future) to type check - I see no reason whatsoever why we wouldn't.

Then, if a hot-loaded module is not type-consistent with a version it's loaded into... we still have the supervision tree and in the worst case can "let it crash" during the transition from the old version to the new one.

**Comment by TD5** [comment]
Hypothetically, if `-Wunknown` was the default, then we'd want a way to turn it off for specific instances of the warning, as per https://github.com/erlang/otp/issues/5995
