### ISSUE TITLE
Inconsistency of variable binding between lists and maps

### ISSUE THREAD

**Issue by yushli** [erlang/otp#5796]
**Describe the bug**

test(Key, [{Key, Value} | T]) -> Value.
is valid.

but 

testMap(Key, #{Key := Value}) -> Value.

the compile will report error:
variable 'Key' is unbound

**Expected behavior**
The variable bound in the previous parameter can also be used in the following parameters.

**Comment by bjorng** [comment]
This is not a bug.

> The variable bound in the previous parameter can also be used in the following parameters.

That assumes that matching is done from left to right, but it is not (except inside binary patterns). All variables are bound at the same time.

We have done some attempts to extend pattern matching so that your example would be accepted, but we also wanted the following variation to be accepted:

```
testMap(#{Key := Value}, Key) -> Value.
```

While we did get that to work, a number of tricky cases turned up which we could not resolve at the time. For example:

```
repeated_vars(#{K := #{K := K}}, K) -> K.
```

For the moment, and for the foreseeable future, we have no plans to extend the pattern matching semantics in the way that you suggests.
