### ISSUE TITLE
Release fails to start when rebar3's include_erts=false is used, 25.0-rc2

### ISSUE THREAD

**Issue by shino** [erlang/otp#5826]
**Describe the bug**
When using rebar3 release configuration `include_erts=false`, resulting release does not start:

```
(default) % _build/dev/rel/devmode/bin/devmode console
Exec: /home/shino/local/otp/25.0-rc2/erts-13.0/bin/erlexec -boot /home/shino/g/devmode/_build/dev/rel/devmode/releases/0.0.0/start -mode interactive -boot_var SYSTEM_LIB_DIR /home/shino/local/otp/25.0-rc2/lib -config /home/shino/g/devmode/_build/dev/rel/devmode/releases/0.0.0/sys.config -args_file /home/shino/g/devmode/_build/dev/rel/devmode/releases/0.0.0/vm.args -- console
Root: /home/shino/g/devmode/_build/dev/rel/devmode
/home/shino/g/devmode/_build/dev/rel/devmode
Can not find inet_gethost for erts-13.0/x86_64-pc-linux-gnu

Crash dump is being written to: erl_crash.dump...done
```

I'm not sure whether Erlang/OTP does support this feature officially.
If not, please close this issue.

**To Reproduce**

```
% git clone https://github.com/shino/devmode.git
% cd devmode
% rebar3 as dev release
% _build/dev/rel/devmode/bin/devmode console
```

**Expected behavior**

No error and BEAM continues to run.

**Affected versions**
- OTP 25.0-rc2

**Additional context**

- At 25.0-rc1, it works
- By setting `include_erts` to true explicitly, it works nice. This can be confirmed by commenting in the line https://github.com/shino/devmode/blob/main/rebar.config#L11
- Does the commit https://github.com/erlang/otp/commit/a32f6d210a58ba1e56f54f07c91106efed2c0777 affect ?

**Comment by garazdawi** [comment]
Adding some notes about what I've found about this issue:

relx has an option called `include_erts` that can be set to false. When that is done, the [release will be created](https://github.com/erlware/relx/blob/16a7972f7679778d9d7f40228b1a20351f1077bd/src/rlx_tar.erl#L163-L172) without including the erts directory.

As far as I can tell, omitting `erts` from a release is not something that has ever been documented to work, but nothing has relied on this until https://github.com/erlang/otp/commit/a32f6d210a58ba1e56f54f07c91106efed2c0777 was added.

**Comment by KennethL** [comment]
Have you tried this (from the documentation  of rebar3)
[](https://rebar3.readme.io/docs/releases#without-erts)Without Erts

To use the ERTS and base applications like kernel and stdlib on the target, set include_erts and system_libs to false in the relx configuration tuple:

{include_erts, false},
{system_libs, false},
...

**Comment by shino** [comment]
Thanks for your comments!!

Tried this but no difference :cold_sweat: 

> {include_erts, false},
> {system_libs, false},

**Comment by RaimoNiskanen** [comment]
> * Does the commit https://github.com/erlang/otp/commit/a32f6d210a58ba1e56f54f07c91106efed2c0777 affect ?

I'd say that is a safe bet.

The commit changes how the Kernel service `inet_gethost_native` finds its helper program inet_gethost from executing any program named inet_gethost from the PATH, into trying two distinct locations and exiting the VM exactly as you described if the executable can not be found.  It tries `code:root_dir()/erts-erlang:system_info(version)/bin/inet_gethost` and `code:root_dir()/bin/erlang:system_info(system_architecture)/inet_gethost`.

When we made this change we made some assumptions about how an Erlang/OTP release should look, and this approach we think is reasonable.

Some of our test cases violated this assumption.  In one case the solution was that an installation in a test case needed to copy over the inet_gethost binary to the installation.  In another (the other) the test case release was created with incorrect system version in the erts- directory name.

The question is what exactly rebar does in this case, and if it goes against this assumption because it is necessary or by accident.

**Comment by shino** [comment]
What I understand so far is the assumption made by rebar3/relx is not valid by specification. Am I right?
Then I will try to fix it to comply with the spec (= erts-<VSN> directory must exists under `root_dir()`).

In case there is any room for OTP team to discuss about the specification, I leave this issue as open now.
Please do not hesitate to close it.

Thank you all for helpful comments and advises!

**Comment by shino** [comment]
P.S. (this comment is about rebar3/relx but not related to erlang/otp, sorry)

I found code in relx that sets up boot variables:
https://github.com/shino/relx/blob/master/src/rlx_assemble.erl#L857-L878
From the comment, on windows, $ROOT points erlang installed directory and lib/ directory is pointed by `$RELEASE_DIR`. If this case can be applied to non-Windows cases, it will work (I hope).

**Comment by RaimoNiskanen** [comment]
We need something that work on Windows too.
We have already rejected a solution that used $BINDIR because Windows does not use the environment variables like *nix does.

**Comment by RaimoNiskanen** [comment]
We (the OTP team) are open for a discussion with the Rebar team about how an Erlang installation should look, in this case where and how to locate helper programs...

**Comment by itssundeep** [comment]
Is it fair to say that we should make releases work on target erts, where ROOTDIR is set to the release and target erts is referred through `SYSTEM_LIB_DIR`.

**Comment by shino** [comment]
I opened a (incomplete) PR for relx https://github.com/erlware/relx/pull/909

**Comment by garazdawi** [comment]
Me and Raimo talked a bit yesterday about this and I think we came up with a solution that will solve the original problem we were trying to solve in https://github.com/erlang/otp/commit/a32f6d210a58ba1e56f54f07c91106efed2c0777 while not breaking the functionality that relx provides. I'll post a PR later for you to try.

The problem around the assumptions about how an Erlang system can and should be structured remains though. While it may have worked to have erts and/or Erlang/OTP in a separate location from the main application, it has never been our intention for a release to be structured that way and thus we do not have any tests for it. Some work needs to be done here so that Erlang/OTP and relx have the same view about what should and should not be supported.

Including Erlang/OTP in a release drags with it a lot of non-cross platform code, so I can understand why you would want to make a cross platform release and keep Erlang/OTP local. But what is the use case for not including erts in the release?

**Comment by shino** [comment]
> But what is the use case for not including erts in the release?

At development time, I sometimes generate ~10 releases to test clustering. ERTS directoy is about 40MB, it sums up ~ 400 MB.
And when I git-clone another version of our application and generate releases, ... Ooops :sweat_smile: 

So main purpose is reducing disk space. There was another reason, fast release generation, which went away after fast SSD.

**Comment by shino** [comment]
In the PR for relx, I hope we can conform the directory structure described at https://www.erlang.org/doc/design_principles/release_structure.html#directory-structure .
(If we could solve errors in windows tests...)

**Comment by garazdawi** [comment]
> In the PR for relx, I hope we can conform the directory structure described at https://www.erlang.org/doc/design_principles/release_structure.html#directory-structure .
> (If we could solve errors in windows tests...)

The structure described there does not allow what you want to do though. It allows for there to be several "lib" folders, but the bin+erts+release folders still need to be in the same place.

**Comment by shino** [comment]
Ah... that's right... I'm not sure in detail how releases directory is used. Should it be there in case the `-boot` argument is given to erlexec?

**Comment by garazdawi** [comment]
The `releases` directory is mostly used when a system needs to do a release upgrade. It contains information about what release version to start by default and which are available to upgrade/downgrade to.

**Comment by garazdawi** [comment]
Please test #5852 and see if it solves your problem.

**Comment by itssundeep** [comment]
Just for context, another reason for not including_erts is we want the ability to run releases built from version V of erlang to run on version V+1 of erlang, without the need to re-build the release. This speeds up validation cycle of V+1. 
This is possible in erlang because of language backward compatibility guarantees and is similar to the idea in JAVA where applications built from one version can run on a higher version of java, without the need to recompile application code.

**Comment by shino** [comment]
> Please test #5852 and see if it solves your problem.

This seems promissing. I will take time to try it in the next week. Thanks!!

**Comment by sile** [comment]
@garazdawi Hi, I'm a colleague of @shino. As he will be off several days, I tried #5852 instead.
It worked as expected (i.e., the crash problem has been solved). Thank you very much for your quick fix!

**Comment by garazdawi** [comment]
> Just for context, another reason for not including_erts is we want the ability to run releases built from version V of erlang to run on version V+1 of erlang, without the need to re-build the release. This speeds up validation cycle of V+1.
This is possible in erlang because of language backward compatibility guarantees and is similar to the idea in JAVA where applications built from one version can run on a higher version of java, without the need to recompile application code.

I assume that you also set `system_libs` to false when doing this?

**Comment by garazdawi** [comment]
> It worked as expected (i.e., the crash problem has been solved). Thank you very much for your quick fix!

Great, thanks for testing!

**Comment by itssundeep** [comment]
> > Just for context, another reason for not including_erts is we want the ability to run releases built from version V of erlang to run on version V+1 of erlang, without the need to re-build the release. This speeds up validation cycle of V+1.
> > This is possible in erlang because of language backward compatibility guarantees and is similar to the idea in JAVA where applications built from one version can run on a higher version of java, without the need to recompile application code.
> 
> I assume that you also set `system_libs` to false when doing this?

Yes.
