### ISSUE TITLE
25.0-rc3 empty tuple is 0 words now, like empty list

### ISSUE THREAD

**Issue by okeuday** [erlang/otp#5900]
**Describe the bug**
Using the repository https://github.com/okeuday/erlang_term/ with rebar 2, the eunit test fails when ran with 25.0-rc3 due to the `t_basic/0` function call equivalent to `16 = erlang_term:byte_size({}, 8)` which can be summarized as calling `erts_debug:flat_size({})` which returns `0`.  If an empty tuple now consumes 0 words like an empty list, it would be good to add this difference at https://www.erlang.org/doc/efficiency_guide/advanced.html#memory (https://github.com/erlang/otp/blob/master/system/doc/efficiency_guide/advanced.xml).

**To Reproduce**
```erlang
$ erl
1> erts_debug:flat_size({}).
0
2> erts_debug:flat_size([]).
0
```

**Expected behavior**
Was expecting `1 = erts_debug:flat_size({}).`

**Affected versions**
25.0

**Additional context**
Not aware of other details related to this.

**Comment by jhogberg** [comment]
Thanks but no thanks, explaining the specifics would just confuse people for no benefit. It's not as simple as "the empty tuple occupies zero words."

As an aside, please stop using OTP internal functionality.

**Comment by essen** [comment]
Out of curiosity, has the size changed compared to before or is it just the internal function's output that has changed?

**Comment by okeuday** [comment]
@essen `erts_debug:flat_size/1` should be correct and there isn't another way to get the information (i.e., no documented function).  Based on its output, an empty tuple consumes 0 words to be the same as an empty list (so, a global constant).  This should have been motivated by reducing the size of an empty map by 1 word, to consume 3 words (in Erlang/OTP 25.0) instead of 4 words (< Erlang/OTP 25.0).

**Comment by jhogberg** [comment]
> Out of curiosity, has the size changed compared to before or is it just the internal function's output that has changed?

For all intents and purposes it's the latter, and I'm not even sure whether we want to keep the changes that led to it. It's one of those cases where an idea looked good on paper and microbenchmarks but turned out to be somewhat disappointing in practice.

> @essen `erts_debug:flat_size/1` should be correct and there isn't another way to get the information (i.e., no documented function). Based on its output, an empty tuple consumes 0 words to be the same as an empty list (so, a global constant). This should have been motivated by reducing the size of an empty map by 1 word, to consume 3 words (in Erlang/OTP 25.0) instead of 4 words (< Erlang/OTP 25.0).

If it were that simple I would've been very happy to say "thanks, feel free to open a PR" instead of closing the issue, it really has nothing to do with reducing heap usage. Furthermore, if our goal was to make the empty map use less memory, wouldn't we have defined that as a global constant instead? :)

Thanks for the inspiration though, the empty map already a literal in nearly all cases but it _does_ live on the heap when the last key is removed from a non-empty map, and it would make sense to return a known literal in that case. I think I'll do that in OTP 26.
