### ISSUE TITLE
persistent_term:get could return random term when racing happens

### ISSUE THREAD

**Issue by zzydxm** [erlang/otp#5908]
**Describe the bug**
In very rare case, we see persistent_term:get/2 returns a random value that has never been set.

For example, we only have 2 write operations for key 'some_key': persistent_term:put('some_key', true) and persistent_term:erase('some_key'), but persistent_term:get('some_key', false) could return an integer or a reference or anything.

Our theory is, persistent_term_get_2 does not have locks, and  *hash_table can be changed during lookup and get_bucket operations.
https://github.com/erlang/otp/blob/master/erts/emulator/beam/erl_bif_persistent.c#L490

Basically, if some persistent_term write operations (erase, put, which changes the erts_atomic_read_nob(&the_hash_table)) happened when doing persistent_term_get_2, *hash_table is possibly freed and filled by anything.

If it also happens that get_bucket(hash_table, entry_index) is a tuple of {_, RandomTerm}, then persistent_term_get_2 will return RandomTerm as result.

**To Reproduce**
This is a really rare racing condition. We can only reproduce that erts_atomic_read_nob(&the_hash_table) can be changed to something different with hash_table while doing lookup and get_bucket operation
see https://github.com/potatosalad/otp/commit/7b460431c53a5715d4ca6d517ccb876470fb7b81

**Expected behavior**
persistent_term:get should never return a value that has never been set.

This might be achievable by adding a read write lock to hash_table: Basically, erts_atomic_read_nob(&the_hash_table) should not be changed when there is an on-going read operation.

If this hurts the performance a lot, we could at least add a lookup_term function which does an atomic operation instead of two steps: entry_index = lookup(hash_table, key); get_bucket(hash_table, entry_index);

**Affected versions**
erts-12.1.2

**Comment by jhogberg** [comment]
Thanks for your report, this was a fun one! :-)

> Our theory is, persistent_term_get_2 does not have locks, and *hash_table can be changed during lookup and get_bucket operations. https://github.com/erlang/otp/blob/master/erts/emulator/beam/erl_bif_persistent.c#L490
> 
> Basically, if some persistent_term write operations (erase, put, which changes the erts_atomic_read_nob(&the_hash_table)) happened when doing persistent_term_get_2, *hash_table is possibly freed and filled by anything.

We use "thread progress" to avoid costly locks and memory barriers in `persistent_term:get/1,2`. You can read more about it [here](https://github.com/erlang/otp/blob/master/erts/emulator/internal_doc/ThreadProgress.md), and I'll use the term "epoch" from here on to say that "thread progress has been made" because it's a bit of a mouthful. The gist of how it makes `persistent_term` safe is:

* Table instances are only freed once an epoch has passed after writing a new instance to `the_hash_table` (making the old instance unreachable). This guarantees that we cannot free a table while it is being observed. The same applies to the contents of the table.
* Only one update can be made at a time and an epoch must pass before the changes are published through an atomic write (whether the table itself or just a bucket). This guarantees that updates cannot be observed out of order, and...
* Since each passing epoch implies a full memory barrier, the content will always be consistent without memory barriers on the individual read operations: seeing the new pointer means that you also see all the changes it points to.

As far as we can see there aren't any problems with this stuff, and @sverker and I found a bug elsewhere that explains the problem quite nicely. Your last paragraph came _very_ close to it:

> If this hurts the performance a lot, we could at least add a lookup_term function which does an atomic operation instead of two steps: entry_index = lookup(hash_table, key); get_bucket(hash_table, entry_index);

Specifically, the `lookup` function searches the table until it either finds or realizes it cannot find an entry, returning the index at which it stopped:

```c
static Uint
lookup(HashTable* hash_table, Eterm key)
{
    Uint mask = hash_table->mask;
    Uint32 idx = make_internal_hash(key, 0);
    Eterm term;

    while (1) {
        term = get_bucket(hash_table, idx & mask);
        if (is_nil(term) || EQ(key, (tuple_val(term))[1]))
            break;
        idx++;
    }
    return idx & mask;
}
```

We hold the update lock over nearly all uses of this function, which guarantees that a `lookup` followed by `get_bucket` on the index returned from the former will return the same term it stopped on, but `persistent_term:get/1,2` doesn't have any locks:

```c
    // persistent_term:get/1
    entry_index = lookup(hash_table, key);
    term = get_bucket(hash_table, entry_index);
    if (is_boxed(term)) {
        ASSERT(is_tuple_arity(term, 2));
        BIF_RET(tuple_val(term)[2]);
    }
    BIF_ERROR(BIF_P, BADARG);
```

Hence, it's possible that `lookup` bails out at some empty index which gets written to by a concurrent update before we call `get_bucket` again, making us return a term we weren't looking for. This was fine back when the tables were immutable and unconditionally swapped out on updates, but broke once we started mutating them for better performance. Shared mutable state strikes again. :-(

Making `lookup` return the term it acted on seems like a pretty straightforward fix. We'll open a PR once we're happy with the test case.

**Comment by zzydxm** [comment]
get_2 can be called while table_updater is running. and get_2 can be called when put_2 is running. I haven't caught a case when get_2 is running but delete_table is also running yet. I just don't see anything prevent it happening.
```
diff --git a/erts/emulator/beam/erl_bif_persistent.c b/erts/emulator/beam/erl_bif_persistent.c
index a836857462..7b8c10b3df 100644
--- a/erts/emulator/beam/erl_bif_persistent.c
+++ b/erts/emulator/beam/erl_bif_persistent.c
@@ -215,6 +215,7 @@ static DeleteOp** delete_queue_tail = &delete_queue_head;

 ErtsLiteralArea** erts_persistent_areas;
 Uint erts_num_persistent_areas;
+HashTable *debug_table = NULL;

 void erts_init_bif_persistent_term(void)
 {
@@ -304,6 +305,9 @@ static int persistent_term_put_2_ctx_bin_dtor(Binary *context_bin)

 BIF_RETTYPE persistent_term_put_2(BIF_ALIST_2)
 {
+    if (BIF_ARG_1 == am_true) {
+        erts_printf("put %T,%p\n", am_true, ethr_self());
+    }
     static const Uint ITERATIONS_PER_RED = 32;
     ErtsPersistentTermPut2Context* ctx;
     Eterm state_mref = THE_NON_VALUE;
@@ -430,6 +434,10 @@ BIF_RETTYPE persistent_term_put_2(BIF_ALIST_2)
          * Now wait thread progress before making update visible to guarantee
          * consistent view of table&term without memory barrier in every get/1.
          */
+        if (BIF_ARG_1 == am_true) {
+            erts_printf("put %T,%d,%p\n", am_true, ctx->hash_table, ethr_self());
+            debug_table = ctx->hash_table;
+        }
         erts_schedule_thr_prgr_later_op(table_updater, ctx->hash_table, &thr_prog_op
);
         suspend_updater(BIF_P);
     }
@@ -496,6 +504,11 @@ BIF_RETTYPE persistent_term_get_2(BIF_ALIST_2)
     Eterm term;

     entry_index = lookup(hash_table, key);
+    if (key == am_true) {
+        erts_printf("get start table:%d, index:%d, scheduler:%p\n", hash_table, entr
y_index, ethr_self());
+        sleep(2);
+        erts_printf("get finish table:%d, index:%d, scheduler:%p\n", hash_table, ent
ry_index, ethr_self());
+    }
     term = get_bucket(hash_table, entry_index);
     if (is_boxed(term)) {
         ASSERT(is_tuple_arity(term, 2));
@@ -1116,6 +1129,10 @@ table_updater(void* data)
     UWord cleanup_bytes;

     old_table = (HashTable *) erts_atomic_read_nob(&the_hash_table);
+    if(debug_table && old_table == debug_table) {
+        erts_printf("update start table:%d, scheduler:%p\n", old_table, ethr_self())
;
+        sleep(1);
+    }
     new_table = (HashTable *) data;
     if (new_table == old_table) {
         Eterm old_term = get_bucket(old_table, fast_update_index);
@@ -1170,6 +1187,10 @@ table_updater(void* data)
                                             &old_table->delete_op.thr_prog_op);
         }
     }
+    if(debug_table && old_table == debug_table) {
+        erts_printf("deleter scheduled table:%d, scheduler:%p\n", old_table, ethr_se
lf());
+        sleep(1);
+    }
     release_update_permission(1);
 }

@@ -1205,6 +1226,9 @@ scheduled_deleter(void* data)
 static void
 delete_table(HashTable* table)
 {
+    if(debug_table && table == debug_table) {
+        erts_printf("delete start table:%d, scheduler:%p\n", table, ethr_self());
+    }
     Uint idx = table->first_to_delete;
     Uint n = table->num_to_delete;

@@ -1226,6 +1250,9 @@ delete_table(HashTable* table)
         idx++, n--;
     }
     erts_free(ERTS_ALC_T_PERSISTENT_TERM, table);
+    if(debug_table && table == debug_table) {
+        erts_printf("delete done table:%d, scheduler:%p\n", table, ethr_self());
+    }
 }
```
in erl shell:
```
persistent_term:put(true,a),spawn(fun() ->timer:sleep(10),persistent_term:erase(true) end),[spawn(fun() ->timer:sleep(20),persistent_term:get(true,b) end)||_<-lists:seq(1,100)].
```
output:
update start table:1477957688, scheduler:0x00007fe35a888640
get start table:1477957688, index:19, scheduler:0x00007fe35ae8e640
deleter scheduled table:1477957688, scheduler:0x00007fe35a888640
get finish table:1477957688, index:19, scheduler:0x00007fe35ae8e640

**Comment by zzydxm** [comment]
Ah I see, so it is visiting an entry while put_2 is mutating the persistent term table. Rather than visiting a random freed memory. Thanks for the explanation!

**Comment by jhogberg** [comment]
I've opened a PR (#5918) that should fix the problem, I'll try to get patches out within the a week or two. Thanks again for your report! :-)
