### ISSUE TITLE
TLS client handshake failure after upgrade to Erlang 24.3.4 on ubuntu

### ISSUE THREAD

**Issue by torfaxen** [erlang/otp#5961]
**Describe the bug**

TLS client handshake failure after ansible upgrade of rabbitMQ 3.9.16 and Erlang 24.3.4 on ubuntu.

error in rabbitmq log after attempted login
2022-05-04 16:51:00.992701+02:00 [notice] <0.18735.132> TLS client: In state hello at ssl_handshake.erl:892 generated CLIENT ALERT: Fatal - Handshake Failure
2022-05-04 16:51:00.992701+02:00 [notice] <0.18735.132>  - {unknown_or_malformed_handshake,13}
2022-05-04 16:51:00.998454+02:00 [notice] <0.18738.132> TLS client: In state hello at ssl_handshake.erl:892 generated CLIENT ALERT: Fatal - Handshake Failure
2022-05-04 16:51:00.998454+02:00 [notice] <0.18738.132>  - {unknown_or_malformed_handshake,13}
2022-05-04 16:51:01.004422+02:00 [notice] <0.18741.132> TLS client: In state hello at ssl_handshake.erl:892 generated CLIENT ALERT: Fatal - Handshake Failure
2022-05-04 16:51:01.004422+02:00 [notice] <0.18741.132>  - {unknown_or_malformed_handshake,13}
2022-05-04 16:51:01.010206+02:00 [notice] <0.18746.132> TLS client: In state hello at ssl_handshake.erl:892 generated CLIENT ALERT: Fatal - Handshake Failure
2022-05-04 16:51:01.010206+02:00 [notice] <0.18746.132>  - {unknown_or_malformed_handshake,13}
2022-05-04 16:51:01.015938+02:00 [notice] <0.18742.132> TLS client: In state hello at ssl_handshake.erl:892 generated CLIENT ALERT: Fatal - Handshake Failure
2022-05-04 16:51:01.015938+02:00 [notice] <0.18742.132>  - {unknown_or_malformed_handshake,13}
2022-05-04 16:51:01.021607+02:00 [notice] <0.18736.132> TLS client: In state hello at ssl_handshake.erl:892 generated CLIENT ALERT: Fatal - Handshake Failure
2022-05-04 16:51:01.021607+02:00 [notice] <0.18736.132>  - {unknown_or_malformed_handshake,13}
2022-05-04 16:51:01.021815+02:00 [warning] <0.18732.132> HTTP access denied: rabbit_auth_backend_cache failed authenticating username@hostname: ldap_connect_error

Error persist when upgrading to rabbitmq 3.10.0 

**To Reproduce**
upgrade
RabbitMQ 3.9.10 & Erlang 24.1.7
to
RabbitMQ 3.9.16 & Erlang 24.3.4
with ansible and attempt to login

**Expected behavior**

login directly after upgrade

**Affected versions**

24.3.4

**Additional context**
attaching relevant rabbitmq config
[advanced.config.txt](https://github.com/erlang/otp/files/8621469/advanced.config.txt)
[rabbitmq.conf.txt](https://github.com/erlang/otp/files/8621470/rabbitmq.conf.txt)

**Comment by IngelaAndin** [comment]
It seems suspicious that this is happening in the hello state! Will hopefully have time to take a closer look tomorrow.

**Comment by michaelklishin** [comment]
I have missed this issue and filed another one. I'll post our (few and far between) findings reported there FTR:

**Describe the bug**

TLS-enabled `eldap` connections from the RabbitMQ LDAP plugin succeed
on `24.3.3` but fail on `24.3.4`. Downgrading Erlang to `24.3.3` makes
the issue go away.

**To Reproduce**

Unfortunately the RabbitMQ environment this [was reported against](https://github.com/rabbitmq/rabbitmq-server/discussions/4726) 
uses a pretty exotic combination
of authentication-related features, plus TLS is involved.
We are trying to collect a much smaller reproducible case. I don't
have any ETA on this.

However, there were `ssl` application changes in `24.3.4`
so this is unlikely to be a coincidence. Since this release is still very new,
I decided to file this even with the amount of information we have.

**Expected behavior**

TLS-enabled LDAP connections should succeed just like before.

**Affected versions**

24.3.4

I have noticed that [the diff between `24.3.3` and `24.3.4` is non-trivial in size](https://github.com/erlang/otp/compare/OTP-24.3.3...OTP-24.3.4).
https://github.com/erlang/otp/issues/5898 seems pretty relevant.

**Comment by IngelaAndin** [comment]
I do not suspect #5898 but rather the solution to #5835

Looking at the symptoms I would guess that the following patch would make the problem go away.

```
diff --git a/lib/ssl/src/ssl_handshake.erl b/lib/ssl/src/ssl_handshake.erl
index ee102077af..804a996d53 100644
--- a/lib/ssl/src/ssl_handshake.erl
+++ b/lib/ssl/src/ssl_handshake.erl
@@ -863,11 +863,11 @@ decode_handshake(_Version, ?CERTIFICATE_STATUS, <<?BYTE(?CERTIFICATE_STATUS_TYPE
         response = ASN1OcspResponse};
 decode_handshake(_Version, ?SERVER_KEY_EXCHANGE, Keys) ->
     #server_key_exchange{exchange_keys = Keys};
-decode_handshake({3, 3} = Version, ?CERTIFICATE_REQUEST,
+decode_handshake({Major, Minor} = Version, ?CERTIFICATE_REQUEST,
                  <<?BYTE(CertTypesLen), CertTypes:CertTypesLen/binary,
                    ?UINT16(HashSignsLen), HashSigns:HashSignsLen/binary,
-                   ?UINT16(CertAuthsLen), CertAuths:CertAuthsLen/binary>>) ->
-    HashSignAlgos = decode_sign_alg(Version, HashSigns),
+                   ?UINT16(CertAuthsLen), CertAuths:CertAuthsLen/binary>>)  when Major == 3, Minor >= 3 ->
+    HashSignAlgos = decode_sign_alg({3,3}, HashSigns),
     #certificate_request{certificate_types = CertTypes,
                          hashsign_algorithms = #hash_sign_algos{hash_sign_algos = HashSignAlgos},
                         certificate_authorities = CertAuths};

```
I am a little surprised thought that this possible timing issue did not show up in any of all our tests.

**Comment by michaelklishin** [comment]
@IngelaAndin thank you so much for looking into it. We seem have a way to reproduce an an exception trace from the original environment in https://github.com/rabbitmq/rabbitmq-server/discussions/4726#discussioncomment-2695386.

**Comment by IngelaAndin** [comment]
I think I know why this is happening and will work on a more logical patch on Monday. I do not have time to explain the details right now, however, the purposed patch might be considered a workaround.

**Comment by lukebakken** [comment]
Thanks @IngelaAndin! Here's a link to my comment [link](https://github.com/erlang/otp/pull/5975#issuecomment-1131778712)

**Comment by lukebakken** [comment]
@IngelaAndin My guess is that this issue comes down to some TLS implementation detail in Windows, so I'm going to see if I can reproduce it using a simple .NET TLS server and Erlang client on Windows.

**Comment by lukebakken** [comment]
@juanperi any chance you could share more information, like a packet trace?

**Comment by lukebakken** [comment]
@IngelaAndin I found a handy .NET project that has example TLS servers and clients. I forked it and added a test Erlang client here:

https://github.com/lukebakken/NetCoreServer/tree/lukebakken/otp-5961

I'm using Windows 10 and Erlang 25. When the test Erlang client tries to connect to a running `SslChatServer` the handshake phase hangs.

Here's how to reproduce on Windows 10 with .NET 6 installed:

```
git clone https://github.com/lukebakken/NetCoreServer.git
cd NetCoreServer
dotnet build
cd .\examples\SslChatServer\bin\Debug\net6.0
.\SslChatServer.exe
```

Then, in another terminal session:

```
cd path\to\NetCoreServer\tools
erlc +debug tls_client.erl
erl -run tls_client
```

Interestingly enough, the test client works using Erlang 24.3.2, 24.3.3 and 24.3.4 in my environment. Only Erlang 25 hangs.

**Comment by IngelaAndin** [comment]
Thank you for the new input, not ignoring you! We just happen to have workfree days Thursday and Friday this week. Will be a priority to continue this on Monday.

**Comment by juanperi** [comment]
> @juanperi any chance you could share more information, like a packet trace?

I should be able to provide `dbg:tracer().` information if you point me to what you would like to know.
I can also run the `ssl:connect` in debug mode and share the outcome (minus some information that might be sensitive), 

Not sure if useful, but comparing the output of a working `ssl:connect` with self signed certificates and a server started with
```
openssl s_server -cert server-cert.pem -key server-key.pem -WWW -port 12345 -CAfile ca-cert.pem -verify_return_error -Verify 1
```
vs the one that fails, the biggest difference I see, not related to the content of the certs is:
![image](https://user-images.githubusercontent.com/203349/170648102-d28ca89a-d00f-4a79-ba6f-8c14e2d697ad.png)

@IngelaAndin Enjoy your time off!!

**Comment by IngelaAndin** [comment]
I think I understand the rest of the problem, working on a solution and will hopefully have a new PR  later this week.

**Comment by IngelaAndin** [comment]
@juanperi thanks for the offer to provide more debug info. If you could try my latest PR that would very helpful. And if it still does not work we can try some tracing commands.

**Comment by IngelaAndin** [comment]
@lukebakken  if you can try the PR on your windows environment that would be good too. I do not have easy access to a windows environment.

**Comment by juanperi** [comment]
hey @IngelaAndin, it didn't work for me. I got:
```
=NOTICE REPORT==== 1-Jun-2022::09:36:34.097521 ===
TLS client: In state certify at ssl_gen_statem.erl:727 generated CLIENT ALERT: Fatal - Unexpected Message
 - {unexpected_msg,{internal,{ssl_tls,22,undefined,
                                      <<11,0,19,148,0,19,145,0,6,41,48,130,
........... [long binary] .......
                                        111,116,32,67,65,32,51,14,0,0,0>>}}}
{error,{tls_alert,{unexpected_message,"TLS client: In state certify at ssl_gen_statem.erl:727 generated CLIENT ALERT: Fatal - Unexpected Message\n {unexpected_msg,{internal,{ssl_tls,22,undefined,\n                                    <<11,0,19,148,0,19,145,0,6,41,48,...>>}}}"}}}
```

**Comment by IngelaAndin** [comment]
@juanperi @lukebakken Thank you both for trying, seems I missed a wrapper atom for the event. I have pushed a new version please try again!

**Comment by juanperi** [comment]
Hey @IngelaAndin, I just tried your patch and it worked!! 🎉 
calling:
```
ssl:connect(
  "the_url",
  9094,
  [
    {verify, verify_none},
    {cacertfile, "certificate_chain"},
    {keyfile, "key"},
    {certfile, "certificate"},
    {password, "the_pass"}
  ],
  3000
).
```
I had to pass verify_none. If I pass verify_peer, it fails with unknown CA. But I suspect that is a different problem, right?

**Comment by IngelaAndin** [comment]
Yes, that is a different problem. It is because you need to include the trusted anchor certs in cacertfile to be able to verify the server's certificate chain. The chain certificates for the client may however be included in certfile as long as the end-entity certificate comes first. See also new option in OTP 25  certs_keys

**Comment by juanperi** [comment]
> Yes, that is a different problem. It is because you need to include the trusted anchor certs in cacertfile to be able to verify the server's certificate chain. The chain certificates for the client may however be included in certfile as long as the end-entity certificate comes first. See also new option in OTP 25 certs_keys

Awesome!! Thank you for your time working on this @IngelaAndin !!!! With your latest patch it seems to be working for me properly

**Comment by lukebakken** [comment]
@IngelaAndin yes with the latest change my test application works. I am using `verify_peer` as well and that works.

In addition, this PR fixes the LDAP connection error I mentioned. Details can be found here:

https://github.com/erlang/otp/pull/5975#issuecomment-1131778712
https://github.com/rabbitmq/rabbitmq-server/discussions/4726#discussioncomment-2784005

Thank you!

**Comment by 36PopTarts** [comment]
> Yes, that is a different problem. It is because you need to include the trusted anchor certs in cacertfile to be able to verify the server's certificate chain. The chain certificates for the client may however be included in certfile as long as the end-entity certificate comes first. See also new option in OTP 25 certs_keys

Hi, I'm encountering an SSL error with Erlang 24.3.3 and RabbitMQ 3.10.5 after updating from 3.8 that is blowing my mind at the moment and this sounds like my exact issue. I have 8 servers which all consume from the same broker cluster. 5 of them work, 3 of them don't, they all use the exact same PKCS12 cert bundle (it has a wildcard leaf cert). The error looks like this:
`2022-06-03 08:34:27.145139-05:00 [notice] <0.3575.0> TLS server: In state wait_cert at ssl_handshake.erl:2074 generated SERVER ALERT: Fatal - Unknown CA
2022-06-03 08:34:27.145139-05:00 [notice] <0.3575.0>`
The other 5 servers log in just fine. The 3 failing servers worked before I upgraded when we were running RabbitMQ 3.8. Most peculiarly, the second line is blank where I think the reason for the issue is supposed to be. Does this look like the problem you were talking about or should I open a new issue? Can I fix this by adding the root cert to the certificate bundle? Thanks for replying to this issue, this is the closest I've come to figuring out my problem.

**Comment by lukebakken** [comment]
@36PopTarts, it's generally not a good idea to ask a question unrelated to the issue at hand, especially if the issue is closed.

If you would like assistance with your issue, ask in one of the following places:
* [`rabbitmq-users` mailing list](https://groups.google.com/g/rabbitmq-users). This is probably the best choice since you're using RabbitMQ. If you ask there I'll most likely be the person answering.
* [Erlang Forms](https://erlangforums.com/)
* [`erlang-questions` mailing list](http://erlang.org/mailman/listinfo/erlang-questions)
