### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by jbevemyr** [erlang/otp#5990]
**Describe the bug**
The state of a gen_server is still accessible even with process_flag(sensitive, true)
and the format_state() callback implemented.

**To Reproduce**
Start a gen_server and set the process_flag(senstive,true) in the init() function.
Then invoke sys:get_state() on the gen_server instance. The state will be returned.

**Expected behavior**
I would expect some mechanism for hiding the gen_server state when the sensitive
flag is set.

**Affected versions**
All version after the senstive flag was introduced.

**Additional context**
One solution would be to modify the gen_server code in the following way.
I have not found any better way to read the state of the senstive flag then
actually setting it.

```
diff --git a/lib/stdlib/src/gen_server.erl b/lib/stdlib/src/gen_server.erl
index 8f61438b5e..585fc927bd 100644
--- a/lib/stdlib/src/gen_server.erl
+++ b/lib/stdlib/src/gen_server.erl
@@ -857,11 +857,23 @@ system_code_change([Name, State, Mod, Time, HibernateAfterTimeout], _Module, Old
     end.

 system_get_state([_Name, State, _Mod, _Time, _HibernateAfterTimeout]) ->
-    {ok, State}.
+    case erlang:process_flag(sensitive, true) of
+        false ->
+            erlang:process_flag(sensitive, false),
+            {ok, State};
+        true ->
+            {ok, hidden}
+    end.

 system_replace_state(StateFun, [Name, State, Mod, Time, HibernateAfterTimeout]) ->
     NState = StateFun(State),
-    {ok, NState, [Name, NState, Mod, Time, HibernateAfterTimeout]}.
+    case erlang:process_flag(sensitive, true) of
+        false ->
+            erlang:process_flag(sensitive, false),
+            {ok, NState, [Name, NState, Mod, Time, HibernateAfterTimeout]};
+        true ->
+            {ok, hidden, hidden}
+    end.

 %%-----------------------------------------------------------------
 %% Format debug messages.  Print them as the call-back module sees 
 ```

**Comment by pouriya** [comment]
Hi. See #2543 for more information

**Comment by jbevemyr** [comment]
On second thoughts I would not patch system_replace_state(). The aim is to protect agains generic debug tools that accidentally expose sensitive data through get_state().

**Comment by rickard-green** [comment]
We do not see this as a security issue. You should not be able to execute arbitrary code on a node unless you are trusted.

The intent with the `sensitive` flag was to prevent sensitive data to end up logs, crash dumps etc which unauthorized persons might get access to. It is intended to be used in combination with `format_status()` which *only* modifies the state returned by `sys:get_status()` which is used when logging.

There is no support for a `format_state()` callback since `sys:get_state()` is only intended for debugging and should not be used when producing output that can be viewed by unauthorized persons. Even if we prevented `sys:get_state()` from returning the state there might be other ways to get access to this data, and we do not want to start giving any guarantees that we will prevent code from accessing such data. Providing such a guarantee would require a lot of thought and work trying to figure out all possible ways the data might be accessed.

**Comment by jbevemyr** [comment]
Ok, with that explanation in mind, is there any reason bt/3 is blocked in the shell? It would be very useful to have it available in the shell while still blocking backtraces from logs.
