### ISSUE TITLE
try after end may not always run

### ISSUE THREAD

**Issue by leoliu** [erlang/otp#6049]
**Describe the bug**
I have been assuming that AfterBody as in `try ... after ... end`  is always run. But there is one case it is not.

**To Reproduce**
Run `try exit(self(),kill) after error(not_run) end.`

**Expected behavior**
AfterBody should run and cause exception `not_run`.

**Affected versions**
OTP 24,25

**Additional context**

Notice this bug while working with ets counters and notice that sometimes they are not decremented correctly because I randomly kill pids from the process list (for example using observer).

**Comment by essen** [comment]
That's because you are using `exit/2` which sends an exit signal to the process, and doesn't throw an exit exception like when you use `exit/1`.

```
7> try exit(kill) after error(not_run) end.
** exception error: not_run
```

The process gets killed "externally" rather than the code throwing the exception. See the green note at https://www.erlang.org/doc/man/erlang.html#exit-2 for details.

**Comment by leoliu** [comment]
Thanks @essen. I was looking at the Erlang reference manual on the `try` expression :(
