### ISSUE TITLE
Compiler is not leveraging literal map tuples as frequently as possible

### ISSUE THREAD

**Issue by josevalim** [erlang/otp#6139]
**Describe the bug**

Take the following code:

```erlang
-module(foo).
-compile(export_all).

decimal(Int) ->
  #{type => decimal, int => Int, exp => 0}.
```

I would expect the following property to be true:

```erlang
A = foo:decimal(0),
B = foo:decimal(1),
erts_debug:same(erts_internal:map_to_tuple_keys(A), erts_internal:map_to_tuple_keys(B)).
```

However, that's not the case! This means that every invocation of the function is allocating a new tuple keys, not fully leveraging #1498.

I found the optimization only happens when we are creating a new map where all values are not literals (or all values are literals)! So this will optimize:

```erlang
-module(foo).
-compile(export_all).

decimal(Int) ->
  #{type => Int, int => Int, exp => Int}.
```

Having maps mixed with literal and non-literal keys is likely the most common scenario and therefore it would make more sense if the optimization applied for all maps with _literal keys_. This has the benefit of considerably reducing the memory allocation of programs that use maps.

**Affected versions**
Probably all versions with maps.

**Comment by michalmuskala** [comment]
The produced bytecode seems quite surprising:

```
    {put_map_assoc,{f,0},
                   {literal,#{type => decimal}},
                   {x,0},
                   1,
                   {list,[{atom,exp},{integer,0},{atom,int},{x,0}]}}.
```

So even for the two keys that are literals, one is pre-allocated, and another created dynamically.

**Comment by michalmuskala** [comment]
The problem seems to be in the `v3_core` pass where it tries to be "too clever". In particular the `cerl:ann_c_map` function tries to do some naive constant folding (which doesn't really work, and breaks other optimisations).

https://github.com/erlang/otp/blob/5d7398fd42b65843a0278d60a8f4236edd282d9f/lib/compiler/src/cerl.erl#L1650-L1677

I can see two solutions:
* "dumb down" the `cerl:ann_c_map` function to not try do anything fancy
* "unfold" constant maps in `put_map_assoc` before emitting the instructions - this would also catch macro-generated things like `#{key_1 => 1}#{key_2 => 2}`

**Comment by josevalim** [comment]
Even if we dumb down cerl:ann_c_map, we would still emit this:

```
    {put_map_assoc,{f,0},
                   {literal,#{}},
                   {x,0},
                   1,
                   {list,[{atom,type},{atom,decimal},{atom,exp},{integer,0},{atom,int},{x,0}]}}.
```

So I am assuming the above will be able to extract the literal keys, however, the code will still attempt to merge the list of values, key by key, doing unnecessary comparisons?

In this case, wouldn't it be better to emit/load something like:

```elixir
    {put_map_literal,{f,0},
                   [type, exp, int],
                   {x,0},
                   1,
                   {list,[{atom,decimal},{integer,0},{x,0}]}}.
```

Where we assume there is a literal key and the values are put immediately in the given order? Or will the loader be able to convert the earlier instruction into something similar to the above?

**Comment by michalmuskala** [comment]
This optimisation of pre-allocating a key tuple for  a `put_map_assoc` instruction with an empty base map and all keys being literals is done in the loader. So it would be enough to emit the "unfolded":
```
    {put_map_assoc,{f,0},
                   {literal,#{}},
                   {x,0},
                   1,
                   {list,[{atom,type},{atom,decimal},{atom,exp},{integer,0},{atom,int},{x,0}]}}.
```

**Comment by michalmuskala** [comment]
@josevalim I think this might benefit from some more sophisticated solution. In particular, this simple case will not pick up on things like:
```erlang
A = #{key1 => V1, key2 => V2},
A#{key3 => V3}
```
which should also benefit from such optimisations.

As to the optimisation, you don't really have to cache or remember the key tuple. You only need to remember the index. If the key under the particular index is the same, you can just look up the value without checking.

So rather than optimising to something like:
```
if (KeyTuple == CachedKeyTuple) {
   ValueTuple[CachedIndex]
}
```

you can do something like:

```
if KeyTuple[CachedIndex] == Key {
    ValueTuple[CachedIndex]
}
```

It involves one more memory read, but does not suffer from the issue that requires key sets to be the exact same literal value (and it won't be for maps allocated in different modules since the key tuple literal is allocated once per module building the map).

**Comment by garazdawi** [comment]
> It involves one more memory read

You would have to check the size also, so two more reads :) Though that read should be in L1 so should be relatively quick!

**Comment by Qqwy** [comment]
I came across @josevalim's call for help on faster lookups [on Twitter](https://twitter.com/josevalim/status/1547192000650280960) and wanted to pitch in my two cents, for whatever they are worth.


On binary search: I know from other projects (Notably: benchmarks done on the Rust persistent data structures library  `im-rs`) that for tiny collections, a linear search will probably be faster than a binary search by virtue of how modern computer architectures work (prefetching, branch prediction and cache lines). Of course, every situation is different; profiling is everything.

On SIMD: It is actually possible to convince the C compiler today to better optimize the given searching loop. 
There are two pieces of information which we are aware of but the compiler in the current version is not.

1. Keys in a map are unique. In other words: there are no duplicate elements in the `ks` array. Thus, there is no need to return 'the first match' from the loop.
2. Flatmaps have at most 32 keys.

These two things together allow us to move the `return` statement out of the loop without worrying about degrading performance.
Since we now no longer 'return fast' from the loop, individual loop iterations depend less on each other. This in turn allows for more compiler optimization flexibility.

```
    Uint *res = NULL;
    for (i = 0; i < n; ++i) {
	if (ks[i] == key) {
	    res = &vs[i];
	}
    }
    return res;
```

[Full example on Godbolt](https://godbolt.org/z/7E3oEM4hr)

Depending on exact compiler versions, target architecture and compiler options, Clang and GCC turn this code into a partially or fully unrolled loop, in some cases using SIMD (AVX) instructions.

I expect performance to be better for these versions, but of course profiling is necessary to be sure.

**Comment by Qqwy** [comment]
I made a microbenchmark  to compare the new approach (and some related ones) with the original one. 

[repo + detailed results here](https://github.com/Qqwy/erlang-smallmap-get-benchmark)

Building and running it on your own machines is hopefully very straightforward and simple. I'm very eager find out the results!

On my computer, gcc and clang (with `-O2`) create assembly for the new implementation that is between 5-15% faster than the original one, depending on map size.

Of course, take this microbenchmark with a huge grain of salt. In a full Erlang runtime there are thousands of other things going on that compete for caches and CPU time. But these initial results seem promising enough to try a full-sized benchmark in which erts as a whole is compiled with the different options next.

**Comment by Qqwy** [comment]
Here is a plot of the results of these simple C benchmarks:

![image](https://user-images.githubusercontent.com/5345745/179506487-d0424b20-6485-42a4-9d7a-baeb6acdc1cd.png)

I'll try to build separate ERTS binaries next and benchmark @josevalim 's example program with these.

**Comment by bjorng** [comment]
I have created a pull request based on José Valim's suggested implementation: #6178

**Comment by bjorng** [comment]
> I think this might benefit from some more sophisticated solution. In particular, this simple case will not pick up on things like:

```
A = #{key1 => V1, key2 => V2},
A#{key3 => V3}
```

Have you seen that kind of code in practice? It should be easy to add an optimisation that combines those two map operations, but before I do would like to know that it would apply to real-world code.

**Comment by josevalim** [comment]
@bjorng from the Elixir side it is not very common, because we don't have a syntactical operation that adds a key to a map (only updates).

**Comment by michalmuskala** [comment]
I haven't seen it in direct code, but I saw it pop up couple times from macros & inlining in our codebase

**Comment by bjorng** [comment]
> I haven't seen it in direct code, but I saw it pop up couple times from macros & inlining in our codebase

@michalmuskala OK, I have extended the CSE optimisation to also combine adjacent map update operations.

**Comment by josevalim** [comment]
In case anyone is keeping tabs on this, this post discusses how a new LuaJIT implements the map key cache lookup (hidden classes) by emitting inline caches assembly: https://sillycross.github.io/2022/11/22/2022-11-22/
