### ISSUE TITLE
Where can I find the native implementation of `send` and `receive` 

### ISSUE THREAD

**Issue by ss3681755** [erlang/otp#6176]
I am new to elixir/erlang and want to understand how the `send` and `receive` are implemented. Are they even part of erlang or is it something that comes from beam itself.  If someone can point to me the native implementation that'll be great.

**Describe alternatives you've considered**
I started looking into the elixir code then figured out it comes from erlang, I tried looking into the erlang itself but I couldn't find it due to my limited experience.

**Comment by RaimoNiskanen** [comment]
erts/emulator/drivers/common/inet_drv.c (a C driver) or erts/emulator/nifs/common/prim_socket_nif.c, a NIF module (Native Implemented Function).

What Erlang functions, exactly (`gen_tcp:send/2`, `socket:send/2,3,4`, or some other function)?

**Comment by paulo-ferraz-oliveira** [comment]
@RaimoNiskanen, I read `send` as `!`, in agreement with the `receive` block. Tried to look for this, but couldn't find it either 😄

**Comment by RaimoNiskanen** [comment]
Well, then, I must have had my socket glasses on...

`erlang:send/2,3` (and `erlang:'!'/2'`, also known as the operator `!`) and the `receive`...`after`...`end` statement are very much part of the VM - they are inherent in the light-weight Erlang process model.

There is a message queue in the Erlang process structure. `!` appends messages to the target process' queue, and `receive` matches messages from its own process' queue.

Both operations are implemented as BEAM instructions.  If you compile this module:
``` erlang
-module(test3).
-export([t/0]).
t() ->
    self() ! message,
    receive
        Message ->
            Message
    end.
```
with `erlc -S` to produce an assembly listing test3.S, the function `t/0` gets this code:
``` erlang
{function, t, 0, 2}.
  {label,1}.
    {line,[{location,"test3.erl",3}]}.
    {func_info,{atom,test3},{atom,t},0}.
  {label,2}.
    {allocate,0,0}.
    {bif,self,{f,0},[],{x,0}}.
    {move,{atom,message},{x,1}}.
    {line,[{location,"test3.erl",4}]}.
    send.
  {label,3}.
    {loop_rec,{f,4},{x,0}}.
    remove_message.
    {deallocate,0}.
    return.
  {label,4}.
    {wait,{f,3}}.
```
`send`, `{loop_rec,Label,Register}`, `{wait,Label}` and `remove_message` are the instructions in play here.
There is a whole set of instructions for looping through the message queue, matching, and waiting.

`erlang:send/2,3` are also reachable as functions and are implemented in erts/emulator/beam/bif.c:send_2,3.

`receive` is more complicated since it is interwoven with process scheduling and performs pattern matching.  I do not really know where all involved .BEAM instructions are implemented...

**Comment by garazdawi** [comment]
> receive is more complicated since it is interwoven with process scheduling and performs pattern matching. I do not really know where all involved .BEAM instructions are implemented...

It is the `loop_rec` instruction that receives new messages. The implementation for the interpreter is located [here](https://github.com/erlang/otp/blob/62ff88c44c5ac81ecaab7be7baca53ae7935e146/erts/emulator/beam/emu/msg_instrs.tab#L87-L188). There is also some useful documentation in [erl_proc_sig_queue.h](https://github.com/erlang/otp/blob/62ff88c44c5ac81ecaab7be7baca53ae7935e146/erts/emulator/beam/erl_proc_sig_queue.h) about how signals work.
