### ISSUE TITLE
`term()` vs. `any()` vs. `_`

### ISSUE THREAD

**Issue by TD5** [erlang/otp#6289]
**Is your feature request related to a problem? Please describe.**
Periodically, I see users confused by `term()` vs. `any()` vs. `_` - they're not sure if there is a difference in meaning between them, or which they should use once they discover they all amount to the same thing.

Each seems to be preferred in at least one sort of scenario, so there doesn't seem to be a consensus around a particular convention:
- `any()` seems to be the default printed by `erl_pp`
- `_` is used by `erl_pp` for map keys/values and tuple elements, presumably for compactness?
- `term()` seems to be preferred in OTP function specs

**Describe the solution you'd like**
- Perhaps some official word on when to use `term()` vs. `any()` vs. `_`, plus maybe some context on why all three exist.
- Long term, unify on a single syntax, or at least a long and a short name, e.g., say, `term()` and `_`

**Comment by josevalim** [comment]
If I am not mistaken, `_` is not valid in typespecs (except in bitstrings?), only in patterns. It exists in a different context than `term()` and `any()`. 

`term()` and `any()` are considered equivalent and such is mentioned here: https://www.erlang.org/doc/reference_manual/typespec.html - the table says `term()` is defined as `any()`. AFAIK which one to use is totally a matter of personal preference but note tools like Gradualizer consider them to be distinct.

**Comment by TD5** [comment]
> If I am not mistaken, _ is not valid in typespecs (except in bitstrings?), only in patterns. It exists in a different context than term() and any().

That's just it: despite it not being documented as a valid way to _input_ an `any()` type, `erl_pp` (the module powers the rendering of types in Dialyzer, etc) will _output_ it in place of `any()` in several circumstances, which can cause some confusion for users.

> the table says `term()` is defined as `any()`

I think the documentation does a good job on making this clear, but it is a common question I see from Erlang beginners which causes a small amount of friction (they typically presume there must be _some_ difference, else why do they both exist?)

**Comment by ilya-klyuchnikov** [comment]
> If I am not mistaken, _ is not valid in typespecs

https://github.com/erlang/otp/blob/54df3e34d288a18ff5846196fb09e1cdceb07fea/lib/stdlib/src/gb_sets.erl#L201

**Comment by josevalim** [comment]
@TD5 @ilya-klyuchnikov TIL, thanks.

Then I agree that `_` should most likely be phased out in favor of `any()` or `term()`.

**Comment by kostis** [comment]
The `set()` example from `gb_sets` is probably a relic from when there was no support for parametric opaque types.
Quite likely, it has been kept for backwards compatibility (i.e., just because there may be code out there that uses `gb_sets:set()` instead of `gb_sets:set(T)` from some type `T`.  Perhaps the non-parametric type should be removed in a future version.

Now, having written all the above, a declaration like
```erlang
-type set() :: set(_).
```
(to me at least) seems **the most natural one** that one can write.  It expresses _precisely_ the fact that here I declare a (new) type using an existing parametric type and I simply do not care at all what this parameter is.  This what the `_` is used for everywhere else in Erlang code.

**Comment by TD5** [comment]
> seems the most natural one that one can write

```
-type set() :: set(_).
```

```
-type set() :: set(any()).
```

```
-type set() :: set(term()).
```

With enough exposure, any of them feel natural enough to me, but my question is why we might want or need three ways to express the same thing. Is it just a historical accident (that maybe we could clean up?), or is there further motivation for them?

Possible arguments for why me might want more than one:
- They subjectively feel more natural in different situations
- One is a convenient shorthand for another, but there's no need for a third (say `_` is short for `term()`)
- So some tools can choose to give them different semantics and not treat them as aliases (@josevalim pointed out that Gradualizer may do this)
- It's a historical accident, but trying to clean it up now isn't worth the opportunity cost

**Comment by kostis** [comment]
> ... but my question is why we might want or need three ways to express the same thing.

Let's first look at the bigger picture here.  By its construction, the type language of Erlang (as well as most other type languages I know of) allows for _type aliases_, i.e., definitions of the form:
```erlang
-type new_type_name() :: existing_type_name().
```
So, in principle, one can create an _unbounded number of names for the same type_.  Currently, there is no way to stop that.

So, simply think of `term()` as having an invisible definition in the `erlang` module of the form:
```erlang
-type term() :: any().
```
in exactly the same way that the same module has e.g. the following invisible definitions:
```erlang
-type node()   :: atom().
-type module() :: atom().
```
Do these two cause any confusion in your opinion?  Should they also be removed?  (In some sense, they are not _needed_.)


So, I hope that we at least agree that **the problem is a general one**: An Erlang programmer _has_ to come to terms with the fact that there may be more than one way -in fact, possibly many- to express the same thing.  There is no way around it. (Unless of course the language prohibits type aliases from now on.  -- I think this will be a bad idea.)


Of course, I know what you are thinking at this point.  Namely, that you are not _really_ complaining about `term()`, but it's `_` that you want to eliminate instead.  (And, indeed, `_` is not something that you can define with a type declaration.)

However, `_` exists for another reason, which (I am guessing) you are probably not (fully) aware of.  As you well know, the Erlang type language also comes with type variables.  These are needed for parametric types and were also introduced for subtype constraints (e.g. `is_subtype(X, Y)` which over the years became `X :: Y`).

Erlang (and Elixir) programmers have found many uses of them.  One of them is to write specs of this form:
```erlang
-spec foo(Arg1, Arg2) -> Ret when Arg1 :: integer(), Ret :: bar_t().
```
i.e., to give arguments _type names_ with type variables, so that they can refer to them for documentation purposes.

The problem of course with the above is that you cannot really write this.  (If you do, you will get a compiler error telling you that `type variable 'Arg2' is only used once (is unbound)`).
But, wait, this is the same as writing:
```erlang
-spec foo(Arg1, Arg2) -> Ret when Arg1 :: integer(), Arg2 :: any(), Ret :: bar_t().
```
and in fact, if you are clever, you can convince the compiler to accept this by writing:
```erlang
-spec foo(Arg1, _Arg2) -> Ret when Arg1 :: integer(), Ret :: bar_t().
```
which, naturally, means the same as the line above -- it's just that it saves some typing (pun intended).

So, anonymous type variables do exist in the language.

You probably know where this is going by now.  Given all the above, if programmers are super lazy, they can also write:
```erlang
-spec foo(Arg1, _) -> Ret when Arg1 :: integer(), Ret :: bar_t().
```
which explains why `_` is an alias / shorthand of `any()`. 

Bottomline: `_` is not really a type, it's an anonymous type variable which is not constrained (i.e. it is `any()`).

**Comment by TD5** [comment]
> So, I hope that we at least agree that the problem is a general one: An Erlang programmer has to come to terms with the fact that there may be more than one way -in fact, possibly many- to express the same thing.

The practical issue I see is OTP uses three aliases without, as far as I can see, much difference difference between them except what I mentioned in the original description (e.g. `_` is conveniently compact).

> Of course, I know what you are thinking at this point. Namely, that you are not really complaining about term(), but it's _ that you want to eliminate instead. (And, indeed, _ is not something that you can define with a type declaration.)

Nope, I have no particular agenda to get rid of it. Indeed, I like that it's compact. If anything, having both `term()` and `any()` seems least useful to me, since I can't see much benefit to having both and I presume they exist for historical reasons.

**Comment by Kartstig** [comment]
@TD5 to further support your example/assumption being correct, the [docs](https://www.erlang.org/doc/reference_manual/typespec.html) even state this:

![image](https://user-images.githubusercontent.com/2031422/193416234-f52f2a8b-cf2d-45ac-9b6b-68d9b4db4c32.png)

I don't consciously use `any()`, but after a quick search of code I've written, I found a usage where `term()` was also used in the same spec :sweat_smile: 

I think `_` should be kept only because of how natural it feels going from actual code to type specification, but I can see:
1. Sticking to `any()` and removing `term()` because consistency across languages
2. Sticking to `term()` and removing `any()` because it's been around longer and feels like the term is more widely adopted by Erlang and articles written around this, right?
3. Keep both? :shrug:

**Comment by mikpe** [comment]
I'll just add my SEK 0.02:

* I tend to use `any()` where any value is permitted, and the code doesn't inspect its structure (the values are just pass-though); think of it as the analogue of `'a` in Standard ML. For example, in container ADTs.
* I tend to use `term()` where any value is permitted, and the code does inspect its structure, at least partially; think of it as the `dynamic` type sometimes proposed for statically-typed languages. For example, in term-to-something-else converters.

So I think they should both remain.
