### ISSUE TITLE
Setting the fullsweep_after = 0 process flag in ssl_gen_statem

### ISSUE THREAD

**Issue by jbevemyr** [erlang/otp#6424]
**Is your feature request related to a problem? Please describe.**
We are seeing some issues with lingering garbage in ssl connections. Triggering a gc will reduce it. We experimented with setting `process_flag(fullsweep_after,0)` in the init function in `ssl_gen_statem.erl` with good results. 
What are your thoughts on this? Do you see an issue with this? Would it be a good idea to always do this in the library?
Our application appears to become both faster and user considerably less memory with this flag set in that module.

**Comment by dgud** [comment]
You could test with hibernate flag instead, since that will take care of connections without any traffic also.

`process_flag(fullsweep_after,0)`  may cause more latency for some applications so I don't think we want that,
at least not as default.

But an explicit **gc** after the handshake is done could be useful, we have also talked about looking into 
removing data from the state that is not needed after the handshake (don't know if that is possible yet).

**Comment by jbevemyr** [comment]
Thanks, I'll give hibernate a try.

**Comment by jbevemyr** [comment]
`{hibernate_after, 10000}` in the options to `gen_statem:enter_loop/4` in `tls_connection `and `tls_connection_1_3 `worked like a sharm in my application (at least so far).

**Comment by dgud** [comment]
I don't know if you noticed, there is an SSL option {hibernate_after, N} so you don't need to patch ssl.

**Comment by jbevemyr** [comment]
Even better! Thanks!
