### ISSUE TITLE
file:read_file returns {error, enoent} for existing file

### ISSUE THREAD

**Issue by ironaimer** [erlang/otp#6428]
**Describe the bug**
file:read_file returns {error, enoent} for existing file

**To Reproduce**
Steps to reproduce the behavior.
Our Elixir application calls JOSE.JWK.from_pem_file() (from erlang_jose project) which in turn calls OTP file:read_file(File).
File exists in the filesystem. Then the logic is called several times in row (up to 40-50) file:read_file returns {error, enoent} for existing file although previous and next call of file:read_file works OK.

**Expected behavior**
file:read_file should not return {error, enoent} for existing file.

**Affected versions**
OTP 23.0
Ubuntu 20.04

**Additional context**
Given callstack (shortened):
`(FunctionClauseError) no function clause matching in JOSE.JWK.from_record/1\n (jose 1.11.1) lib/jose/jwk.ex:30: JOSE.JWK.from_record({:error, :enoent})`

**Comment by lukebakken** [comment]
Can you provide a concise set of code that reproduces this issue? You're asking the Erlang/OTP maintainers to guess how to reproduce this issue, rather than spend time diagnosing it.

**Comment by ironaimer** [comment]
Sorry for confusing! I thought it is quite straight-forward but let me provide more details.
There is an Elixir code (application). There is relative path to file on the filesystem like "folder/file".
The code looks like:
...
result = get_file_path()
      |> JOSE.JWK.from_pem_file()
...

Sometimes during a consequent call (e.g. 100 times in row) this code triggers:
`(FunctionClauseError) no function clause matching in JOSE.JWK.from_record/1\n (jose 1.11.1) lib/jose/jwk.ex:30: JOSE.JWK.from_record({:error, :enoent})`

It happens because file:read_file("path/file") called by JOSE.JWK.from_pem_file() returns {error, enoent} for existing file.

**Comment by okeuday** [comment]
@ironaimer The issue is better if it has a link to the `JOSE.JWK.from_pem_file() ` source code.  The problem could be related to unreliable NFS use or a hard disk that is starting to fail.  To avoid those problems, you could test with a ram disk.

**Comment by lukebakken** [comment]
> I thought it is quite straight-forward but let me provide more details

It is straight forward that you think the issue lies in `file:read_file/1`. However, it is _extremely unlikely_ that an important, long-standing API method within Erlang/OTP has a bug. Much more likely, as @okeuday points out, you have an issue in your environment. This is why it is *your* obligation to provide steps or to reliably reproduce this issue. You can't expect the Erlang/OTP maintainers to come up with ways to try to reproduce your issue when you have in essence given no information for how to do so.

@ironaimer based on your description [this](https://github.com/potatosalad/erlang-jose/blob/main/src/jwk/jose_jwk.erl#L477-L495) is the location of the error. You should answer the following questions:
* Is your application running in a cloud environment?
* What is the storage layer where your `.pem` files reside? Is it directly attached, SAN, NFS, etc?
* Have you _always_ experienced this issue or did your application run successfully for a period of time before this issue started?

**Comment by ironaimer** [comment]
@okeuday @lukebakken thanks for ideas and additional questions!
Let me try to elaborate:
The application runs on the local machine with Ubuntu 20.04.
The storage layer is local SSD.
The fault is reproduced from time to time e.g. 1 time of 50 cyclic run the mentioned code. But the iteration before and after are OK.

My assumption (not sure how worth it is) is it might be related to relative path usage. I'll try to test with absolute path then.

**Comment by lukebakken** [comment]
@ironaimer it's important for you to answer this question:

> Have you always experienced this issue or did your application run successfully for a period of time before this issue started?

Which of these statements is true -

* Your application ran _without any issue_ for a period of time, _then_ starting exhibiting this intermittent issue
* Your application has _always_ exhibited this intermittent issue

You should also try to reproduce this issue using the latest version of Erlang/OTP - 25.1.2

Please run the `dmesg -t` command and *attach* the output to your response. I want to see if the kernel is reporting any disk issues.

**Comment by jhogberg** [comment]
Our file handling code never returns `ENOENT` by itself, so it must've been one of the underlying APIs that did it, i.e. `open(2)` and `stat(2)`. While it's possible that we could pass garbage to these functions, it's rather unlikely that we would do so intermittently.

Can you please answer @lukebakken's questions?
