### ISSUE TITLE
Read out ssl cipher from client hello

### ISSUE THREAD

**Issue by cwmichi** [erlang/otp#6554]
Hello together,

i used "lib/ssl/src/ssl_connection.hrl" from OTP 24.3.4 to read out the client ciphers and to decide if I want to use the ciphers or the ssl certificate for the connection.

%% Ext handling
hello,                %%:: #client_hello{} | #server_hello{}      

But since OTP 24.3.4.1 " hello "was commented out, how is it now possible to read out the client ciphers from the ssl connection?

Best regards
Michael

**Comment by IngelaAndin** [comment]
I do not understand why you would use an internal header file in your application. We have not changed the API we just changed how we handle some information internally! You can use the **hello** option to pause the handshake and inspect hello extensions to make choices in what options (certs ) etc you want for the connection.

**Comment by obi458** [comment]
We did the same. 
The idea is: If the client cipher is psk only ciphers, like ?TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 then
we change to psk otherwise we keep on cert for this connection.
I can not see clientcerts in hello extensions! How to get it?

Example code:

handshake hello
...
#sslsocket{pid=[Pid|_]} = Hs,
{user_hello, #state{handshake_env=HandshakeEnv}} = sys:get_state(Pid),
#handshake_env{hello=ClientHello} = HandshakeEnv,
#client_hello{client_version=_Version, cipher_suites=ClientCipherSuites} = ClientHello,
PskSuites = [?TLS_DHE_PSK_WITH_AES_256_GCM_SHA384],
case ClientCipherSuites -- PskSuites of
          ClientCipherSuites ->
		handshake_continue_with_cert({Hs});
	_ ->
		handshake_continue_with_psk({Hs})
end;

....

**Comment by IngelaAndin** [comment]
I think you should be able to achieve that by setting the option to honor the server cipher suite order and configure supported PSK ciphers to be first in the servers list.  And anyhow if there would be a need for more information in an API function you should request an API addition instead of relying on internal things that you happen to find in the code, as they might be changed for several reasons at any time to work differently.

**Comment by obi458** [comment]
...by setting the option to honor the server cipher suite order and configure supported PSK ciphers to be first in the servers list.
Works perfect :-)
Thanks
