### ISSUE TITLE
Clarifying the scoping rules of try/of/catch/after

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6598]
Looking at https://www.erlang.org/doc/reference_manual/expressions.html#try, I've not found a description of the rules for scoping of variables in that language construct.

Here is what I've found empirically by giving small testcases to erlc:
- variables bound in the expressions just after `try` are:
  - bound in the `of` cases
  - unsafe in the `catch` and `after` cases, as well as after the whole construct
- variables bound in the `of` section are:
  - unbound in the `catch` section
  - unsafe in the `after` section, as well as after the whole construct
- variables bound in the `catch` section are:
  - unsafe in the `after` section, as well as after the whole construct
- variables bound in the `after` section are:
  - unsafe after the whole construct

Before sending a PR adding this information to the documentation, I would like to make sure that this is all working as intended.
In particular, the following two points are surprising to me:
- variables bound in the`of` section can be re-bound in the  `catch` section, whereas I would have expected them to be unsafe by consistency with all the other cases.
- variables bound in the `after` section cannot be used after it, despite being guaranteed to have been initialized.

**Comment by bjorng** [comment]
I would say that the semantics is intentional. At least, we have no plans to change it.

> variables bound in the `of` section can be re-bound in the  `catch` section, whereas I would have expected them to be unsafe by consistency with all the other cases.

If the `catch` section has been reached, none of the clauses in the `of` section could have been executed, so those variables can never be bound. There is no reason for them to be considered unsafe.

> variables bound in the `after` section cannot be used after it, despite being guaranteed to have been initialized.

It was a long time ago `try` ... `catch` was introduced (in Erlang/OTP R7, I think), but as I remember it, it was our intention that it should be possible use the variables after the `after` section. We wanted to implement that in a later release, but it turned out to be trickier to do than we anticipated and it was never implemented.

**Comment by RobinMorisset** [comment]
Thank you for the explanation, it makes sense.
