### ISSUE TITLE
[vm] Different stacktraces for exceptions between jit and emu flavors

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#6697]
**Describe the bug**
About the following code:
```erlang
f(X) ->
    X - 0.

wrapper() ->
    io:write(catch f(ok)).
```
Running it with `--emu_flavor emu` results in the following output:
```
{'EXIT',{badarith,[{jit326,f,1,[{file,[109,105,110,105,109,105,122,101,100,47,106,105,116,51,50,54,46,101,114,108]},{line,12}]},{jit326,wrapper,0,[{file,[109,105,110,105,109,105,122,101,100,47,106,105,116,51,50,54,46,101,114,108]},{line,15}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
```
Whereas running it with `--emu_flavor jit` results in the following:
```
{'EXIT',{badarith,[{erlang,'-',[ok,0],[{error_info,#{module => erl_erts_errors}}]},{jit326,f,1,[{file,[109,105,110,105,109,105,122,101,100,47,106,105,116,51,50,54,46,101,114,108]},{line,12}]},{jit326,wrapper,0,[{file,[109,105,110,105,109,105,122,101,100,47,106,105,116,51,50,54,46,101,114,108]},{line,15}]},{init,start_em,1,[]},{init,do_boot,3,[]}]}}
```
Note that the latter has one extra element on its stack trace, corresponding to the `-` operator.

**Expected behavior**
I'd naively expect the jit/no-jit toggle to have no impact on the output of the VM.
It might be expected though, in which case please close and ignore this issue.

**Affected versions**
master

**Additional context**
Inlining `f` makes the discrepancy disappear.

**Comment by jhogberg** [comment]
Thanks for your report, this is (sort of?) on purpose.

A long time ago someone made the decision not to keep track of arguments or even specific operation in most `badarith` exceptions, I'm guessing because they didn't think it was worth the (slight) performance hit in the interpreter.

However, there's no reason to discard this information in the JIT other than trying to be quirks-compliant, so we kept it around.
