### ISSUE TITLE
subject/verb clashes in man page for the code module

### ISSUE THREAD

**Issue by RichMorin** [erlang/otp#6709]
There are some subject/verb clashes in the man page for the code module
(https://www.erlang.org/doc/man/code.html). The lib_dir entry contains the text:

> ... at least partly resides in ... while other reside in ...

This should be edited to:

> ... at least partly reside in ... while others reside in ...

**Comment by bjorng** [comment]
Thanks! Fixed.

**Comment by RichMorin** [comment]
Thanks for the prompt action. I would have submitted this as  patch, but after a fair amount of looking around, I still hadn't managed to find the source file (sigh).

**Comment by paulo-ferraz-oliveira** [comment]
@RichMorin, when you're reading the documentation, you'll find e.g. alongside a function definition (as shown in the attached image), a pencil. Pressing it will prompt you to a pull request (as in [this example](https://github.com/erlang/otp/edit/maint/lib/kernel/doc/src/code.xml#L362)). 😄 

Any pencil in the doc. should do, since the whole file is made available for the pull request.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/7303768/213568320-233c5ee0-725f-4d7b-b58f-6239fa53a99a.png">

**Comment by RichMorin** [comment]
Thanks for the hint!
That said, editing XML by hand may not be everyone's cup of tea...

-r

**Comment by paulo-ferraz-oliveira** [comment]
Yeah, for bigger changes maybe not, but for small English-related stuff I guess it's Ok.
