### ISSUE TITLE
Timer improvements

### ISSUE THREAD

**Issue by manuel-rubio** [erlang/otp#6722]
This ticket isn't covering a request/bug, it's a proposal I'll use to refer to different pull requests (PR) I'll be opening for improving the timer implementation from the observability point of view.

## Rationale

After checking some solutions for providing cron tasks in Erlang (and Elixir) I just recognise that most of them are always doing stuff on top of `:timer` because it's not enough, it's missing some features to make it possible to use it completely as an easy solution for cron tasks, from my point of view, I think these features are missing:

- **Monitoring**: we have functions like `inet:i/0`, `ets:i/0`, `i/0`, ... to get information about network connections, ETS tables, and processes, ... but not for timers. And it could be great to know the number of timers we have running, the time until they will be triggered, the type of the timer (once, interval, repeatedly), and what's triggering (MFA or function).
- **Naming**: even if we have the possibility to know or see the timer, that's under a reference and it's cumbersome to get that reference in some other places linked to a name, I think it could be great to have a naming service similar to `register/2` and `unregister/2` that's giving us the timers.

In addition, a new tab for timers' information inside of the observer application where we could navigate the active timers and the information they have.

**Comment by rickard-green** [comment]
As I wrote in #6720 "It *could* perhaps be interesting the get overall information about amount of BIF timers used or similar, though, but we see no need to expose all details of all timers for that" apply also here. This is however not something that we've seen as especially important, so it is not something that we will implement.

We do not want a naming service for the same reason we do not want to expose the references of all BIF timers in #6720. The timer should only be operated on by those that have been explicitly passed the reference to the timer. Other uses will typically only cause problems.

The `timer` module never had the intention to provide cron functionality and would need a lot of new functionality in order to provide such a service. Such a service is typically implemented using other primitives, for example, BIF timers monitoring of time offset, etc.
