### ISSUE TITLE
TUPLE0 used but not defined

### ISSUE THREAD

**Issue by manuel-rubio** [erlang/otp#6723]
**Describe the bug**
In the file `erts/emulator/beam/erl_term.h` line ~1277 appears the following code:
```c
#define MAP0(hp)                                                \
    (MAP_HEADER(hp, 0, TUPLE0(hp+MAP_HEADER_FLATMAP_SZ)),       \
     make_flatmap(hp))
```
But `TUPLE0` isn't defined anywhere.

**To Reproduce**
No steps are needed.

**Expected behavior**
Looks like `MAP0` isn't in use, I guess it could be removed or `TUPLE0` could be implemented.

**Affected versions**
Currently in `master`.

**Additional context**
(None)

**Comment by mikpe** [comment]
`TUPLE0` was deliberately removed. `MAP0` is dead code and should be deleted (along with `MAP0_SZ`).

**Comment by manuel-rubio** [comment]
@mikpe I used both here #6720 but I guess it could be easy change it for something different.

**Comment by jhogberg** [comment]
Thanks for spotting this! `TUPLE0` was replaced with a global empty tuple literal in order to guarantee that all boxed terms have at least one word past the header, which lets us simplify things like fun dispatch. I'm guessing we simply missed the use in `MAP0` because it wasn't used itself.

Feel free to make a PR that removes `MAP0`. :-)

**Comment by sverker** [comment]
As @mikpe said, `TUPLE0` was deliberately removed. It's handled specially and exists as a singleton literal `ERTS_GLOBAL_LIT_EMPTY_TUPLE`. The reason is that it's the only term consisting of only one heap word and we make optimizing assumptions that at least two words can be read.
