### ISSUE TITLE
Diameter: the IP of transport is not resolved by default

### ISSUE THREAD

**Issue by vkatsuba** [erlang/otp#6765]
**Problem**
There was a host. Resolved it, got an IP and added to transport connect. Connected and everything was fine. After a while the connections dropped by reason that host changed IP for some reason - as result transport will continue to use the old IP until the loss of pulse or till time when transport will be removed by API call(and it's not clear where to call it if pool_size > 1).

**Possible of solution**
Provide the ability to transfer the host instead of IP to transport options for make resolving IP by default if IP of host will changed.

**Alternatives considered**
* In Diameter service, provide a handler for up/down/reconnect events and provide a custom check if IP was changed or not by given host.
* Provide external API for add/remove transports if IP was changed.

**Additional context**
Not sure if this can be issue or maybe OTP team already have some strong vision why IP cannot be resolved by given host - but the current issue is causing custom changes to the default diameter logic which can lead to more serious problems.

**Comment by vkatsuba** [comment]
@otp-anders thanks for reply! Maybe I describe the issue confusingly a little bit  - sorry for it. Your suggestion, if I got your point correct, is that - try resolve host in some place. The similar approach is already described in ticket. The main reason of creating this ticket was discuss/ask/propose the point that - for resolving hosts in Diameter application when server/client will down and will change the IP when will UP - provide automation resolving hosts without any custom changes from user/developer side. Fo course if this is possible at all. Maybe you can propose some solution approach for make changes in current implementation of adding transports or in Diameter application it self for fix/improve this ticket?

**Comment by otp-anders** [comment]
It's not possible for diameter to resolve hosts before calling a transport module without significant changes since it has no idea how an arbitrary transport module should be called. The diameter user configures {transport_module, Mod} and {transport_config, Config} in a call to diameter:add_transport/2, and diameter just takes these and calls Mod:start/3 with Config as third argument. It has no idea what Config is, so even if there is a hostname in it, diameter has no idea how to find if and how it should it should call Mod:start/3 with an IP address instead. It's purposely oblivious to how that transport process is started other than that Mod:start/3 is the function to call with the user's transport_config.

All you need to do is implement a transport module of your own to resolve the hostname. For example, if you want to use diameter_tcp or diameter_sctp to connect to a peer then something like this would map hostname-valued raddr options to IP addresses:

```
-module(my_transport_module).

-export([start/3]).

-include_lib("kernel/include/inet.hrl").

%% start/3

start(T, Svc, [Mod | Opts]) ->
    Mod:start(T, Svc, lists:flatmap(fun(X) -> map(Mod, X) end, Opts)).

%% map/2

map(Mod, {raddr = K, Hostname}) ->
    {ok, #hostent{h_addr_list = Addrs}} = inet:gethostbyname(Hostname),
    case Mod of
        diameter_tcp ->
            [{K, hd(Addrs)}];         %% use the first address
        diameter_sctp ->
            [{K, A} || A <- Addrs]    %% use them all
    end;

map(_, T) ->
    [T].
````

Make my_transport_mod as smart or dumb as you want. You can then configure your transports something like this:

```
{ok, TRef} = diameter:add_transport(Svc, [{transport_mod, my_transport_mod},
                                          {transport_config, [diameter_tcp | Opts]}
                                          | Config]),
```

That's it: hostnames will be resolved each time diameter calls the start function. You have to implement the transport module to do the address lookup, but it's not much code. The case of diameter_tcp/sctp could be handled in the diameter application by giving those modules the ability to resolve hostnames, but then gen_tcp/sctp could do it for any protocol, not just Diameter. As is, both deal with IP addresses, and if you want to use hostnames then you need something like my_transport_module.

**Comment by vkatsuba** [comment]
@otp-anders many thanks for reply. You describe in details what you commented before. I was think maybe in updating of `diameter_tcp`/`diameter_sctp` transport modules in the Diameter application without any custom implementation. I suppose we can close this ticket. Thanks for your time!
