### ISSUE TITLE
The compiler can generate unsafe code for binary append

### ISSUE THREAD

**Issue by bjorng** [erlang/otp#6851]
**Describe the bug**
The compiler generates unsafe for some binary append operations, which can cause the runtime system to crash.

**To Reproduce**
Given the following module:

```
-module(private_append_crash).
-compile([export_all, nowarn_export_all]).

start() ->
    unsafe_private_append(not_ok).

unsafe_private_append(X) ->
    <<(case ok of
           X -> <<>>;
           _ -> ok
       end)/bytes>>.
```

Compile and execute it:

```
1> c(private_append_crash).
{ok,private_append_crash}
2> private_append_crash:start().
zsh: segmentation fault  bin/erl
```

**Expected behavior**
There should be an exception when the code is executed:

```
1> c(private_append_crash).
{ok,private_append_crash}
2> private_append_crash:start().
** exception error: construction of binary failed
     in function  private_append_crash:unsafe_private_append/1 (private_append_crash.erl, line 8)
        *** segment 1 of type 'binary': expected a binary but got: ok
```

**Affected versions**
The current `master` branch.

**Additional context**
The compiler should not rewrite the `append` sub instruction of `bs_create_bin` instruction to `private_append` when its argument can be something other than a bitstring. (`private_append` assumes that its argument is a bitstring, and will crash if given some other term.)

**Comment by frej** [comment]
We can quite easily avoid this by simply forbidding the transformation when  the compiler can't prove that the type is and only is a bitstring.

I have pushed a fix in e5d27daaf3f5f974aca8eeffa6e9ffd9b62aeadc.

A drawback with the fix is that the optimization isn't applied in some cases like the one below:

```Erlang
-module(foo).

-export([transformable22/1]).

transformable22(L) ->
    transformable22(L, [<<>>|<<>>]).

transformable22([H|T], [AccA|AccB]) ->
    transformable22(T, [<<AccA/binary, H:8>>|<<AccB/binary, 17:8>>]);
transformable22([], Acc) ->
    Acc.
```
Here the type analysis determines that the type of the of the cons tail is `nonempty_improper_list(bitstring(8,appendable), bitstring(8,appendable)) | bitstring(8,appendable)` although it is actually `bitstring(8,appendable)`.

Is this something we should care about? We could add a flag to private_append which tells the runtime to check the type of the first argument. The flag would be set by the compiler when the type can't be guaranteed to only be a bitstring (@bjorng this was probably what we tried to recall when we talked about runtime support last week).

**Comment by frej** [comment]
I will deal with the dead code in `beam_ssa_private_append.erl` this fix leaves until there is a decision on whether we should add a type-checking version of  private_append to the runtime system. The same for beam-verifier support.

**Comment by bjorng** [comment]
I find it unlikely that code similar to your example is used in practice. Dialyzer would by default complain about using improper lists and most developers would tend to use a tuple or a record anyway. For example:

```
transformable22(L) ->
    transformable22(L, {<<>>, <<>>}).

transformable22([H|T], {AccA, AccB}) ->
    transformable22(T, {<<AccA/binary, H:8>>, <<AccB/binary, 17:8>>});
transformable22([], Acc) ->
    Acc.
```

Another natural way to write this (which doesn't build any garbage) is to use separate arguments for the accumulators:

```
transformable22(L) ->
    transformable22(L, <<>>, <<>>).

transformable22([H|T], AccA, AccB) ->
    transformable22(T, <<AccA/binary, H:8>>, <<AccB/binary, 17:8>>);
transformable22([], AccA, AccB) ->
    {AccA,AccB}.
```

Both of those are optimized.

Therefore, I don't think that the effort of adding a new version of `private_append` is worth it, and we should not do it.

**Comment by frej** [comment]
Agreed, I'll revise the patch fixing #6855 and change some of the test cases from being xfail to check that we don't try transform the cons-case.
