### ISSUE TITLE
Open external editor fails to return edited text to shell with from external windows

### ISSUE THREAD

**Issue by rowlandcodes** [erlang/otp#6867]
**Describe the bug**
Opening an external editor in another window doesn't send the text from the shell to the editor,
And it doesn't return the text from the editor to the shell. 

Sometimes, with `EDITOR="gnome-terminal -- vim" erl`,
I am able to see the text from the shell,
But I have an error:
```
E211: File "/tmp/tmp.8zYKpbYo9B.erl" no longer available
```
Saving this errored file doesn't return the text to the editor.

**To Reproduce**
Run:
```
EDITOR=code erl
```
Type some text,
And invoke `C-o`.

The exact same problem occurs with a terminal editor opened in a new terminal:
```
EDITOR="gnome-terminal -- kak" erl
# and
EDITOR="gnome-terminal -- vim" erl
```

**Expected behavior**
The text from the shell should appear in the editor,
And return to the shell after saving and closing that file.

**Affected versions**
OTP 26.0-rc1

**Additional context**
This issues were found on Ubuntu 22.04.1 LTS

**Comment by frazze-jobb** [comment]
On Ubuntu 20.04:
If I run `EDITOR="code -w" erl` write something and open external editor with `C-o` its working as expected. The problem is that we expect the EDITOR process to return something before we update the prompt. If you start code without "-w" then vscode will just return immediately and the temporary file will be read and removed before you are able to edit it.
Similarly if you start it with `gnome-terminal -- vim` then the _gnome-terminal instance_ will return something and fork itself to the background.
To start a gnome-terminal window that waits until the process exists you can write `EDITOR="gnome-terminal --wait -- vim" erl`.

**Comment by frazze-jobb** [comment]
The open_editor function has been documented to require that a flag corresponding to --wait needs to be specified for it to work.
