### ISSUE TITLE
Erlang Windows executable is not digitally signed 

### ISSUE THREAD

**Issue by ophirzk** [erlang/otp#6885]
**Describe the bug**
erl.exe and all other executables in Erlang's installation dir are not digitally signed.

**To Reproduce**
Install Erlang.

**Expected behavior**
erl.exe and all other executables in Erlang's installation dir are digitally signed.

**Affected versions**
13.0.4
Maybe all others.

**Additional context**
Erlang installation exe, otp_win64.exe, is signed by Ericsson AB. But the content it installs is not signed.

**Comment by KennethL** [comment]
I don't know why you call this a bug? The installer is signed. Why do you think the files installed by the installer must be signed as well?

I am not an expert in this area, but if you have more info and can explain how you think this can be done, please do so.

**Comment by ophirzk** [comment]
How is signing only the installer will be useful to any user who cares about running only digitally signed applications? Any EDR configured to block unsigned applications will immediately block Erlang after the installation. So what is the point in signing only the installer? How will it work in a real-life scenario? The user will be able to install Erlang but not to run it?

**Comment by KennethL** [comment]
I don't know anything about what "EDR configured" on Window means and I assume it is Windows specific.
By installing everything with signed installers you should be safe to only have SW from trusted sources. If you install individual executables you will need them signed as well, but we don't provide any individual executables, they are always bundled into the signed installer. This is the first time I heard about problems to run Erlang because `.exe` files are not signed.

**Comment by ophirzk** [comment]
I need to clarify a few things.

1. I am not talking about installing an individual executable of course. 
2. You can't trust anything that runs in your system because a signed installer installed it. That is because after it was installed, you still need to monitor what is running in your system. Most of the malicious applications have the same name as known dlls/exe because of that reason, so you won't suspect something malicious is running in your system. It is the most known practice of viruses and it is the main point in signing. The only thing that saves you is the digital signature. That is the reason the dlls in your machine are signed.
3. EDR means - endpoint detection and response it has nothing to do with Windows.
4. I didn't say you can't technically run Erlang if it is not signed. The problem is that it is not signed and therefore no one really knows what really runs, the original Erlang that was installed using the signed installer, or malicious software that in order to "impersonate" Erlang, called itself erl.exe like most of the viruses.
5. You probably didn't hear about this issue because not every user of Erlang is willing to share such information with you because they might expose sensitive information about how their system detects threats. Some of them are dropping Erlang technology because of this reason.

**Comment by ophirzk** [comment]
I am browsing now from my Chrome browser which was signed by Google. I would not let an unsigned Chrome browser run on my machine (and I think you wouldn't either). Google signed Chrome exe, not only the installer for the obvious reason that there might be thousands of viruses that pretend to be Chrome. Same thing for every other application you ever installed from a reliable source. If you see for instance that something called word.exe is running in your machine and it is not signed, I would not recommend you run it, because it is not Microsoft Word for sure. And the only way you can know that you are running Word is the digital signature, not the name "word.exe".

**Comment by michalmuskala** [comment]
TBH I'd expect most security-sensitive companies compiling programming language runtimes on their own and using their internal systems to verify integrity. Especially for completely open-source projects, like Erlang. I'd expect that's primary reason this haven't come up before.
The reason word or chrome have to be signed to be verified is that they're closed source, so you can't compile them yourself.

**Comment by ophirzk** [comment]
@michalmuskala 

The fact that Chrome or Microsoft Word are closed sources has nothing to do with being or not being able to sign them or the fact that they are signed. Signing is done after compilation. You can sign things you didn't build, so it is not related if you can or can't build something. The exe or the dll that was compiled doesn't know whether it is an open source or a closed source. In both cases, people can download an MSI that installs, either an open source or a closed source application, Erlang or Chrome, and they don't care if it is an open source or not. In both cases, even if it was a close source and unsigned, they could have signed it the **exact ** same way they would sign an open source they built.

Regarding security-sensitive companies that are building their own runtimes:
1. Again, signing and building have nothing to do with each other. In many cases, it is not even the company that builds is the one that is signing it.
2. Maintaining builds, automation etc.. for Erlang is not something most companies would want to do. It requires staff and expertise. 

And lastly, with all that being said, what is the point then in signing the installer? From your comment, it sounds like you are saying "Everyone who cares about security (almost everyone), should build their own Erlang", in addition to that it was said here "we already sign the installer" and you don't tell people "build your own installer if you care about security".

**Comment by KennethL** [comment]
> I need to clarify a few things.
> 
> 1. I am not talking about installing an individual executable of course.
> 2. You can't trust anything that runs in your system because a signed installer installed it. That is because after it was installed, you still need to monitor what is running in your system. Most of the malicious applications have the same name as known dlls/exe because of that reason, so you won't suspect something malicious is running in your system. It is the most known practice of viruses and it is the main point in signing. The only thing that saves you is the digital signature. That is the reason the dlls in your machine are signed.
> 3. EDR means - endpoint detection and response it has nothing to do with Windows. I think this works differently for each OS even if the definition of EDR is generic.
> 4. I didn't say you can't technically run Erlang if it is not signed. The problem is that it is not signed and therefore no one really knows what really runs, the original Erlang that was installed using the signed installer, or malicious software that in order to "impersonate" Erlang, called itself erl.exe like most of the viruses.
> 5. You probably didn't hear about this issue because not every user of Erlang is willing to share such information with you because they might expose sensitive information about how their system detects threats. Some of them are dropping Erlang technology because of this reason.

I understand your argumentation about signed executables, But a signed installer is still useful since it makes Windows happy when you are downloading and installing. And if you only allow new software to be installed via signed installers you should be somewhat safe.

But I have nothing against signed executables it is only a question about who is doing the signing and when. Since we the OTP team only deliver pre-built binaries for Windows and for all other platforms the users have to build themselves from source it is not up to us to sign the SW. It is also common practice that users build their own releases with tools provided in OTP and `rebar3`for example. It would then be natural if the code signing took place during make of a release. Possibly that could need new support in the tools used for making a release.

By the way , do you have pointers to how other Open Source languages are handling code signing in a "good way".

**Comment by ophirzk** [comment]
@KennethL 
Why is rebar3 related or the fact that everyone builds their own Erlang modules/applications? I was referring to the Erlang executable only (I created another thread about signing Erlang module which is not related to this thread).

1. Can the executable be signed the same way the installer is signed? 
2. Who compiles the Erlang executable that is delivered via the OTP installer?

**Comment by KennethL** [comment]
@ophirzk: some answers to your questions:
1. Yes the executable can be signed the same way as the installer. We will probably start signing all .exe and .dll files in the upcoming releases possibly already in OTP 25.3 next week and if not there it will happen in OTP 26.0 scheduled for release in May. We have tested this and it seems to work well.
2. We are compiling the `erl` and all other executables included in the installer. I don't think it makes sense that we sign something where we have no control over the build as well.

Rebar3 is related since this is a tool where users can create their own releases containing executable binaries from OTP as well as their own executables.
It is also related to your other issue where you suggest that Erlang modules (.beam files) should or could be signed as well. This since rebar3 is the most common tool for putting together executables and .beam files from OTP and from the user(s) into one installable product.

As we are only delivering Erlang/OTP as a binary for the Windows platform we have done the signing of executables there. For other platforms it is up to the ones providing pre-built binaries.

**Comment by ophirzk** [comment]
@KennethL
Sounds great.
When is 25.3 is expected to be released?

**Comment by KennethL** [comment]
@ophirzk 
It is very probable that we will have signed executables in the Windows installer beginning with the OTP 25.3 release.
The plan is to release 25.3 the coming Wednesday (March 8:th).

**Comment by ophirzk** [comment]
@KennethL 
There are other exe in the Erlang folder, for instance, start_erl.exe, rl_call.exe and more.

Can they be signed in this process as well?

**Comment by KennethL** [comment]
As from OTP 25.3 all .exe and .dll files inside the Windows installer are signed in the same way as the installer itself.
There is one exception and that is the Uninstall.exe which is created by NSIS (the utility used to build the installer), because it is
not available when we do the signing. This might get fixed as soon as we have a good solution. See #7002
