### ISSUE TITLE
Compiler directives via `-compile` do not take precedence.

### ISSUE THREAD

**Issue by robertoaloi** [erlang/otp#6979]
**Describe the bug**

It is possible to customize the compiler options for a module via the `-compiler` attribute. As an example, one can decide to warn about missing specs (default behaviour is not to) using the `warn_missing_spec` option:

```
-module(test).
-compile([warn_missing_spec]).
-export([test/0]).
test() ->
    ok.
```

```
erlc test.erl
test.erl:7:1: Warning: missing specification for function test/0
%    7| test() ->
%     | ^
```

Unfortunately, these options seem to be applied *after* the global ones, so the following example does not work as expected:

```
-module(test).
-compile([nowarn_missing_spec]).
-export([test/0]).
test() ->
    ok.
```

```
erlc +warn_missing_spec test.erl
test.erl:7:1: Warning: missing specification for function test/0
%    7| test() ->
%     | ^
```

**Expected behavior**

I expect no warnings about missing spec to be produced for the `test` module, containing the `nowarn_missing_spec` directive.

**Affected versions**

Reproduced on Erlang/OTP 25 [erts-13.0.3].

**Comment by ilya-klyuchnikov** [comment]
`-compile(warn_missing_spec).` works just fine.

**Comment by robertoaloi** [comment]
> `-compile(warn_missing_spec).` works just fine.

Yes, that is equivalent to the first case above, where the override mechanism works as expected. What does not work is the case where you override the default behaviour via CLI and then try to apply a local override for a module.

The variant of the attribute where an atom is used instead of a list suffers exactly the same problem.

**Comment by michalmuskala** [comment]
This seems to be quite confusing.

Looking at the code in `compile` it [appends the options from the environment](https://github.com/erlang/otp/blob/dce09cbe5a2efe674a76ef2d4dd392c522e29bf1/lib/compiler/src/compile.erl#L96) to the list of options passed to `compile:file`, and [prepends the options from `-compile` attributes](https://github.com/erlang/otp/blob/dce09cbe5a2efe674a76ef2d4dd392c522e29bf1/lib/compiler/src/compile.erl#L1511).

However, looking at `erl_lint` it seems to always take the last option from the list (since it folds over the entire list): https://github.com/erlang/otp/blob/dce09cbe5a2efe674a76ef2d4dd392c522e29bf1/lib/stdlib/src/erl_lint.erl#L54-L58

I'm not really sure what a proper fix would be - changing the order options are combined in `compile`, or changing the order how they are read in `erl_lint`.
Changing `erl_lint` seems appealing since it would also made it more efficient - traversing options only until first is found.

On the other hand, it would make it impossible to override in-file options with the env variable which might be desirable in some scenarios to force builds (e.g. missing `no_auto_import`).

I'd be happy to fix this once it's clear how this should be handled.

**Comment by bjorng** [comment]
The linked pull request changes how options are appended. This is for OTP 27; I don't think we dare change in previous releases.
