### ISSUE TITLE
`socket:accept` throws `invalid` instead of returning it

### ISSUE THREAD

**Issue by digitalcora** [erlang/otp#7148]
**Describe the bug**

`socket:accept/2`, when given a `Timeout` value less than 0, _throws_ an `invalid` tuple rather than returning it as an error. Given the typespec says the function may return `{error, {invalid, Term}}`, and other `socket` functions do return such a value when given invalid arguments, this seems unintended.

**To reproduce**

```
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
Eshell V13.2  (abort with ^G)

1> {ok, S} = socket:open(inet, stream).
{ok,{'$socket',#Ref<0.2776640198.3165257732.250709>}}

2> ok = socket:listen(S).
ok

3> socket:accept(S, -1).
** exception error: {invalid,{timeout,-1}}
     in function  socket:accept/2 (socket.erl, line 1719)
```

**Expected behavior**

In this example I would expect the function to return `{error, {invalid, {timeout, -1}}}` instead of throwing.

**Affected versions:** 25.3

**Comment by RaimoNiskanen** [comment]
The value `-1` for argument 2 breaks the type specification, which is why we have chosen to raise an exception.  An `{invalid, Reason}` exception is intended to be more informative than just a `badarg` exception that doesn't point out any argument.

We try to draw the line between exceptions and error return values where the calling argument never could be correct.
For example: `socket:open(inet, stream, {})` throws an internal exception while `socket:open(inet, stream, not_a_protocol)` returns an error tuple.  This is not entirely consistent, but we intend to make it more so.  One problem here is, for example, that today the socket `domain()` can only be `inet | inet6 | local | unspec` today, but in a future release more values might be possible, so we do not want to throw an exception for every value that is not in that type.

So, `socket` may only throw an exception if the call breaks the type specification, but will not always do so.

**Comment by digitalcora** [comment]
Thanks very much for that clarification, makes sense.
