### ISSUE TITLE
[erlc] internal consistency check failed: ambiguous_catch_try_state

### ISSUE THREAD

**Issue by RobinMorisset** [erlang/otp#7180]
**Describe the bug**
Running erlc on the following:
```erlang
-module(test85993).
-compile([export_all]).

f() -> 
    0.0 = try erlang:binary_to_float(erlang:garbage_collect() orelse ((1.0 = erlang:tuple_to_list(ok)) -- ok))
after
ok
end.
```
results in the following error message:
```
test85993:1: function f/0+37:
  Internal consistency check failed - please report this bug.
  Instruction: {badmatch,{x,0}}
  Error:       ambiguous_catch_try_state:
```

**Affected versions**
- master
- master + #7172

**Additional context**
Extremely confusingly, improving the formatting - such as by adding a line return between `try` and `erlang:binary_to_float` - makes the bug disappear!

**Comment by bjorng** [comment]
Somewhat simplified, the `beam_jump` pass would rewrite the following BEAM code:

    {label,12}.
    {line,[{location,"t.erl",7}]}.
    {badmatch,{x,0}}.
    .
    .
    .
    {test,is_eq_exact,{f,15},[{x,0},{float,1.0}]}.
    .
    .
    .
    {label,15}.
    {line,[{location,"t.erl",7}]}.
    {badmatch,{x,0}}.

to:

    {label,12}.
    {jump,{f,15}}.
    .
    .
    .
    {test,is_eq_exact,{f,15},[{x,0},{float,1.0}]}.
    .
    .
    .
    {label,15}.
    {line,[{location,"t.erl",7}]}.
    {badmatch,{x,0}}.

in order to share the code for raising a `badmatch` exception (this optimization is more useful than it might seem, because it usually enables other control-flow optimizations).

In this particular case, this transformation happens to be unsafe.

If newlines are inserted, the `line` instructions will have different line numbers and the blocks after labels 12 and 15 are no longer identical and the code sharing will not happen.

**Comment by RobinMorisset** [comment]
Thanks for the explanation (and for the fix)!
