### ISSUE TITLE
ssl: tls_record_1_3:decipher_aead/6 returns decryption_failed

### ISSUE THREAD

**Issue by krant** [erlang/otp#7199]
Website https://www.shfe.com.cn looks valid for curl, openssl or a browser, but fails to establish TLS connection with Erlang/OTP:

```
$ erl -s inets -s ssl
1> httpc:request("https://www.shfe.com.cn/").
{error,{failed_connect,[{to_address,{"www.shfe.com.cn",443}},
                        {inet,[inet],
                              {tls_alert,{bad_record_mac,"TLS client: In state wait_ee at tls_record_1_3.erl:351 generated CLIENT ALERT: Fatal - Bad Record MAC\n decryption_failed"}}}]}}
```

Debug has shown the error happens at [this line](https://github.com/erlang/otp/blob/465720cf8b6f3c14ebca43c3ce852d135b86bdbe/lib/crypto/c_src/aead.c#L170).

**Affected versions**
OTP-25.3.1

**Comment by IngelaAndin** [comment]
This is not really a bug,  but maybe in the sense that we could change our handling slightly so that the error message become clearer.  The thing is that the server is not honoring the "middlebox-compatible-mode".

 `ssl:connect("www.shfe.com.cn", 443, [{verify, verify_none}, {middlebox_comp_mode, false}]).
`
will work. It is possible to supply this option already to the httpc-client, even if maybe a  little inconvenient. 

It has also been discussed to have  , {middlebox_comp_mode, relaxed} that does middlebox-mode but does not verify
that the server behaves correctly in sending the required change_cipher_spec messages in the correct places, that will however be ignored as they are there to fool the middelboxes to behave as they should.  This option could then be adopted by typical
web-clients  but we can still have other clients verify the protocol. Now this might seem not so important at the moment, but so have other thing done that later turned out to be security issues, so we like to be able to assert the intended protocol
behavior by default.

**Comment by krant** [comment]
That's a good news! Thanks for looking into it and for the solution. OTP TLS rocks!
