### ISSUE TITLE
TLS client: In state cipher received SERVER ALERT: Fatal - Certificate Unknown in OTP 26

### ISSUE THREAD

**Issue by hzeus** [erlang/otp#7264]
**Describe the bug**
After upgrading to OTP 26, we cannot establish a ssl connection to a server that requires a client certificate, instead we receive

```elixir
{:error,
 %HTTPoison.Error{
   reason: {:tls_alert,
    {:certificate_unknown,
     'TLS client: In state cipher received SERVER ALERT: Fatal - Certificate Unknown\n'}},
   id: nil
 }}
```

The error message is the same one that we received after the update to OTP 24.3 last year, so maybe this is a regression of https://github.com/erlang/otp/issues/5835 ?

**Affected versions**
* 26.0 is affected
* 26.0-rc3 is _not_ affected
(installed on Mac via `asdf`)

**Additional context**
The error happens when we are trying to connect to the same server as in https://github.com/erlang/otp/issues/5835 which was resolved in https://github.com/erlang/otp/pull/5919 . Please let me know if I can help with tracing / debugging.

**Comment by u3s** [comment]
Can you (similarly to #5835 ;-) ) use option {log_level, debug} for comparing the processing for both versions?

**Comment by hzeus** [comment]
Thanks for your quick response (again)!

I created two log files of the two versions and I try to summarize the differences I see in a diff tool. I can also send you the complete files if this helps (via Mail?), but I do not want to share them publicly as they contain our customer's name in the certificates.

The first thing I notice is that right at the beginning in the release candidate, our server sends two messages, but the final release only one (left side is the RC; and the additional message ends with `, protocol: :record, direction: :outbound]`)

<img width="1252" alt="Bildschirmfoto 2023-05-19 um 20 18 29" src="https://github.com/erlang/otp/assets/121394/85c02b77-f57f-48c3-95b3-64e99dc5a39e">

Still within the ClientHello I see some differences within extensions (again, left side is RC, right side the final release):

<img width="1244" alt="Bildschirmfoto 2023-05-19 um 20 19 59" src="https://github.com/erlang/otp/assets/121394/1c8ccabf-fb58-4581-b3e2-5d4b818f5868">


The next significant change seems to be directly after `Handshake, ServerHelloDone`, and the final release seems to send an empty list of certificates.

<img width="1266" alt="Bildschirmfoto 2023-05-19 um 20 23 10" src="https://github.com/erlang/otp/assets/121394/6d75b4be-d697-4e36-825e-89c863297eef">

I omitted some diffs in between, as I do not see any significant differences other than e.g. the session ID.

**Comment by IngelaAndin** [comment]
It would help if you could share the signature algorithm used by your client certificate. You do not need to share the whole certificate.
You can get the information by in an erlang shell (elexir shell works to with adjusted syntax):
` {ok, Pem} = file:read_file("yourcert.pem").  
[{_, DerCert, _}| _] =public_key:pem_decode(Pem). 
Cert = public_key:pkix_decode_cert(DerCert, otp).` 
Share appropriate part of last command with us.

**Comment by hzeus** [comment]
This is the output I get (the outputs are the same for the rc and the final version):

```
{'OTPCertificate',
    {'OTPTBSCertificate',v3,5530876617007198567,
        {'SignatureAlgorithm',{1,2,840,113549,1,1,11},'NULL'},
        {rdnSequence,
            [[{'AttributeTypeAndValue',{2,5,4,6},"DE"}],
             [{'AttributeTypeAndValue',
                  {2,5,4,7},
                  {utf8String,<<"XXX">>}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,8},
                  {utf8String,<<"XXX">>}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,10},
                  {utf8String,
                      <<"XXX">>}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,11},
                  {utf8String,<<"XXX">>}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,3},
                  {utf8String,<<"XXX">>}}],
             [{'AttributeTypeAndValue',
                  {1,2,840,113549,1,9,1},
                  "XXX"}]]},
        {'Validity',
            {utcTime,"210121082300Z"},
            {utcTime,"260121082300Z"}},
        {rdnSequence,
            [[{'AttributeTypeAndValue',{2,5,4,6},"--"}],
             [{'AttributeTypeAndValue',
                  {2,5,4,8},
                  {printableString,"XXX"}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,7},
                  {printableString,"XXX"}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,10},
                  {printableString,
                      "XXX"}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,11},
                  {utf8String,<<"XXXt">>}}],
             [{'AttributeTypeAndValue',
                  {2,5,4,3},
                  {printableString,"XXX"}}],
             [{'AttributeTypeAndValue',
                  {1,2,840,113549,1,9,1},
                  "XXX"}]]},
        {'OTPSubjectPublicKeyInfo',
            {'PublicKeyAlgorithm',{1,2,840,113549,1,1,1},'NULL'},
            {'RSAPublicKey',
                233...,
                65537}},
        asn1_NOVALUE,asn1_NOVALUE,
        [{'Extension',
             {2,5,29,14},
             false,
             <<185,253,64,225,49,181,158,232,221,81,41,...>>},
         {'Extension',
             {2,5,29,35},
             false,
             {'AuthorityKeyIdentifier',
                 <<123,194,183,112,183,157,31,10,...>>,
                 asn1_NOVALUE,asn1_NOVALUE}},
         {'Extension',{2,5,29,37},false,[{1,3,6,1,5,5,7,3,...}]},
         {'Extension',
             {2,5,29,17},
             false,
             [{iPAddress,<<160,83,1,248>>},
              {iPAddress,<<80,156,207,8>>}]}]},
    {'SignatureAlgorithm',{1,2,840,113549,1,1,11},'NULL'},
    <<67,211,123,80,110,75,232,0,240,108,131,60,32,154,79,
      214,107,225,120,53,38,176,41,113,164,...>>}
```

**Comment by IngelaAndin** [comment]
Thank you, and yes of course the certificate will not have changed.
I wanted to know the signature algorithm, which corresponds to
public_key (ASN-1) macro:

`-define('sha256WithRSAEncryption', {1,2,840,113549,1,1,11}).`

Which should still be supported by default. We have changed the
defaults in the RC (removed default support for algorithms considered weak) and we missed one that was included  in the release but not in the RC. However you are not using that one.
Another change that was done fairly late was that we made a new function to list signature algorithms to facilitate customization for those how need to interop with legacy systems. When doing this function we realized that  some algorithms where duplicated in the
default list due to the same algorithm having a TLS-1.2 and TLS-1.3 name, so we decide that the TLS-1.3 name should be used if both versions are supported. 

Could you try setting `signature_algs` in your client   to
`{signature_algs, [eddsa_ed25519,eddsa_ed448,ecdsa_secp521r1_sha512,
 ecdsa_secp384r1_sha384,ecdsa_secp256r1_sha256,
 rsa_pss_pss_sha512,rsa_pss_pss_sha384,rsa_pss_pss_sha256,
 rsa_pss_rsae_sha512,rsa_pss_rsae_sha384,rsa_pss_rsae_sha256,
 rsa_pkcs1_sha512,rsa_pkcs1_sha384,
 {sha256, rsa},
 {sha512,ecdsa},
 {sha384,ecdsa},
 {sha256,ecdsa}]`

Note that I change the algorithm name of your cert to TLS-1.2 format. This should not matter but we might have uncovered a bug in filtering/conversion functions.

I would also be interested to see the server hello messages form your scenarios.

**Comment by IngelaAndin** [comment]
It does help, I realized it was actually the server certificate request that I wanted to see and not the server hello.
Anyway I it was not a bug in the conversion functions, but rather that the where not run due to a legacy clause matching. I think I have a solution, I will make a PR as soon as the test suites have run. (Takes a while to run the TLS suites).

**Comment by IngelaAndin** [comment]
@hzeus Once I fixed the first problem it turned out there was some more things needing adjusting too. But now I think my PR should solve your problem. I will work on an additional test case.

**Comment by hzeus** [comment]
@IngelaAndin Thank you very much! I just tested your branch with our application and could successfully make a request 🎉

**Comment by IngelaAndin** [comment]
I have now added client certification to some test cases that will regression test this. If all goes well we should be able to merge this tomorrow and I will schedule it for upcoming OTP-26 patch.

**Comment by hzeus** [comment]
@IngelaAndin Sorry to bother you again: I just tried to perform the HTTP Request after upgrading to 26.0.1, but I got the same error message as before - it seems that I either did a mistake when I tried the request some weeks ago, or that there was some kind of regression that was introduced in one of the later commits.

Do you want me to open another issue for that? And should I be doing the same debugging steps as before, or do you already have enough information?

**Comment by IngelaAndin** [comment]
I think that the problem is likely that the client is not able to verify that its certificate chain is signed by a root CA that is present in the certificate_authorities presented by the server in its certificate-request message.   This could possible be because the client is only configured with its own cert and does not have it chain certificates.  It is possible to configure an erlang TLS server to not send an certificate_authorities extension and then it might accept a client that only send its own cert and not the chain, if the server is able to recreate the chain. But the client is suppose to send it whole chain.  And if the certificate_authorites extension is sent the client will only send a certifcate that adheres to it.

**Comment by hzeus** [comment]
Before I dig deeper into the tls algorithm: I just checked your previous suggestion with setting the `signature_algs` - Parameter; and could successfully make a request.

I could then boil it down to setting `signature_algs` to only `[{sha256, rsa}]` and make a successful request. Is there any chance this might be a regression bug in detecting the correct algorithm?

**Comment by hzeus** [comment]
@IngelaAndin Thank you, that helped 👍
