### ISSUE TITLE
[socket] Blocking `accept` call creates stray select handle

### ISSUE THREAD

**Issue by digitalcora** [erlang/otp#7328]
### Description

I accidentally performed some `socket` operations in the wrong order, and in doing so, found a strange behavior I think is a bug. In summary, when the following occurs in order:

1. a `socket:accept` call is made with `nowait` (on a Unix system, generating a "select handle")
2. a blocking `accept` call is made, and times out
3. a client connects to the socket, triggering the select

...then the process receives a `select` socket message, but with a _different_ select handle than the one returned from the `nowait` call. No message is ever received for the original select handle. It's as though the blocking `accept` call consumes it, and generates a new one in its place.

### Reproduction

This escript demonstrates the odd behavior:

```erlang
#!/usr/bin/env escript
%%!
main(_) ->
    {ok, Socket} = socket:open(inet, stream),
    ok = socket:listen(Socket),
    {ok, Addr} = socket:sockname(Socket),
    % ok = socket:setopt(Socket, {otp, debug}, true),

    % show handle returned from nowait accept
    {select, {select_info, _, Handle}} = socket:accept(Socket, nowait),
    erlang:display(Handle),

    % perform a blocking accept that will fail
    % comment this out and the issue disappears!
    {error, timeout} = socket:accept(Socket, 500),

    % spawn a client to connect
    spawn(fun() ->
        {ok, ClientSocket} = socket:open(inet, stream),
        ok = socket:connect(ClientSocket, Addr),
        timer:sleep(infinity)
    end),

    receive
        % this never seems to arrive...
        {'$socket', Socket, select, Handle} ->
            erlang:display("received matching handle")
    after 1000 ->
        receive
            % ...but a different handle *does* arrive
            {'$socket', Socket, select, OtherHandle} ->
                erlang:display("received other handle"),
                erlang:display(OtherHandle)
        end
    end.
```

When I run this, I get the output:

```
#Ref<0.2209183972.3221487620.174173>
"received other handle"
#Ref<0.2209183972.3221487620.174175>
```

### Expected behavior

I would expect the above script to output "received matching handle".

I think it's correct that the blocking `accept` times out, as it's documented that when a select is in progress, the socket is "locked" and calls of the same type won't go through until the select is completed or canceled. It just also has this strange "side effect" of changing the handle that's eventually received.

### Affected versions

I see this behavior on Erlang 25.3 and 26.0.

### Additional context

Socket debug output:

```
SOCKET [31-May-2023::10:06:09.430411] [unknown] esock_setopt_otp_debug {19} -> ok
   eVal: true
SOCKET [31-May-2023::10:06:09.431285] [unknown] nif_accept#Ref<0.2209183972.3221618692.174171>), {19,0x2} ->
   ReqRef:                #Ref<0.2209183972.3221487620.174173>
   Current Acceptor addr: 0x0000000000000000
   Current Acceptor  pid: undefined
   Current Acceptor  mon: undefined
   Current Acceptor  env: 0x0
   Current Acceptor  ref: undefined
UNIX-ESSIO [31-May-2023::10:06:09.432701] [unknown] essio_accept {19} -> try accept
UNIX-ESSIO [31-May-2023::10:06:09.432854] [unknown] essio_accept_listening_error {19} -> would block - retry
SOCKET [31-May-2023::10:06:09.433180] [unknown] esock_monitor {19} [<0.9.0>] essio_accept_listening -> current acceptor: try monitor
SOCKET [31-May-2023::10:06:09.433614] [unknown] esock_monitor {19} [<0.9.0>] essio_accept_listening -> current acceptor: monitor ok: #Ref<0.2209183972.3221487620.174174>
UNIX-ESSIO [31-May-2023::10:06:09.433934] [unknown] essio_accept_listening_error {19} -> retry for:
   Current Pid: <0.9.0>
   Current Mon: #Ref<0.2209183972.3221487620.174174>
SOCKET [31-May-2023::10:06:09.434397] [unknown] nif_accept(#Ref<0.2209183972.3221618692.174171>) -> done with
   res: select
SOCKET [31-May-2023::10:06:09.434910] [unknown] nif_accept#Ref<0.2209183972.3221618692.174171>), {19,0x106} ->
   ReqRef:                #Ref<0.2209183972.3221487620.174175>
   Current Acceptor addr: 0x000055cb308578b0
   Current Acceptor  pid: <0.9.0>
   Current Acceptor  mon: #Ref<0.2209183972.3221487620.174174>
   Current Acceptor  env: 0x55CB308C8A10
   Current Acceptor  ref: #Ref<0.2209183972.3221487620.174173>
UNIX-ESSIO [31-May-2023::10:06:09.435885] [unknown] essio_accept_accepting -> check: is caller current acceptor:
   Caller:      <0.9.0>
   Current:     <0.9.0>
   Current Mon: #Ref<0.2209183972.3221487620.174174>
UNIX-ESSIO [31-May-2023::10:06:09.436393] [unknown] essio_accept_accepting {19} -> current acceptor
UNIX-ESSIO [31-May-2023::10:06:09.436615] [unknown] essio_accept_accepting_current {19} -> try accept
UNIX-ESSIO [31-May-2023::10:06:09.436826] [unknown] essio_accept_accepting_current_error {19} -> would block: try again
SOCKET [31-May-2023::10:06:09.437078] [unknown] nif_accept(#Ref<0.2209183972.3221618692.174171>) -> done with
   res: select
UNIX-ESSIO [31-May-2023::10:06:09.935556] [unknown] essio_cancel_accept(#Ref<0.2209183972.3221618692.174171>), {19,0x106} ->
   opRef: #Ref<0.2209183972.3221487620.174175>
   with acceptor
UNIX-ESSIO [31-May-2023::10:06:09.936018] [unknown] essio_cancel_accept(#Ref<0.2209183972.3221618692.174171>) -> done with result:
   not_found
```

**Comment by bmk** [comment]
Actually, each process cannot have more than one "active" accept.
The second accept call destroys some of the data we store for each request.
As it turns out we are missing a check; That the process already have an
active request. Otherwise, we could end up with processes "spamming"
the nif with requests.
So, it should *not* be allowed to add a *new* request, but we have no check for this.
We instead assume that its the second call, that is made after receiving the select message...

**Comment by bmk** [comment]
It turns out that it was a bit more complicated.
You are allowed to make repeated calls, *but* only the *last* call is actually active/valid.
So, in your case, the first (nowait-) call for which you received the 'Handle', is no longer
valid once the second call (with timeout 500) is made.

The problem was that we did not update the internal data when the second call was made,
and when that request timed out and was supposed to be canceled, we had no info about that request
and no cancel was actually made. When the client eventually connected, the select was triggered and
the (select-) message sent (with the handle that had never been exposed to you).

We also need to update the documentation to clarify that only the last (accept) call is actually valid.

**Comment by digitalcora** [comment]
If only one call can be "active" at a time, is this a case where an `abort` message should have been sent for the first handle? I'm still unclear on exactly when that can happen; it would be nice if the full type was documented. Of course, that doesn't change the issue of the "internal" select handle escaping from the second call.

**Comment by bmk** [comment]
This only applies to Unix (that's where we use select).

You are not supposed to make more than one "initial" nowait-call
to accept (or any other function that takes the nowait argument).
After the initial call, you should wait for the select message,
and *then* make the final call

The idea is that the sequence should look like this:

        1) Make the initial nowait-call
        2) Wait for the select message
            (assuming that the initial call returned a select)
        3) Make the final call (and get the result).

If you do two calls after each other, the second call
(assuming it does not resolve) will result in another
(nif) select request, which will simply replace the previous
(select-) request.

You *can* make multiple calls (after the fix). There is no point,
but you can.

In your case, the second call was a call with a timeout. This time'ed
out. When this happens, 'socket' attempts to cancel the request.
This is where our bug triggered. During the second call, we did
not update our data structures with the new handle (reference()).
So, when we attempted to cancel the request, the nif could not
find it (it had only info about the original request), so no cancel
of the active select was made. Then when the client connected,
the select triggered, and the message (with the handle from the
second call, which had not been cancelled) the was sent.

So, the fix is a one-liner, add an update of the handle of the
"new" handle (with each new call).

Regarding the abort message (for the previous call), I will check
how that will work.

**Comment by bmk** [comment]
Solution now merged (into maint and master).
Planned to be released with 25.3.2.3 and 26.0.2

**Comment by bmk** [comment]
Patch 26.0.2 has been released.

**Comment by bmk** [comment]
Patch 25.3.2.3 has been released.
