### ISSUE TITLE
erlang:halt() is hanging due to dangling port

### ISSUE THREAD

**Issue by toffea** [erlang/otp#7438]
**Describe the bug**
During circumstances described below `erlang:halt()` will hang for about 15 minutes before terminating.

__NOTE__: I'm not sure this should be considered a "bug" or "work as intended", but we really want your input and comment. Thx

**To Reproduce**
1. start two vanilla OTP distribution nodes, n1 and n2.
2. connect nodes
3. make sure we have lots of messages in `send_q` of distribution socket 
4. disconnect the network between the nodes
5. wait for `dist_util` tick timeout to kick in. `The detection time interval is thus, by default, 45s < DT < 75s` .... `** Node n2@h02 not responding **`
6. `dist_util:con_loop()` process does `exit(shutdown)`. Process dies, but port is left open (dangling?) with following state:  
      `80  prim_inet 16856 114035 <0.92.0> 192.168.100.101:39342 192.168.100.103:43069 BY:cd:O   STREAM`
7. the port will stay in this state for about 15 min before terminating.

__NOTE:__ 
- step 3 above seem to be required to trigger the described behavior
- `erlang:halt([{flush, false}]).` does not seem to trigger the behavior

**Expected behavior**
Expected behavior is that `erlang:halt()` should terminate even though it has one of it's peers disconnected. At least I expect the erlang argument  `-shutdown_time` to work.  

**Affected versions**
This has been reproduced on OTP versions `25.1.2`, `25.3.2.2` and `26.0.1` for both TCP and TLS distribution. Tests has mainly been running on `qemu` VMs with 2GB ram and 1 vCPU running Alpine linux. Host OS is Ubuntu 22.04.2 LTS.  

**Additional context**

With `strace`, `ss` and `netstat` we traced the behavior to `inet_drv.c` driver and our guess is that the state `BY:cd:O` somehow means `BUSY`. Maybe busy with flushing the `send_q`?

Killing the erlang port when it is in state `BY:cd:O` has no effect, but killing the socket with for example `ss -K dst 192.168.100.108 dport = 4668` terminates the vm. 

Nodes have been started with `erl -boot ./start_clean_tcp_25_1_2 -setcookie trams -proto_dist inet_tcp -sname n1` with boot files generated (one for each OTP version tested) from `.rel` files like:
```
{release, {"Erlang/OTP","25"}, {erts, "13.1.2"},
 [{kernel,"8.5.1"},
  {stdlib,"4.1.1"}
 ]}.
```

Below is captured output during the behavior for nodes named: `n1@h01` and `n3@h03`

```
%% … BEFORE

(n1@h01)4> inet:i().
Port Module   Recv Sent Owner    Local Address         Foreign Address       State        Type   
24   inet_tcp 0    0    <0.61.0> *:38131               *:*                   ACCEPTING    STREAM 
40   inet_tcp 6    17   <0.59.0> localhost:45080       localhost:epmd        CONNECTED(O) STREAM 
80   inet_tcp 2241 2130 <0.92.0> 192.168.100.101:52086 192.168.100.103:32791 CONNECTED(O) STREAM 
ok

%%… disconnect node n3@h03
%%… after detection timeout 

(n1@h01)19> =ERROR REPORT==== 21-Jun-2023::08:40:20.972214 ===
** Node n3@h03 not responding **
** Removing (timedout) connection **

(n1@h01)19> inet:i().
Port Module    Recv  Sent  Owner     Local Address         Foreign Address       State        Type   
24   inet_tcp  0     0     <0.61.0>  *:38131               *:*                   ACCEPTING    STREAM 
40   inet_tcp  6     17    <0.59.0>  localhost:45080       localhost:epmd        CONNECTED(O) STREAM 
80   prim_inet 13391 98020 <0.92.0>  192.168.100.101:52086 192.168.100.103:32791 BY:CD:O      STREAM 
696  inet_tcp  0     0     <0.114.0> 192.168.100.101:59702 *:*                   CG:O         STREAM 
ok

=port:#Port<0.10>
State: CONNECTED|BINARY_IO|CLOSING|PORT_LOCK
Task Flags: EXITING
Slot: 80
Connected: <0.92.0>
Port controls linked-in driver: tcp_inet
Input: 12760
Output: 42
Queue: 8248
Port Data: inet_tcp

%%… PROCESS DEAD, BUT DANGLING PORT

(n1@h01)21> i(0,92,0).
undefined

(n1@h01)22> inet:i(). 
Port Module    Recv  Sent  Owner     Local Address         Foreign Address       State        Type   
24   inet_tcp  0     0     <0.61.0>  *:38131               *:*                   ACCEPTING    STREAM 
40   inet_tcp  6     17    <0.59.0>  localhost:45080       localhost:epmd        CONNECTED(O) STREAM 
80   prim_inet 13391 98020 <0.92.0>  192.168.100.101:52086 192.168.100.103:32791 BY:CD:O      STREAM 
1112 inet_tcp  0     0     <0.197.0> 192.168.100.101:58820 *:*                   CG:O         STREAM 
ok

%%… KILL PORT

(n1@h01)23> exit(#Port<0.10>, kill).
true

(n1@h01)24> inet:i().               
Port Module    Recv  Sent  Owner     Local Address         Foreign Address       State        Type   
24   inet_tcp  0     0     <0.61.0>  *:38131               *:*                   ACCEPTING    STREAM 
40   inet_tcp  6     17    <0.59.0>  localhost:45080       localhost:epmd        CONNECTED(O) STREAM 
80   prim_inet 13391 98020 <0.92.0>  192.168.100.101:52086 192.168.100.103:32791 BY:CD:O      STREAM 
1184 inet_tcp  0     0     <0.204.0> 192.168.100.101:49696 *:*                   CG:O         STREAM 
ok

%%… NO EFFECT. CONTINUE FOR 15 MINUTES STARTING FROM DETECTION

(n1@h01)30> inet:i().
Port Module   Recv Sent Owner     Local Address         Foreign Address State        Type   
24   inet_tcp 0    0    <0.61.0>  *:38131               *:*             ACCEPTING    STREAM 
40   inet_tcp 6    17   <0.59.0>  localhost:45080       localhost:epmd  CONNECTED(O) STREAM 
2368 inet_tcp 0    0    <0.447.0> 192.168.100.101:56904 *:*             CG:O         STREAM 
ok
```

**Comment by rickard-green** [comment]
When halting with the option `[{flush,true}]` (which is the default), halt is delayed until all currently open ports have flushed their send queues and terminated. A port with a send queue will first flush the send queue before closing the connection and then terminate. If the network is down between the nodes, it may take a very long time before the network stack flags the connection as terminated. When this happens the port will be able to terminate even though it has not been able to flush the send queue.

If you pass the following on the command line `-kernel inet_dist_connect_options '[{linger,{true,0}}]' -kernel inet_dist_listen_options '[{linger,{true,0}}]'`, the distribution ports wont even try to flush the send queue which will make your problem go away. Note that this is the only configuration which will prevent the `halt()` from hanging this long. `[{linger,{true,1}}]` will still cause the same long timeout since it will still try to flush (which will block). I don't see why we should not default to `[{linger,{true,0}}]` since there are no guarantees that sent signals will reach the other node when a connection is lost. This will probably be the default configuration in some future OTP version.

**Comment by rickard-green** [comment]
Perhaps another solution than `[{linger,{true,0}}]` will be introduced instead, but we will have a look at this.

**Comment by toffea** [comment]
Thx for the response. I will give it a try when I'm back from vacation.

**Comment by toffea** [comment]
Hi OTP-team, 

any progress or plans in changing the defaults (on any other solution) to handle this situation in a general manner?

Thx
/Toffe

**Comment by rickard-green** [comment]
We don't think that we should change the default regarding `linger` as I talked about above, since it will always cause the other end to see the connection takedown as an error even when it is not. It would also only handle the specific scenario with flushing a distribution port. There are more flushing operation than that that can cause `halt()` to hang for a very long time. Instead I've created a PR #8035 implementing a flush timeout for `halt()` which one can use in order to prevent a very long halt time.
