### ISSUE TITLE
OTP 26.1 get stuck when compiling gun

### ISSUE THREAD

**Issue by RoadRunnr** [erlang/otp#7667]
**Describe the bug**

When trying to compile gun (https://github.com/ninenines/gun) under OTP 26.1, the compiler never finishes.

**To Reproduce**

with OTP-26.1 installed from kerl:
```
git clone https://github.com/ninenines/gun
cd gun
rebar3 compile
```

I have been able to narrow the problem down to `src/gun_public_suffix.erl`, e.g.:

```
gun$ erl
Erlang/OTP 26 [erts-14.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]

Eshell V14.1 (press Ctrl+G to abort, type help(). for help)
1> c("src/gun_public_suffix.erl").

 .... not response and 100% CPU load ....
```

**Expected behavior**

compilation finishes

**Affected versions**

OTP-26.1

**Additional context**

OS: Ubuntu 23.10
rebar3: 3.22.0
OTP-26.1 compiled from source with kerl, no special options

**Comment by sile** [comment]
I am facing a similar issue (in my m1 mac laptop, the compilation of `gun_public_suffix.erl` can finish, but  it takes more than 2 minutes in OTP 26.1).

It appears that the `beam_ssa_alias:aa_merge_1()` function is being called excessively during the module compilation. Therefore, I think that the problem was introduced by #7448.
