### ISSUE TITLE
OTP 26.1/OpenSSL 3.0.9 `erl -crypto fips_mode true` does not start with fips enabled

### ISSUE THREAD

**Issue by pjk25** [erlang/otp#7693]
**Describe the bug**
The erl args `-crypto fips_mode true` should start the crypto application with fips enabled, but does not when used with OpenSSL 3.0.9. `crypto:info_fips().` will return `not_enabled`, but then `crypto:enable_fips_mode(true).` returns true, then `crypto:info_fips().` will return enabled.

**To Reproduce**
With Photon OS 4.0, install openssl-devel and openssl-fips-provider packages with tdnf.
Build OTP 26.1, configured with `--with-ssl=/ --with-ssl-incl=/usr --enable-fips`
Run `erl -crypto fips_mode true` and then `crypo:info_fips()`.

**Expected behavior**
`crypto:info_fips()` should return `enabled` when erl is started this way

**Affected versions**
26.1

**Comment by sverker** [comment]
You have to start the `crypto` application first (or at least load it).
```
> erl -crypto fips_mode true

1> application:load(crypto).
ok
2> crypto:info_fips().
enabled
```
The application `crypto` must be loaded before the module `crypto` is loaded.
The configuration parameters `-crypto fips_mode true` does thus not work very well as a safety feature, to prevent accidental usage of a non-fips implementation, as it can easily be bypassed by (accidentally) loading the `crypto` module before the application is loaded/started. For example calling `crypto:start()` will not do the same thing as `application:start(crypto)` in this regard, as it will first load module `crypto` (in order to call `start`) and then start the application.

**Comment by pjk25** [comment]
@sverker thanks for clarifying, sorry for the misunderstanding on my part.
