### ISSUE TITLE
OTP 26 shell won't reset terminal interrupt on exit

### ISSUE THREAD

**Issue by zzydxm** [erlang/otp#7832]
**Describe the bug**

Open a shell with
```erl +Bc```
exit it through ```init:stop().``` or any other way.

Then open a new shell in the same terminal using ```erl```

The shell won't exit when pressing Ctrl + C

Any other tools like ```tail```, ```top``` won't be able to handle Ctrl + C correctly.

**Expected behavior**
The terminal tty setting should not be permanently changed

**Affected versions**
OTP 26, CentOS 8

**Comment by garazdawi** [comment]
The issue was introduced in: https://github.com/erlang/otp/commit/5bb388471f293677e518c9de5ff803200a8957f8

The start order of erl_child_setup vs when break handlers are installed cause erl_child_setup to read a tty with Ctrl-C already disabled and thus it is not restored to the correct value.

I need to think a bit about what to do there to make it correct.

**Comment by garazdawi** [comment]
Fix available in #7893, would be great if you could test it in your original usecase just to make sure that it works as it should.
