### ISSUE TITLE
maps:to_list order differs from iterator order

### ISSUE THREAD

**Issue by michalmuskala** [erlang/otp#7851]
**Describe the bug**
The following property does not hold for maps today:
```
maps:to_list(Map) =:= maps:to_list(maps:iterator(Map))
```

While maps have no guaranteed order (specifically "undefined order" following documentation), this doesn't necessarily mean there's no order whatsoever. Getting different order depending on the operation used seems surprising and error-prone.

**Expected behavior**
Maps should have an unspecified, but consistent iteration order - the order elements are returned should be the same for all different ways of iterating a map with the default, unspecified order. Be it `maps:values/1`, `maps:keys/1`, `maps:to_list/1`, `maps:iterator/1` or map comprehensions.

**Affected versions**
Tested on OTP 26.

**Comment by garazdawi** [comment]
As you say there is no such guarantee and so far we have been reluctant to give it. Maybe at some point in the future the insertion order into the map will matter to how it is iterated and then two seemingly equal maps will iterate differently.

That being said, the default iterator is today just the reversed from what to_list does. So:

 ```erlang
maps:to_list(Map) =:= lists:reverse(maps:to_list(maps:iterator(Map))).
```

should always be true in the current implementation.

**Comment by michalmuskala** [comment]
I think the place where this is problematic today is in transition to map comprehensions since:
```erl
[foo(X, Y) || {X, Y} <- maps:to_list(Map)]
```
and
```erl
[foo(X, Y) || X := Y <- Map]
```
give different orders.

And I fully agree on the order being unspecified. But I'd expect the order to be the same between different ways of iterating, if not otherwise specified.

**Comment by garazdawi** [comment]
If you compare the speed of `maps:to_list(Map)` and `maps:to_list(maps:iterator(Map))` you will notice that `maps:to_list/1` with a map is about 2x faster than `maps:to_list/1` with an iterator. This is possible because there is no guarantee about iteration order (or rather the order in which `maps:to_list/1` returns elements when the argument is a map).

So would say that it is good that we don't specify this as it already allows us to make optimizations and who knows what the future will bring.
