### ISSUE TITLE
INSTALL_* variables in make scripts don't preserve timestamps

### ISSUE THREAD

**Issue by jchristgit** [erlang/otp#7900]
**Is your feature request related to a problem? Please describe.**
At the moment, when running tests via "make test", the `INSTALL_*` variables are used to copy the test files into the target directory. These use the `install` command under the hood but do not preserve the timestamps, causing constant copying of the files and recompilation of files in test suites since the modification time has changed.

**Describe the solution you'd like**
Unchanged files should not be copied by the install script, or the modification timestamp should be preserved to prevent tooling from doing extra work.

**Describe alternatives you've considered**
`install -C` seems like it could work, but I'm not sure if this is portable to all platforms. The configure scripts mention BSD install, which seems to support the option. https://man.freebsd.org/cgi/man.cgi?query=install

**Comment by garazdawi** [comment]
It is standard procedure for any install command to update the timestamp of the files. This so that all files get the timestamp of when the installation was done and not when the build was done.

The behaviour can be overridden by doing `./configure INSTALL="`which install` -C"`, but that needs to be done at configure so is not very convenient.

I'm unsure if it would be ok to change INSTALL and INSTALL_DATA to be configurable at make install time instead of at configure time.

**Comment by jchristgit** [comment]
Thank you for the explanation! I was thinking a bit narrow just looking at the tests here, the installation timestamp definitely makes more sense in the grand scheme of things.

`make INSTALL_DATA="install -C" test` actually seems to work and do what I was looking for, so it seems to be configurable via `make` after all? I'm closing this then, thank you for the help :slightly_smiling_face:

**Comment by garazdawi** [comment]
> so it seems to be configurable via `make` after all?

what do you know, I was not expecting that to work.
