### ISSUE TITLE
False positive dialyzer warnings

### ISSUE THREAD

**Issue by profetasajt** [erlang/otp#7967]
Dialyzer reports such type of warnings that could be resolved inside of case statement. 

Here is a sample: 

[bnf_parser.erl.txt](https://github.com/erlang/otp/files/13694782/bnf_parser.erl.txt)
[bnf_types.hrl.txt](https://github.com/erlang/otp/files/13694783/bnf_types.hrl.txt)

Now it throws such kind of errors (sample): 

"The pattern .... can never match the type {'error',[1..255,...],string()}"
"Function .... has no local return" 
"Function ... will never be called"

bnf_parser.erl:274:2: Invalid type specification for function bnf_parser:hex_digit/1.
 The success typing is bnf_parser:hex_digit
          ('rest') -> {'error', [1..255, ...], 'rest'}
 But the spec is bnf_parser:hex_digit
          (Input) -> Result :: success(hex_digit()) | error()
             when Input :: input()
 They do not overlap in the 1st argument, and the return types do not overlap

Line 277 Column 1: The pattern [C | Rest] can never match the type 'rest'

Affected versions where it tested: 25, 26.2

This kind of indirection types seems hard to dialyzer. IMHO, it expected to resolve such kind of types properly.  Also the line 277 error is very strange as the rest() and input() has common ancessor type of string().

**Comment by jhogberg** [comment]
Hi! Thanks for your report, but this is not an error in `dialyzer`.

> Dialyzer reports such type of warnings that could be resolved inside of case statement.

... but they cannot be "resolved." Consider the warning for line 384: because you passed the _atom_ `rest` to `hex_number/1` by mistake  instead of the variable `Rest`, `hex_number/1` cannot possibly return `{ok, Number, Rest}`, so you get a warning there.

> the line 277 error is very strange as the rest() and input() has common ancessor type of string().

Same thing there, _the atom_ `rest` and `input()` have nothing in common at all.

The other errors you see aren't much different -- they're either caused by a problem with your code or your specs.

> This kind of indirection types seems hard to dialyzer. IMHO, it expected to resolve such kind of types properly.

It's important to remember that `dialyzer` is not a type checker. `-type xxx()` is merely an alias for a set of possible values, and `-spec` is merely a way to _further restrict_ the range and domain of a function _on successful return_.

Everything is still constrained by the code itself: the only possible input value for `hex_digit/1` is `rest`, so the spec which says it may have any value described by `input()` is invalid because they don't overlap.

I hope that clears things up a bit. :)

**Comment by profetasajt** [comment]
Thanks for clarification, Yepp, that line missed a capital "R". 

But asking again:  what about this kind of warnings: "Line 22 Column 5: The pattern {'ok', Rule, Rest} can never match the type {'error',[1..255,...],string()}" ? 

line 21:
  case rule(Input)  of
    **{ok, Rule, Rest}** ->  .......
    **{error, _, _}** = E -> E
  end.

As you can see, the {error, _, _} resolved later in same case statement and that kind of warnings are simply unecessary as the case clause handle it as it intended (and ofc. 'ok' will never match with 'error')...

**Comment by jhogberg** [comment]
> As you can see, the {error, _, _} resolved later in same case statement and that kind of warnings are simply unecessary as the case clause handle it as it intended (and ofc. 'ok' will never match with 'error')...

They aren't unnecessary: with the code and specs that you have provided, there is no way for `rule/1` to return `{ok, Rule, Rest}`.
