### ISSUE TITLE
New doc search issues

### ISSUE THREAD

**Issue by essen** [erlang/otp#8321]
**Describe the bug**
The doc search is sub-optimal with the new docs.

There used to be Algolia (https://www.erlang.org/doc/search?q=ssl) which could be quite powerful to navigate the entirety of the documentation. Now it only provides links that are served by HexDocs.

The HexDocs search does not let us navigate the entirety of the documentation however.

If I am on https://www.erlang.org/docs/27/apps/ssl/ssl# and search for "design" I get this: https://www.erlang.org/docs/27/apps/ssl/search.html?q=design

In order to find the design principles documentation I need to first click on the Erlang logo, which gets me to https://www.erlang.org/docs/27/readme.html and then searching for "design" I get https://www.erlang.org/docs/27/search.html?q=design which gives me what I looked for: https://www.erlang.org/docs/27/system/design_principles.html

It seems that the HexDocs search is not just one search but many searches depending on your location. From my point of view however, I am trying to search the OTP docs in their entirety, not a specific application (at least by default). So they do not do their work correctly.

Worse, going back to Algolia results (https://www.erlang.org/doc/search?q=ssl), by searching for "ssl" I could reach https://www.erlang.org/docs/27/apps/ssl/ssl_crl_cache# immediately. Today, if I search for "ssl" I only get the ssl application, and "ssl_crl_cache" (https://www.erlang.org/docs/27/search.html?q=ssl_crl_cache) gives me nothing. So it appears that for me to reach the documentation for the ssl_crl_cache I need to perform two searches or click my way through. This is sub-optimal as this completely breaks the shortcut I have in my browser's address bar.

**Expected behavior**
It was working before, don't fix it!

**Comment by dumbbell** [comment]
Another regression I just noticed with the search: the first results are clearly not the ones I would expect.

For instance I'm reading the `gen_server` doc and search for `start_link`. Now, the first results are from `peer` and `slave`, the ones from the latter being event deprecated (and stroke through in the search results).

![20240328_123452](https://github.com/erlang/otp/assets/159804/f0906ea9-35a9-4096-b8bc-b7a7d755cb4a)

Is it because I read the `peer` docs a few minutes earlier and it tracks that? I hope not.

**Comment by garazdawi** [comment]
I have prepared algolia to be used with the new docs, I just haven't enabled it yet for the release candidates. It will be a bit different, but should offer the same functionality as we have now.

In the long run we hope that the ex_doc/hexdocs team will [finish their search solution](https://github.com/elixir-lang/ex_doc/issues/1811) so that we can use that as it should be better than what we have today.
