### ISSUE TITLE
edlin_expand:expand/2 returns invalid Element when matching on functions with 0-arity and higher arity exports

### ISSUE THREAD

**Issue by potatosalad** [erlang/otp#8364]
**Describe the bug**

For functions that have a 0-arity clause and also have 1-or-more-arity clauses, the return value from `edlin_expand:expand/2` currently violates the defined type spec for the function.

An example of this would be `erlang:get/0` when entered as `get(` in the shell and then pressing `<TAB>`.

Other examples include `erlang:alias/0` and `persistent_term:get/0` and many others.

`Element` is defined in the type spec as `{string(), [ElementOption]}`, but in the affected case it returns a `string()` exactly equal to `")"`.

**To Reproduce**

```erl
1> get(<TAB>
typespecs
erlang:get(Key)
any()
erlang:get()
) % <- invalid Element
```
<img width="352" alt="Monosnap erl 2024-04-10 13-00-06" src="https://github.com/erlang/otp/assets/1804/57c4f61d-fefe-45a5-9091-778916dc7fd8">

```erl
1> edlin_expand:expand(lists:reverse("get("), []).
{no,[],
    [#{options => [highlight_all],
       title => "typespecs",
       elems =>
           [#{options => [{highlight_param,1}],
              title => "erlang:get(Key)",
              elems =>
                  [#{options => [{hide,title}],
                     title => "types",
                     elems => [{"any()",[]}]}]},
            #{options => [],title => "erlang:get()",elems => [")"]}]}]} % <- invalid Element
```

**Expected behavior**

Either one of the following would be expected:

1. The type spec for `edlin_expand:expand/2` is incorrect.
2. The return value including an Element defined as `")"` is incorrect.

If (1), the fix is likely to adjust the type spec for `expand/2` to be:

```erlang
      Matches :: [Element] | [Section],
      Element :: string() | {string(), [ElementOption]},
      ElementOption :: {ending, string()},
```

If (2), I _think_ the corrected Element would be:

```erlang
{yes, ")", [#{title=>MFA, elems=>[{")", []}], options=>[]}]}
```

**Affected versions**

This bug was introduced in https://github.com/erlang/otp/commit/99c1493bb8aebc5b7c28fb63651dc9c4201aa102, so this currently affects the latest OTP-26.2.3 and OTP-27.0-rc2, plus all other released versions of OTP-26.x.

**Additional context**

* https://github.com/erlang/otp/blob/OTP-27.0-rc2/lib/stdlib/src/edlin_expand.erl#L483

**Comment by garazdawi** [comment]
I'm not very familiar with this code so I'll write some of my reasoning here...

From the expand fun there are two possible output modes, "legacy" and "sections". For out `edlin_expand:expand/1` function it always returns "legacy" while the `edlin_expand:expand/2` always returns "sections". This is so that a Erlang/OTP 25 node can call the `edlin_expand` of a 26 node and it will still work (this is how expansion works when using `-remsh`).

Someone that wants to implement their own expansion fun (for example iex in Elixir) can return either the "legacy" or "sections" format from `expand/1` or `expand/2` if they don't care about cross version `-remsh`.

What can be returned by a "legacy" fun is documented in [io:setops/2](https://www.erlang.org/doc/man/io#setopts-2) and what can be returned from a "sections" fun is documented in [edlin_expand](https://www.erlang.org/doc/man/edlin_expand).

What seems to have happened here is that in the fix you mentioned we returned the "legacy" format instead of the "sections" format and it just happened to work because both "legacy" and "sections" end up in the same formatting code.

So I think that solution (2) is the correct solution.

However, maybe we should also incorporate the legacy format into the sections format... in which case we would also want to update the spec to include your (1) changes and also add `arity()` as an alternative to `[ElementOptions]`.

```erlang
      Matches :: [Element] | [Section],
      Element :: string() | {string(), [ElementOption] | arity()},
      ElementOption :: {ending, string()},
```

Anyways.... none of the fixes solves the original issue that we output a ")" to show that there is also a zero arity variant of the function, which I don't actually think is a bug but rather expected behaviour. Something needs to be printed there to show what to do to select that option and might as well be ")". I'll sleep on this and maybe tomorrow I will change my opinion :) 

While poking about I did however find some other bugs: #8365 #8366

**Comment by potatosalad** [comment]
@garazdawi Thanks for taking a look!

> &hellip;we output a ")" to show that there is also a zero arity variant of the function, which I don't actually think is a bug but rather expected behaviour.

I agree the ")" should still be present for 0-arity, I think my initial write-up was unclear that the print-out is valid, but the underlying returned value is invalid according to the type spec.

Related to this, I noticed that for non-zero-arity functions, I don't think there is a way to get a ")" printed out as a valid closing option, for example:

```erl
1> persistent_term:get(<TAB>
typespecs
persistent_term:get(Key)
persistent_term:get(Key, Default)
persistent_term:key() ::     any()
persistent_term:get()
) % <- 0-arity ")"

2> persistent_term:get(xyz<TAB>
% nothing, expand returns `{no,[],[]}`

3> persistent_term:get(xyz,<TAB>
typespecs
persistent_term:get(Key, Default)
persistent_term:value() ::     any()
% 2-arity autocomplete works if a comma "," is included
```

> While poking about I did however find some other bugs: https://github.com/erlang/otp/issues/8365 https://github.com/erlang/otp/issues/8366

Nice!  I began writing a property-based tester for `edlin_expand:expand/2` a while ago, but in order to properly test it, the test model effectively has to be a complete copy of the expand function in order to validate the OTP code.  However, maybe a simplified version could be useful that effectively acts like a fuzzer would be useful for catching edge-cases like this.
