### ISSUE TITLE
Publish JInterface to Maven Central Repository

### ISSUE THREAD

**Issue by p-ssanders** [erlang/otp#8372]
**Is your feature request related to a problem? Please describe.**
I want to use JInterface in my Java projects, but I have to build the JInterface jar from erlang/otp source releases and figure out a way to publish the JInterface jar so my project can treat it like any other dependency.

**Describe the solution you'd like**
I would like a github actions pipeline in this repository that publishes the JInterface jar to the Maven Central Repository. I would like this pipeline to run every time erlang/otp is released, so JInterface users can upgrade their JInterface-dependent projects when they upgrade OTP.

**Describe alternatives you've considered**
Today I've built my own pipeline to:
1. Download a release of erlang/otp
2. Build the JInterface jar
3. Publish the jar as a maven package to a self-managed maven registry
4. Configure JInterface projects to discover the JInterface maven dependency in the self-managed registry

**Additional context**
Seems like there's been some discussion of this in the past, but would appreciate clarity on why this jar isn't published to Maven Central today i.e.: do the project maintainers have a different vision for how JInterface should be consumed?

**Comment by garazdawi** [comment]
Hello!

In the past there have been community members that have uploaded the [Jinterface build to maven](https://mvnrepository.com/artifact/org.erlang.otp/jinterface), but from what I've heard the person that did that has lost interest and access to that account.

We have never published any artifact to any external repository and we don't intend to start doing that. We are however more than willing to aid anyone in the community that wants to setup such a service so that more Java users can access Jinterface. Though if I were designing a project that was using Erlang and Java I would probably use some other protocol to communicate, like protobuf or something like that.

> do the project maintainers have a different vision for how JInterface should be consumed?

We are not Java developers, so don't know anything about how things normally are consumed in the Java world today. I'm not sure that maven even existed when JInterface was originally created, so from what I know it has mostly been consumed as just a `.jar` that is added to the class path when a system is started.
