### ISSUE TITLE
Windows installer (64-bit) for Erlang/OTP 26.2.5.2 is broken and not signed

### ISSUE THREAD

**Issue by big-r81** [erlang/otp#8666]
**Describe the bug**
The [64-bit Windows installer](https://github.com/erlang/otp/releases/download/OTP-26.2.5.2/otp_win64_26.2.5.2.exe) is broken and Erlang can't be installed. The size of the installer is less than half of the 32-bit installer package and the installer isn't correctly signed.

Size of the installers:
![image](https://github.com/user-attachments/assets/612decde-349c-4ec2-96eb-ca4b542c404c)

During installation:
![image](https://github.com/user-attachments/assets/2c940547-c8bd-42b0-8de0-bdfa9c31ad51)

**To Reproduce**
1. Download the [installer](https://github.com/erlang/otp/releases/download/OTP-26.2.5.2/otp_win64_26.2.5.2.exe).
2. Try to install.

**Expected behavior**
Fix the installer and republish it.

**Affected versions**
Erlang/OTP 26.2.5.2 - Windows 64-bit installer

**Comment by paulo-ferraz-oliveira** [comment]
👍

I'd detected this in CI for a library I maintain, but didn't try to install it locally on my desktop (in the lib., since it wasn't important, I just downgraded the test version to 26.1), but with an image it's much clearer.

I initially thought it might be related to changing paths in the installer, but then a report on `setup-beam` made me come here again looking for a report.

I search this repo's CI to check if the Windows installer was being tested on e.g. `windows-2022` but didn't find anything. Perhaps adding it to this repo's CI would make sense (?)

**Comment by waynechen251** [comment]
I have the same issue. Has this problem been resolved?

**Comment by jhogberg** [comment]
Thanks for your report, most of us are on vacation right now but I'll look into this as time allows.

**Comment by jhogberg** [comment]
It should be fixed now, thanks again for your report :-)

**Comment by waynechen251** [comment]
![image](https://github.com/user-attachments/assets/3491910f-2057-4f26-9d32-389503105a9c)
Thanks~

**Comment by big-r81** [comment]
Thx @jhogberg, works again 👍
