### ISSUE TITLE
User-defined verify_fun ignored in Erlang/OTP 24.x and 25.x

### ISSUE THREAD

**Issue by tduccuong** [erlang/otp#9088]
**Describe the bug**
I need to allow self-signed certificate for my server. The Erlang/OTP version is 24.3.4.2. I also tried 25.0 without success. But the same self-signed cert is accepted with Erlang/OTP 21.3.8.2.

The error is:
```
{tls_alert,  {bad_certificate,  "TLS server: In state certify at ssl_handshake.erl:2080 generated SERVER ALERT: Fatal - Bad Certificate\n"}}.
```

Looking at source code of `Erlang/OTP 24.3.4.2`, at `ssl_handshake.erl:2080`, the error revealed is `selfsigned_peer`:
```
path_validation_alert({bad_cert, selfsigned_peer}) ->
    ?ALERT_REC(?FATAL, ?BAD_CERTIFICATE);
```

Using `recon_trace` also confirms it:
```
16:19:36.416228 <0.2131.0> public_key:pkix_path_validation/3 --> {error,{bad_cert,selfsigned_peer}}
```

I digged deeper with `recon_trace`:
```
recon_trace:calls({ssl_gen_statem, handshake_continue, fun(_) -> return_trace() end}, 1).
```

It returns (among with other things that I pruned for the sake of clarity):
```
...
{verify_fun,{#Fun<rel_client.3.59923973>,[]}},
{verify,verify_peer},
...
```

which means my user-defined `verify_fun` is still passed down to this call. But following the Erlang/OTP source code with this `recon_trace` command:
```
recon_trace:calls({ssl_handshake, certify, fun(_) -> return_trace() end}, 1).
```

shows that the value of verify_fun is now:
```
...
verify_fun=>undefined,
...
```

At this point, when the trace comes to path validation, the default OTP `verify_fun` is used as in the below:
```
public_key:pkix_path_validation(selfsigned_peer, [{cert,... {verify_fun, {#Fun<ssl_handshake.8.122428672>, ...
```

**To Reproduce**
Here is the supply when establish SSL connection:
```
[
    {verify_fun, {fun verify/3, []}},
    {verify, verify_peer}
]
```

Here is the `verify/3` function:
```
verify(_, {bad_cert, selfsigned_peer}, UserState) ->
    {valid, UserState};
verify(_, {bad_cert, _} = Reason, _) ->
    {valid, Reason};
verify(_, {extension, _}, UserState) ->
    {unknown, UserState};
verify(_, valid, UserState) ->
    {valid, UserState};
verify(_, valid_peer, UserState) ->
    {valid, UserState}.
```

**Expected behavior**
The certificate should be confirmed as valid.

**Affected versions**
- 24.3.4.2
- 25.0

**Comment by IngelaAndin** [comment]
Latest release is now OTP-27 and a lot happened since 25.0  you need to try out a later release to see if this is a fixed problem. 

The reason you get undefined can be  best described by this commit message :

"The option 'verify' is simulated by the configured 'verify_fun' that
    is mostly hidden from the end user. When 'verify' is set to verify_none,
    the option 'verify_fun' is also set to a default verify-none-verify_fun
    when processing the configuration. If 'verify' is later changed from
    verify_none to verify_peer, the 'verify_fun' must also be changed to
    undefined.  When 'verify_fun' is set to undefined, public_key's default
    verify_fun will be used that performs a full verification." 
    
   So this could also be related to some other fixed bug with providing new options when 
   doing handshake continue.

**Comment by tduccuong** [comment]
Thanks @IngelaAndin for the answer! But sorry for my noob question, I don't quite understand this statement:
```
If 'verify' is later changed from verify_none to verify_peer, the 'verify_fun' must also be changed to undefined.
```

Does that mean that the SSL conn must be established with `verify = verify_peer` right from the start, and any opts changes later to the connection regarding that key will be automatically discarded?

Also, upgrading to Erlang/OTP version > 24.3.4.2 is out of question for my company at the moment, due to tremendous code base upgrades and regression testing. Is there a workaround for `verify_fun` being discarded for now?

Thanks a lot!

**Comment by IngelaAndin** [comment]
> Does that mean that the SSL conn must be established with `verify = verify_peer` right from the start, and any opts changes later > to the connection regarding that key will be automatically discarded?

No it does not mean that.  But it means that if you have configured your connection with a verify_fun but not with {verify, verify_peer} that I believe is not yet default on your release and then change your options during a so called paused handshake and at this time specify {verify, verify_peer}  but not a verify_fun then your verify_fun will be lost, as {verify, verify_none}  is implemented as a verify_fun that accepts all errors and specifying a verify  fun in verify_none mode is an error although it was probably ignored and  verify_none would become "user defined verify". 

I also know there has been some bugs fixed historically where setting of the new options some times accidently keep the old options, although they seem to be fixed before your version.

> Also, upgrading to Erlang/OTP version > 24.3.4.2 is out of question for my company at the moment, due to tremendous code 
> base upgrades and regression testing. Is there a workaround for `verify_fun` being discarded for now?
 
This is your problem, but if you can tell me if it starts working as expected in a later version I might be able to understand where your problem was fixed so that you may work around it.

**Comment by tduccuong** [comment]
@IngelaAndin your explanation helped! I used `verify = verify_peer` and `verify_fun = <custom_fun>` right from the start and it worked (with Erlang/OTP 24 and 25)! Although the behavior is kinda weird to me, but it works now is all that matters!

Thanks a lot for your help @IngelaAndin :+1:

**Comment by IngelaAndin** [comment]
Well if I would have had the privilege to design it from the start, I would not have had the the two options that have a dependency, but rather only had the verify_fun option that defaults to strict and where you may use the fun to customize the verification, adding application specific checks and possible exceptions (or workarounds). But for backwards compatibility reasons that is not the case.
