### ISSUE TITLE
Misleading unused function warning

### ISSUE THREAD

**Issue by TD5** [erlang/otp#9092]
**Describe the bug**

Running `erlc use_via_fun.erl`:

```
-module(use_via_fun).

-export([get_fun/0]).

get_fun() ->
  Fs = [fun use_via_fun:my_function/1],
  Fs.

% Used, but only via a remote function reference above
my_function(Y) -> Y.
```

Gives:

```
use_via_fun.erl:10:1: Warning: function my_function/1 is unused
%   10| my_function(Y) -> Y.
%     | ^
```

**Expected behavior**
No warning, since `my_function/1` is used via a function ref. Notably, we do _not_ get the warning if we reference it as a location function (i.e. as `fun my_function/1` vs. `fun use_via_fun:my_function/1`).

In this case, it's an issue because its temping to believe it is definitely safe to delete the "unused" function, but probably it should be exported instead?

**Affected versions**
OTP 26 & 27

**Comment by TD5** [comment]
@jhogberg going by your change in tag to "not a bug" I reflected a bit more on this and updated the issue to clarify that it's perhaps not "wrong" per se, but perhaps misleading.

**Comment by jhogberg** [comment]
Thanks for your report, but this is not a bug. `my_function/1` is not actually used via a function reference because `fun use_via_fun:my_function/1` refers to the _exported function_ `use_via_fun:my_function/1`, which does not exist (yet) as this is a local function.

I'll see about changing the wording of the warning though, it would be helpful to point out that functions that are unused in this way were probably meant to be exported.

**Comment by TD5** [comment]
Thanks for resolving so quickly!
